import PureSFormal.StrongMultiwayUniversality

/-!
# Result-B aggregate axiom inventory

The release audit permits no logical dependency beyond the empty set or
`propext` alone.
-/

#print axioms PureSFormal.StrongMultiwayUniversality.strongWholeMultiwayUniversality
#print axioms PureSFormal.StrongMultiwayUniversality.strongInitialProjectionEmpty
#print axioms PureSFormal.StrongMultiwayUniversality.strongInitialObserverEmpty
#print axioms PureSFormal.StrongMultiwayUniversality.strongInitialCountedObserverEmpty
#print axioms PureSFormal.StrongMultiwayUniversality.strongObserverOutputHasLiteralCertificate
#print axioms PureSFormal.StrongMultiwayUniversality.strongObserverTargetGenerated
#print axioms PureSFormal.StrongMultiwayUniversality.strongObserverNonconstantOnCone
#print axioms PureSFormal.StrongMultiwayUniversality.strongFairPathEventuallyProjects
#print axioms PureSFormal.StrongMultiwayUniversality.strongFairPathEventuallyLabels
#print axioms PureSFormal.StrongMultiwayUniversality.strongFairMacroSequenceStarts
#print axioms PureSFormal.StrongMultiwayUniversality.strongFairMacroSequenceAdvances
#print axioms PureSFormal.StrongMultiwayUniversality.strongFairMacroSequenceStructurallyFair
#print axioms PureSFormal.StrongMultiwayUniversality.strongFairMacroSequenceEventuallyLabels
#print axioms PureSFormal.StrongMultiwayUniversality.strongFiniteFairnessObligationsExtendible
#print axioms PureSFormal.StrongMultiwayUniversality.strongInvalidCandidateAcceptanceReachable
#print axioms PureSFormal.StrongMultiwayUniversality.strongConeWideCandidateObserverSoundIffRefinesVerifier
#print axioms PureSFormal.StrongMultiwayUniversality.strongConeWideCandidateObserverSoundAndCompleteIffAgreesWithVerifier
#print axioms PureSFormal.StrongMultiwayUniversality.strongTerminalObservationIff
#print axioms PureSFormal.StrongMultiwayUniversality.strongBoundedTerminalCandidateIff
#print axioms PureSFormal.StrongMultiwayUniversality.strongStateMergedConfigurationQuotient
#print axioms PureSFormal.StrongMultiwayUniversality.strongExecutableScheduleNonvacuity
#print axioms PureSFormal.StrongMultiwayUniversality.strongExecutableEdgeCertificate
#print axioms PureSFormal.StrongMultiwayUniversality.strongOneStepEnumerationExact
#print axioms PureSFormal.StrongMultiwayUniversality.strongFiniteReductionEnumerationExact
#print axioms PureSFormal.StrongMultiwayUniversality.strongTerminalObservationSemidecidable
#print axioms PureSFormal.StrongMultiwayUniversality.strongDeterministicTapeHaltingIff
#print axioms PureSFormal.StrongMultiwayUniversality.strongDeterministicTapeHaltingReduction
#print axioms PureSFormal.StrongMultiwayUniversality.strongDeterministicTapeHaltingManyOne
#print axioms PureSFormal.StrongMultiwayUniversality.strongDeterministicTapeHaltingTermReduction
#print axioms PureSFormal.StrongMultiwayUniversality.strongDeterministicTapeHaltingTermManyOne
#print axioms PureSFormal.StrongMultiwayUniversality.strongDeterministicTapeAcceptanceSemidecidable
#print axioms PureSFormal.StrongMultiwayUniversality.strongFiniteBranchBinaryFirstReturn

#print axioms PureSFormal.Research.ProtectedTrieStrongCompleteness.mem_oneStepResults_iff
#print axioms PureSFormal.Research.ProtectedTrieStrongCompleteness.steps_mem_some_reductionLayer
#print axioms PureSFormal.Research.ProtectedTrieStrongCompleteness.eventuallyTerminalObserved_semidecidable
#print axioms PureSFormal.Research.ProtectedTrieDeterministicCompiler.compile_step_slot0
#print axioms PureSFormal.Research.ProtectedTrieDeterministicCompiler.compile_step_slot1
#print axioms PureSFormal.Research.ProtectedTrieDeterministicCompiler.compile_terminal_iff
#print axioms PureSFormal.Research.ProtectedTrieDeterministicCompiler.halts_iff_targetTerminalObservation
#print axioms PureSFormal.Research.ProtectedTrieDeterministicCompiler.deterministicHalting_reducesVia_targetTerminalObservation
#print axioms PureSFormal.Research.ProtectedTrieDeterministicCompiler.deterministicHalting_manyOne_targetTerminalObservation
#print axioms PureSFormal.Research.ProtectedTrieDeterministicCompiler.deterministicHalting_reducesVia_eventuallyTerminalObserved
#print axioms PureSFormal.Research.ProtectedTrieDeterministicCompiler.deterministicHalting_manyOne_eventuallyTerminalObserved
#print axioms PureSFormal.Research.ProtectedTrieDeterministicCompiler.compiledAcceptance_semidecidable
#print axioms PureSFormal.Research.FiniteBranchBinaryCompiler.occurrenceCode_injective
#print axioms PureSFormal.Research.FiniteBranchBinaryMachineCompiler.run?_compiled_occurrenceCode
#print axioms PureSFormal.Research.FiniteBranchBinaryMachineCompiler.compiled_occurrence_reflected
#print axioms PureSFormal.Research.FiniteBranchBinaryMachineCompiler.run?_compiled_history
#print axioms PureSFormal.Research.FiniteBranchBinaryMachineCompiler.finiteTerminal_iff_compiledTerminal_total
#print axioms PureSFormal.Research.FiniteBranchBinaryMachineCompiler.compiled_equal_rules_preserve_multiplicity
#print axioms PureSFormal.Research.FiniteBranchBinaryMachineCompiler.finiteBranchBinaryMachineFirstReturn

#print axioms PureSFormal.Research.ProtectedTrieMachineAgreement.step?_eq_some_iff_textbookStep
#print axioms PureSFormal.Research.ProtectedTrieMachineAgreement.selectsCell_iff_symbolCell
#print axioms PureSFormal.Research.ProtectedTrieMachineAgreement.selectsOccurrence_iff_occurrence
#print axioms PureSFormal.Research.ProtectedTrieMachineAgreement.selectsRule_iff_ruleAt?
#print axioms PureSFormal.Research.ProtectedTrieTableau.verify_sound
#print axioms PureSFormal.Research.ProtectedTrieTableau.verify_complete
#print axioms PureSFormal.Research.ProtectedTrieTableau.verify_witness_unique
#print axioms PureSFormal.Research.ProtectedTrieStrong.strongProjection_step_genuine_batch
#print axioms PureSFormal.Research.ProtectedTrieStrong.strongCheckpoint_exact
#print axioms PureSFormal.Research.ProtectedTrieStrong.strong_cofinal_complete
#print axioms PureSFormal.Research.ProtectedTrieFairness.fair_path_eventually_strongProjection
#print axioms PureSFormal.Research.ProtectedTrieFairness.fair_path_eventually_labelledProjection
#print axioms PureSFormal.Research.ProtectedTrieFairness.fairMacroTerm_steps
#print axioms PureSFormal.Research.ProtectedTrieFairness.fairMacroTerm_structurallyFair
#print axioms PureSFormal.Research.ProtectedTrieFairness.fairMacroTerm_eventually_labelled
#print axioms PureSFormal.Research.ProtectedTrieFairness.finite_fairness_obligations_extendible

#print axioms PureSFormal.Research.ProtectedTrieExecutableSchedule.insertPathSchedule_of_frontier
#print axioms PureSFormal.Research.ProtectedTrieExecutableSchedule.subdivisionEventSchedule_eq_openingSchedule
#print axioms PureSFormal.Research.ProtectedTrieExecutableSchedule.replayWithTrace_subdivisionEventSchedule
#print axioms PureSFormal.Research.ProtectedTrieExecutableSchedule.subdivisionEdgeSchedule_executable_certificate
#print axioms PureSFormal.Research.ProtectedTrieExecutableScheduleStrong.strongSourceEdgeSchedule_replay
#print axioms PureSFormal.Research.ProtectedTrieExecutableScheduleStrong.strongSourceEdgeSchedule_executable_certificate
#print axioms PureSFormal.Research.ProtectedTrieExecutableScheduleStrong.strongFiniteBranchSchedule_replay
#print axioms PureSFormal.Research.ProtectedTrieExecutableScheduleStrong.strongExecutableNonvacuity

#print axioms PureSFormal.Research.ProtectedTrieStrongTheorem.strongWholeMultiwayUniversality
#print axioms PureSFormal.Research.ProtectedTrieStrongTheorem.strongProjection_contains_valid_on_cone
#print axioms PureSFormal.Research.ProtectedTrieStrongTheorem.sourceValidity_iff
#print axioms PureSFormal.Research.ProtectedTrieStrongTheorem.strongFiniteBranchWalk
#print axioms PureSFormal.Research.ProtectedTrieStrongTheorem.strongInfiniteBranchStep
#print axioms PureSFormal.Research.ProtectedTrieStrongTheorem.strong_subdivisionCheckpoint_reachable
#print axioms PureSFormal.Research.ProtectedTrieStrongTheorem.strong_subdivisionCheckpoint_exact
#print axioms PureSFormal.Research.ProtectedTrieStrongTheorem.strongSourceEdgeSimplePath_nonempty
#print axioms PureSFormal.Research.ProtectedTrieStrongTheorem.strong_simple_directed_subdivision
#print axioms PureSFormal.Research.ProtectedTrieStrongTheorem.strong_frontier_exact_opening

#print axioms PureSFormal.Research.ProtectedTrieSubdivision.protectedTrieFiniteBranchWalk
#print axioms PureSFormal.Research.ProtectedTrieSubdivision.protectedTrie_simple_directed_subdivision
#print axioms PureSFormal.Research.ProtectedTrieSubdivision.subdivisionSimpleEdgePath_nonempty

#print axioms PureSFormal.Research.ProtectedTrieWholeObserverExactCost.strongEncoder_resource_certificate
#print axioms PureSFormal.Research.ProtectedTrieWholeObserverExactCost.runWholeLabelledObserver_labels
#print axioms PureSFormal.Research.ProtectedTrieWholeObserverExactCost.runWholeLabelledObserver_historyIdeal
#print axioms PureSFormal.Research.ProtectedTrieWholeObserverExactCost.runWholeLabelledObserver_outputCells_le
#print axioms PureSFormal.Research.ProtectedTrieWholeObserverExactCost.runWholeLabelledObserver_ticks_le
#print axioms PureSFormal.Research.ProtectedTrieWholeObserverExactCost.runWholeLabelledObserver_peak_le
#print axioms PureSFormal.Research.ProtectedTrieWholeObserverExactCost.wholeObserver_resource_certificate

#print axioms PureSFormal.Research.ProtectedTrieTableauExactResource.runLocalVerifier_resourceCertificate
#print axioms PureSFormal.Research.ProtectedTrieLabelledObserver.labelledProjection_literal_final_on_cone
#print axioms PureSFormal.Research.ProtectedTrieLabelledObserver.labelledProjection_slot_and_terminal_on_cone
#print axioms PureSFormal.Research.ProtectedTrieLabelledObserver.labelledProjection_history_unique
#print axioms PureSFormal.Research.ProtectedTrieLabelSemantics.strongProjection_contains_iff_labelled_extension
#print axioms PureSFormal.Research.ProtectedTrieLabelSemantics.labelledProjection_checkpoint_contains_prefix
#print axioms PureSFormal.Research.ProtectedTrieLabelSemantics.labelledProjection_finalRow_eq_sourceRun
#print axioms PureSFormal.Research.ProtectedTrieLabelSemantics.sourceBranchHalts_iff_targetTerminalObservation
#print axioms PureSFormal.Research.ProtectedTrieLabelSemantics.rootCheckpoint_reachable_exact
#print axioms PureSFormal.Research.ProtectedTrieLabelSemantics.valid_append_singleton_iff_step?_isSome
#print axioms PureSFormal.Research.ProtectedTrieConfigurationQuotient.configurationProjection_step_genuine_batch
#print axioms PureSFormal.Research.ProtectedTrieConfigurationQuotient.configurationProjection_checkpoint_iff
#print axioms PureSFormal.Research.ProtectedTrieConfigurationQuotient.historyConfigurationMap_surjective
#print axioms PureSFormal.Research.ProtectedTrieConfigurationQuotient.historyConfigurationMap_eq_iff_sourceFinalRow?
#print axioms PureSFormal.Research.ProtectedTrieConfigurationQuotient.valid_extension_maps_to_configuration_edge
#print axioms PureSFormal.Research.ProtectedTrieConfigurationQuotient.configurationOccurrenceEdge_lifts
#print axioms PureSFormal.Research.ProtectedTrieConfigurationQuotient.equal_successor_slots_merge_vertices_preserve_edges
#print axioms PureSFormal.Research.ProtectedTrieConfigurationQuotient.equalSuccessorFixture_finalRow_zero
#print axioms PureSFormal.Research.ProtectedTrieConfigurationQuotient.equalSuccessorFixture_finalRow_one
#print axioms PureSFormal.Research.ProtectedTrieConfigurationQuotient.equalSuccessorFixture_successor_terminal
#print axioms PureSFormal.Research.ProtectedTrieConfigurationQuotient.equalSuccessorFixture_terminalObservation
#print axioms PureSFormal.Research.ProtectedTrieConfigurationQuotient.equalSuccessorFixture_preserves_two_edges
#print axioms PureSFormal.Research.ProtectedTrieConfigurationQuotient.configurationQuotientCertificate
#print axioms PureSFormal.Research.ProtectedTrieConfluenceObstruction.no_exclusive_fork_decoder
#print axioms PureSFormal.Research.ProtectedTrieConfluenceObstruction.no_distinct_terminal_fork_decoder
#print axioms PureSFormal.Research.ProtectedTrieObserverNecessity.invalidCandidateAcceptance_reachable
#print axioms PureSFormal.Research.ProtectedTrieObserverNecessity.coneWideLiteralSound_iff_pointwiseRefinesVerifier
#print axioms PureSFormal.Research.ProtectedTrieObserverNecessity.coneWideLiteralSound_and_complete_iff_pointwiseAgreesWithVerifier
#print axioms PureSFormal.StrongMultiwayUniversality.strongCurrentTermObserverCandidateIff
#print axioms PureSFormal.StrongMultiwayUniversality.strongVerifiedCandidateReducesViaCurrentTermObserver
#print axioms PureSFormal.StrongMultiwayUniversality.strongVerifiedCandidateManyOneCurrentTermObserver
#print axioms PureSFormal.StrongMultiwayUniversality.strongInitialSourceStepReducesViaCurrentTermObserver
#print axioms PureSFormal.StrongMultiwayUniversality.strongInitialSourceStepManyOneCurrentTermObserver
#print axioms PureSFormal.StrongMultiwayUniversality.strongEncoderConeCurrentSource
#print axioms PureSFormal.StrongMultiwayUniversality.strongEncoderConesSourceSeparated
#print axioms PureSFormal.StrongMultiwayUniversality.strongNoFixedDepthCompleteProvenanceObserver
#print axioms PureSFormal.StrongMultiwayUniversality.strongLabelledLiteralObserverNotPrefixLocal
