import PureSFormal.WeakPathUniversalityExclusion
import PureSFormal.WeakPathPolynomialCost
import PureSFormal.PureS.ControllerStateCount
import PureSFormal.Research.RootResetBoundedDepthObstruction

/-!
# Result-A selected-path public theorem axiom inventory

The output of these commands is parsed by the release audit.  The only
permitted logical basis is the empty set or `propext` alone.
-/

#print axioms PureSFormal.WeakPathUniversality.finiteCTSUniformCertificate
#print axioms PureSFormal.WeakPathUniversality.finiteCTSWeakPathUniversality
#print axioms PureSFormal.WeakPathUniversality.fixedCookWeakPathUniversality
#print axioms PureSFormal.WeakPathUniversality.finiteCTSNextContractionMicroticks_le_linear
#print axioms PureSFormal.WeakPathUniversality.finiteCTSCheckpointTime_le_explicit_cubic
#print axioms PureSFormal.WeakPathUniversality.finiteCTSCheckpointTerm_size_le_explicit
#print axioms PureSFormal.WeakPathPolynomialCost.checkpointTime_le_of_horizon_le_polynomial
#print axioms PureSFormal.WeakPathPolynomialCost.checkpointTime_le_of_horizon_le_quadratic_log
#print axioms PureSFormal.WeakPathPolynomialCost.checkpointTime_le_of_horizon_le_cubic
#print axioms PureSFormal.WeakPathPolynomialCost.checkpointTime_le_of_horizon_le_cubic_log
#print axioms PureSFormal.WeakPathPolynomialCost.checkpointTime_le_of_horizon_le_quartic
#print axioms PureSFormal.Research.RootResetBoundedDepthObstruction.no_fixed_depth_sound_complete_selector
#print axioms PureSFormal.WeakPathUniversality.fixedRogozhinPassDecoder
#print axioms PureSFormal.WeakPathUniversality.fixedRogozhinBareTermDecoder
#print axioms PureSFormal.WeakPathUniversality.fixedRogozhinBareTermDecoder_eq
#print axioms PureSFormal.WeakPathUniversality.fixedRogozhinBareTermDecoder_of_decode

-- Exact global `Pass_R` / `Dec_R` classification and rejection.
#print axioms PureSFormal.WeakPathUniversality.fixedRogozhinPassDecoder_some_iff_fixedRegisteredBoundary
#print axioms PureSFormal.WeakPathUniversality.fixedRogozhinPassDecoder_none_iff_no_fixedRegisteredBoundary
#print axioms PureSFormal.WeakPathUniversality.fixedRegisteredBoundary_machineSteps_unique
#print axioms PureSFormal.WeakPathUniversality.fixedRogozhinBareTermDecoder_run_some_iff_fixedRegisteredBoundary
#print axioms PureSFormal.WeakPathUniversality.fixedRogozhinBareTermDecoder_run_none_iff_no_fixedRegisteredBoundary
#print axioms PureSFormal.WeakPathUniversality.fixedPureSMarkedSnapshotJobEncoder
#print axioms PureSFormal.WeakPathUniversality.fixedPureSMarkedSnapshotTapeEncoder
#print axioms PureSFormal.WeakPathUniversality.deterministicTapeHalts_iff_fixedPureSMarkedSnapshotTermEvent
#print axioms PureSFormal.WeakPathUniversality.fixedPureSMarkedSnapshotTapeEncoder_reducesVia
#print axioms PureSFormal.WeakPathUniversality.deterministicTapeHalts_manyOne_fixedPureSMarkedSnapshotTermEvent
#print axioms PureSFormal.WeakPathUniversality.universalAccepts_iff_fixedPureSMarkedSnapshotTermEvent
#print axioms PureSFormal.WeakPathUniversality.fixedPureSMarkedSnapshotJobEncoder_reducesVia
#print axioms PureSFormal.WeakPathUniversality.counterProgram_accepts_iff_fixedPureSMarkedSnapshotTermEvent
#print axioms PureSFormal.WeakPathUniversality.fixedPureSMarkedSnapshotFormulaEncoder
#print axioms PureSFormal.WeakPathUniversality.encodedBoundedWitnessFormula_iff_fixedPureSMarkedSnapshotTermEvent
#print axioms PureSFormal.WeakPathUniversality.fixedPureSMarkedSnapshotFormulaEncoder_reducesVia
#print axioms PureSFormal.WeakPathUniversality.fixedPureSMarkedSnapshotTermEvent_counterMachineHardViaNamedEncoder
#print axioms PureSFormal.WeakPathUniversality.fixedPureSMarkedSnapshotTermEvent_encodedBoundedWitnessHardViaNamedEncoder
#print axioms PureSFormal.WeakPathUniversality.fixedPureSMarkedSnapshotTermEvent_exponentialCounterBoundedRunComplete
#print axioms PureSFormal.WeakPathUniversality.fixedPureSMarkedSnapshotTermEvent_directInputCounterComplete
#print axioms PureSFormal.WeakPathUniversality.FixedPureSMarkedSnapshotTermEvent

-- The same target as a literal language on the displayed natural term codes.
#print axioms PureSFormal.WeakPathUniversality.FixedPureSMarkedSnapshotNatLanguage
#print axioms PureSFormal.WeakPathUniversality.fixedPureSMarkedSnapshotJobCodeEncoder
#print axioms PureSFormal.WeakPathUniversality.universalAccepts_iff_fixedPureSMarkedSnapshotNatLanguage
#print axioms PureSFormal.WeakPathUniversality.fixedPureSMarkedSnapshotJobCodeEncoder_reducesVia
#print axioms PureSFormal.WeakPathUniversality.fixedPureSMarkedSnapshotFormulaCodeEncoder
#print axioms PureSFormal.WeakPathUniversality.encodedBoundedWitnessFormula_iff_fixedPureSMarkedSnapshotNatLanguage
#print axioms PureSFormal.WeakPathUniversality.fixedPureSMarkedSnapshotFormulaCodeEncoder_reducesVia
#print axioms PureSFormal.WeakPathUniversality.fixedPureSMarkedSnapshotNatLanguage_exponentialCounterBoundedRunComplete
#print axioms PureSFormal.WeakPathUniversality.fixedPureSMarkedSnapshotNatLanguage_directInputCounterComplete

-- Canonical duplicate-free controller cover and raw-cover accounting.
#print axioms PureSFormal.PureS.SchedulerControl.canonicalControlStates_nodup
#print axioms PureSFormal.PureS.SchedulerControl.control_mem_canonicalStates
#print axioms PureSFormal.PureS.SchedulerControl.machine_states_nodup
#print axioms PureSFormal.PureS.SchedulerControl.machine_states_length
#print axioms PureSFormal.PureS.SchedulerControl.cook_runtimeCoverEntryCount

-- The fixed endpoint rejects every post-halt directional pass boundary.
#print axioms PureSFormal.Cook.PassClassification.haltCleanup_run_containsIndexed
#print axioms PureSFormal.Cook.PassClassification.haltCleanup_run_notArrivalReadable
