import Std

/-!
# Pure-S syntax and occurrences

`Term` is the ordinary unshared binary syntax tree generated by the single
leaf `S` and application.  There is deliberately no variable constructor, so
every inhabitant is a closed pure-S term by construction.

Addresses are root-relative lists of left/right directions.  They are a
specification device used to state occurrence-level results; the eventual
evaluator will use a single movable cursor rather than retaining an address
in its finite control.
-/

namespace PureSFormal.PureS

/-- A closed pure-S term.  Application associates to the left by convention. -/
inductive Term where
  | s : Term
  | app (fn arg : Term) : Term
  deriving BEq, DecidableEq, Inhabited, Repr

namespace Term

/-- Number of syntax-tree nodes, counting both `S` leaves and applications. -/
@[simp]
def size : Term → Nat
  | .s => 1
  | .app fn arg => Nat.succ (size fn + size arg)

theorem size_pos (t : Term) : 0 < t.size := by
  cases t <;> exact Nat.zero_lt_succ _

/-- The left-spine head.  For pure-S syntax it is necessarily `S`. -/
@[simp]
def head : Term → Term
  | .s => .s
  | .app fn _ => head fn

@[simp]
theorem head_eq_s (t : Term) : t.head = .s := by
  induction t with
  | s => rfl
  | app fn arg ih => exact ih

/-- Number of arguments on the applicative head spine. -/
@[simp]
def headArity : Term → Nat
  | .s => 0
  | .app fn _ => Nat.succ fn.headArity

/-- Arguments on the head spine, in their left-to-right application order. -/
@[simp]
def spineArgs : Term → List Term
  | .s => []
  | .app fn arg => fn.spineArgs ++ [arg]

/-- Apply a list of arguments from left to right. -/
@[simp]
def applyArgs : Term → List Term → Term
  | fn, [] => fn
  | fn, arg :: args => applyArgs (.app fn arg) args

theorem applyArgs_append (fn : Term) (xs ys : List Term) :
    applyArgs fn (xs ++ ys) = applyArgs (applyArgs fn xs) ys := by
  induction xs generalizing fn with
  | nil => rfl
  | cons x xs ih =>
      simp only [List.cons_append, applyArgs]
      exact ih (.app fn x)

theorem applyArgs_spineArgs (t : Term) : applyArgs .s t.spineArgs = t := by
  induction t with
  | s => rfl
  | app fn arg ih =>
      simp only [spineArgs, applyArgs_append, ih, applyArgs]

theorem headArity_eq_spineArgs_length (t : Term) :
    t.headArity = t.spineArgs.length := by
  induction t with
  | s => rfl
  | app fn arg ih =>
      simp only [headArity, spineArgs, List.length_append, List.length_cons,
        List.length_nil, Nat.add_zero, ih]

end Term

/-- One edge of an occurrence address. -/
inductive Direction where
  | left
  | right
  deriving BEq, DecidableEq, Inhabited, Repr

/-- A root-relative occurrence address. -/
abbrev Address := List Direction

namespace Term

/-- Look up the subtree at an occurrence address. -/
def subterm? (term : Term) : Address → Option Term
  | [] => some term
  | .left :: rest =>
      match term with
      | .app fn _ => subterm? fn rest
      | .s => none
  | .right :: rest =>
      match term with
      | .app _ arg => subterm? arg rest
      | .s => none

/-- Replace exactly the occurrence at `address`, failing when it is absent. -/
def replace? (term : Term) : Address → Term → Option Term
  | [], replacement => some replacement
  | .left :: rest, replacement =>
      match term with
      | .app fn arg => do
          let fn' ← replace? fn rest replacement
          pure (.app fn' arg)
      | .s => none
  | .right :: rest, replacement =>
      match term with
      | .app fn arg => do
          let arg' ← replace? arg rest replacement
          pure (.app fn arg')
      | .s => none

@[simp]
theorem subterm?_root (t : Term) : t.subterm? [] = some t := by
  cases t <;> rfl

@[simp]
theorem replace?_root (t replacement : Term) :
    t.replace? [] replacement = some replacement := by
  cases t <;> rfl

end Term

/-- A one-hole application context. -/
inductive Context where
  | hole
  | appLeft (ctx : Context) (right : Term)
  | appRight (left : Term) (ctx : Context)
  deriving BEq, DecidableEq, Inhabited, Repr

namespace Context

/-- Fill the unique hole of a context. -/
@[simp]
def plug : Context → Term → Term
  | .hole, term => term
  | .appLeft ctx right, term => .app (ctx.plug term) right
  | .appRight left ctx, term => .app left (ctx.plug term)

/-- Context composition, with `inner` placed in the hole of `outer`. -/
def comp : Context → Context → Context
  | .hole, inner => inner
  | .appLeft ctx right, inner => .appLeft (ctx.comp inner) right
  | .appRight left ctx, inner => .appRight left (ctx.comp inner)

@[simp]
theorem plug_comp (outer inner : Context) (term : Term) :
    (outer.comp inner).plug term = outer.plug (inner.plug term) := by
  induction outer with
  | hole => rfl
  | appLeft ctx right ih =>
      simp only [comp, plug, ih]
  | appRight left ctx ih =>
      simp only [comp, plug, ih]

end Context

namespace Term

/--
A successful lookup exposes an ordinary one-hole context.  Replacing the
looked-up occurrence by any term fills that same context.
-/
theorem context_of_subterm
    {term found : Term} {address : Address}
    (h : term.subterm? address = some found) :
    ∃ ctx : Context,
      ctx.plug found = term ∧
      ∀ replacement, term.replace? address replacement = some (ctx.plug replacement) := by
  induction address generalizing term with
  | nil =>
      simp only [subterm?] at h
      cases h
      refine ⟨.hole, rfl, ?_⟩
      intro replacement
      cases found <;> rfl
  | cons direction rest ih =>
      cases term with
      | s =>
          cases direction <;> simp [subterm?] at h
      | app fn arg =>
          cases direction with
          | left =>
              have hfn : fn.subterm? rest = some found := by
                simpa only [subterm?] using h
              obtain ⟨ctx, hplug, hreplace⟩ := ih hfn
              refine ⟨.appLeft ctx arg, ?_, ?_⟩
              · simp only [Context.plug, hplug]
              · intro replacement
                change (do
                  let fn' ← fn.replace? rest replacement
                  pure (Term.app fn' arg)) =
                    some (Term.app (ctx.plug replacement) arg)
                rw [show fn.replace? rest replacement = some (ctx.plug replacement) from
                  hreplace replacement]
                rfl
          | right =>
              have harg : arg.subterm? rest = some found := by
                simpa only [subterm?] using h
              obtain ⟨ctx, hplug, hreplace⟩ := ih harg
              refine ⟨.appRight fn ctx, ?_, ?_⟩
              · simp only [Context.plug, hplug]
              · intro replacement
                change (do
                  let arg' ← arg.replace? rest replacement
                  pure (Term.app fn arg')) =
                    some (Term.app fn (ctx.plug replacement))
                rw [show arg.replace? rest replacement = some (ctx.plug replacement) from
                  hreplace replacement]
                rfl

theorem replace?_self
    {term found : Term} {address : Address}
    (h : term.subterm? address = some found) :
    term.replace? address found = some term := by
  obtain ⟨ctx, hplug, hreplace⟩ := context_of_subterm h
  simpa only [hplug] using hreplace found

/-- Replacement is functional at a fixed term and address. -/
theorem replace?_deterministic
    {term replacement result₁ result₂ : Term} {address : Address}
    (h₁ : term.replace? address replacement = some result₁)
    (h₂ : term.replace? address replacement = some result₂) :
    result₁ = result₂ := by
  rw [h₁] at h₂
  exact Option.some.inj h₂

end Term

end PureSFormal.PureS
