import PureSFormal.Research.ProtectedTrieExecutableScheduleStrong
import PureSFormal.Research.ProtectedTrieExecutableScheduleFixture

/-!
# Source-level executable schedule axiom audit
-/

#print axioms PureSFormal.Research.ProtectedTrieExecutableSchedule.subdivisionEdgeSchedule_length_le
#print axioms PureSFormal.Research.ProtectedTrieExecutableSchedule.openingSchedule_length_le_seven
#print axioms PureSFormal.Research.ProtectedTrieExecutableSchedule.insertPathSchedule_length_le
#print axioms PureSFormal.Research.ProtectedTrieExecutableSchedule.insertPathsSchedule_length_le
#print axioms PureSFormal.Research.ProtectedTrieExecutableSchedule.subdivisionPreparationSchedule_trace_stutter
#print axioms PureSFormal.Research.ProtectedTrieSubdivision.subdivisionPreparationWalk_every_projection_stutter
#print axioms PureSFormal.Research.ProtectedTrieSubdivision.subdivisionEventWalk_before_target_projection_stutter
#print axioms PureSFormal.Research.ProtectedTrieSubdivision.subdivisionTargetFrontier
#print axioms PureSFormal.Research.ProtectedTrieSubdivision.subdivisionCheckpointGenerators_append_singleton
#print axioms PureSFormal.Research.ProtectedTrieExecutableSchedule.subdivisionEdgeSchedule_split_computable
#print axioms PureSFormal.Research.ProtectedTrieExecutableSchedule.insertPathSchedule_of_frontier
#print axioms PureSFormal.Research.ProtectedTrieExecutableSchedule.subdivisionEventSchedule_eq_openingSchedule
#print axioms PureSFormal.Research.ProtectedTrieExecutableSchedule.replay_subdivisionEventSchedule
#print axioms PureSFormal.Research.ProtectedTrieExecutableSchedule.replayWithTrace_subdivisionPreparationSchedule
#print axioms PureSFormal.Research.ProtectedTrieExecutableSchedule.replayWithTrace_subdivisionEventSchedule
#print axioms PureSFormal.Research.ProtectedTrieExecutableSchedule.subdivisionEdgeSchedule_exact_spec
#print axioms PureSFormal.Research.ProtectedTrieExecutableSchedule.subdivisionEdgeSchedule_executable_certificate
#print axioms PureSFormal.Research.ProtectedTrieExecutableSchedule.replay_finiteBranchSchedule
#print axioms PureSFormal.Research.ProtectedTrieExecutableScheduleStrong.strongSourceEdgeSchedule_replay
#print axioms PureSFormal.Research.ProtectedTrieExecutableScheduleStrong.strongSourceEdgeSchedule_nonempty
#print axioms PureSFormal.Research.ProtectedTrieExecutableScheduleStrong.strongSourceEdgeCheckpoints_distinct
#print axioms PureSFormal.Research.ProtectedTrieExecutableScheduleStrong.strongSourceEdgeSchedule_length_le
#print axioms PureSFormal.Research.ProtectedTrieExecutableScheduleStrong.strongSourceEdgeSchedule_executable_certificate
#print axioms PureSFormal.Research.ProtectedTrieExecutableScheduleStrong.strongFiniteBranchSchedule_replay
#print axioms PureSFormal.Research.ProtectedTrieExecutableScheduleStrong.infiniteValidBranch_checkpoints_pairwise_distinct
#print axioms PureSFormal.Research.ProtectedTrieExecutableScheduleStrong.strongExecutableNonvacuity
#print axioms PureSFormal.Research.ProtectedTrieExecutableScheduleFixture.equalSuccessorExecutableMultiplicity
