import PureSFormal.Research.ProtectedTrieCertificates

/-!
# Finite prefix sets for protected-trie certificates

This local Research module packages a finite list of bit words as the finite
prefix-closed set generated by those words.  It then specializes that
construction to complete certificate addresses and router addresses.

There is deliberately no machine model or tableau verifier here.  A chosen
certificate is an explicit pair `(history, payload)`.  The load-bearing
results say that its address is the only kind of complete candidate address
that can occur in the prefix closure of the chosen addresses, and that adding
router generators creates no additional complete candidate address.
-/

namespace PureSFormal.Research.ProtectedTrieFinitePrefix

open PureSFormal.Research.ProtectedTrieCertificates

/-! ## Constructive prefix algebra -/

/-- Prefixing is transitive. -/
theorem wordPrefix_trans {small middle large : BitWord}
    (hsm : WordPrefix small middle) (hml : WordPrefix middle large) :
    WordPrefix small large := by
  induction hsm generalizing large with
  | nil middle => exact .nil large
  | cons bit htail ih =>
      cases hml with
      | cons _ hlarge => exact .cons bit (ih hlarge)

/-- A finite prefix-closed set represented by its finite list of generators. -/
structure FinitePrefixSet where
  generators : List BitWord

namespace FinitePrefixSet

/-- Membership means being a prefix of one of the finite generators. -/
def Contains (set : FinitePrefixSet) (word : BitWord) : Prop :=
  ∃ endpoint, List.Mem endpoint set.generators ∧ WordPrefix word endpoint

/-- Every listed generator belongs to the prefix set it generates. -/
theorem contains_generator {set : FinitePrefixSet} {word : BitWord}
    (hmem : List.Mem word set.generators) : set.Contains word :=
  ⟨word, hmem, WordPrefix.refl word⟩

/-- The represented set is prefix-closed by construction. -/
theorem contains_prefix {set : FinitePrefixSet} {small large : BitWord}
    (hlarge : set.Contains large) (hprefix : WordPrefix small large) :
    set.Contains small := by
  obtain ⟨endpoint, hmem, hlargeEndpoint⟩ := hlarge
  exact ⟨endpoint, hmem, wordPrefix_trans hprefix hlargeEndpoint⟩

/-- The empty finite prefix set. -/
def empty : FinitePrefixSet :=
  ⟨[]⟩

/-- Adjoin all prefixes of one further generator. -/
def insertGenerator (word : BitWord) (set : FinitePrefixSet) : FinitePrefixSet :=
  ⟨word :: set.generators⟩

/-- Union of two finitely generated prefix sets. -/
def union (left right : FinitePrefixSet) : FinitePrefixSet :=
  ⟨left.generators ++ right.generators⟩

end FinitePrefixSet

/-! ## Small list lemmas with an empty kernel dependency basis -/

/-- Constructive left-to-right inclusion into an append. -/
theorem mem_append_left {word : BitWord} {left right : List BitWord}
    (hmem : List.Mem word left) : List.Mem word (left ++ right) := by
  induction hmem with
  | head => exact .head _
  | tail head htail ih => exact .tail head ih

/-- Constructive right-to-left inclusion into an append. -/
theorem mem_append_right {word : BitWord} (left : List BitWord)
    {right : List BitWord} (hmem : List.Mem word right) :
    List.Mem word (left ++ right) := by
  induction left with
  | nil => exact hmem
  | cons head left ih => exact .tail head ih

/-- Constructively classify membership in an append. -/
theorem mem_append_cases {word : BitWord} {left right : List BitWord}
    (hmem : List.Mem word (left ++ right)) :
    List.Mem word left ∨ List.Mem word right := by
  induction left with
  | nil => exact Or.inr hmem
  | cons head left ih =>
      cases hmem with
      | head => exact Or.inl (.head _)
      | tail _ htail =>
          cases ih htail with
          | inl hleft => exact Or.inl (.tail head hleft)
          | inr hright => exact Or.inr hright

/-! ## Explicit certificate and router generators -/

/-- Map explicit `(history,payload)` choices to complete candidate addresses. -/
def candidateGenerators : List (BitWord × BitWord) → List BitWord
  | [] => []
  | pair :: rest => a pair.1 pair.2 :: candidateGenerators rest

/-- Map explicit history choices to their open router addresses. -/
def routerGenerators : List BitWord → List BitWord
  | [] => []
  | history :: rest => router history :: routerGenerators rest

/-- A selected pair contributes its complete candidate generator. -/
theorem candidateGenerator_mem_of_mem {pair : BitWord × BitWord}
    {chosen : List (BitWord × BitWord)} (hmem : List.Mem pair chosen) :
    List.Mem (a pair.1 pair.2) (candidateGenerators chosen) := by
  induction hmem with
  | head => exact .head _
  | tail head htail ih => exact .tail (a head.1 head.2) ih

/-- Every complete candidate generator comes from an explicit selected pair. -/
theorem candidateGenerator_mem_cases {word : BitWord}
    {chosen : List (BitWord × BitWord)}
    (hmem : List.Mem word (candidateGenerators chosen)) :
    ∃ pair, List.Mem pair chosen ∧ a pair.1 pair.2 = word := by
  induction chosen with
  | nil => cases hmem
  | cons pair chosen ih =>
      cases hmem with
      | head => exact ⟨pair, .head _, rfl⟩
      | tail _ htail =>
          obtain ⟨found, hfound, heq⟩ := ih htail
          exact ⟨found, .tail pair hfound, heq⟩

/-- A selected history contributes its router generator. -/
theorem routerGenerator_mem_of_mem {history : BitWord}
    {routes : List BitWord} (hmem : List.Mem history routes) :
    List.Mem (router history) (routerGenerators routes) := by
  induction hmem with
  | head => exact .head _
  | tail head htail ih => exact .tail (router head) ih

/-- Every router generator comes from an explicit selected history. -/
theorem routerGenerator_mem_cases {word : BitWord} {routes : List BitWord}
    (hmem : List.Mem word (routerGenerators routes)) :
    ∃ history, List.Mem history routes ∧ router history = word := by
  induction routes with
  | nil => cases hmem
  | cons history routes ih =>
      cases hmem with
      | head => exact ⟨history, .head _, rfl⟩
      | tail _ htail =>
          obtain ⟨found, hfound, heq⟩ := ih htail
          exact ⟨found, .tail history hfound, heq⟩

/-! ## Certificate-only finite prefix closure -/

/-- Prefix closure generated by the explicitly chosen certificate endpoints. -/
def certificatePrefixSet
    (chosen : List (BitWord × BitWord)) : FinitePrefixSet :=
  ⟨candidateGenerators chosen⟩

/--
A complete candidate address occurs in the chosen-certificate prefix closure
exactly when its `(history,payload)` pair was selected.
-/
theorem a_contains_certificatePrefixSet_iff
    {history payload : BitWord} {chosen : List (BitWord × BitWord)} :
    (certificatePrefixSet chosen).Contains (a history payload) ↔
      List.Mem (history, payload) chosen := by
  constructor
  · intro hcontains
    obtain ⟨endpoint, hgenerator, hprefix⟩ := hcontains
    obtain ⟨pair, hchosen, heq⟩ := candidateGenerator_mem_cases hgenerator
    rcases pair with ⟨chosenHistory, chosenPayload⟩
    change a chosenHistory chosenPayload = endpoint at heq
    cases heq
    obtain ⟨hhistory, hpayload⟩ := a_prefix_eq hprefix
    cases hhistory
    cases hpayload
    exact hchosen
  · intro hchosen
    exact ⟨a history payload, candidateGenerator_mem_of_mem hchosen,
      WordPrefix.refl _⟩

/-- Chosen candidate pairs therefore remain injectively distinguishable. -/
theorem chosen_pair_eq_of_equal_address
    {left right : BitWord × BitWord}
    (heq : a left.1 left.2 = a right.1 right.2) : left = right :=
  a_injective heq

/-! ## Router-only and combined finite prefix closures -/

/-- Prefix closure generated by a finite list of router addresses. -/
def routerPrefixSet (routes : List BitWord) : FinitePrefixSet :=
  ⟨routerGenerators routes⟩

/-- Router prefix paths contain no complete candidate address. -/
theorem a_not_contains_routerPrefixSet
    (history payload : BitWord) (routes : List BitWord) :
    ¬ (routerPrefixSet routes).Contains (a history payload) := by
  intro hcontains
  obtain ⟨endpoint, hgenerator, hprefix⟩ := hcontains
  obtain ⟨routeHistory, hroute, heq⟩ := routerGenerator_mem_cases hgenerator
  change router routeHistory = endpoint at heq
  cases heq
  exact a_not_prefix_router history payload routeHistory hprefix

/--
The finite prefix set used by hierarchical checkpoints: selected complete
certificates together with a finite list of open routers.
-/
def protectedPrefixSet (chosen : List (BitWord × BitWord))
    (routes : List BitWord) : FinitePrefixSet :=
  ⟨candidateGenerators chosen ++ routerGenerators routes⟩

/-- Every selected certificate endpoint is present after routers are added. -/
theorem selected_a_contains_protectedPrefixSet
    {history payload : BitWord} {chosen : List (BitWord × BitWord)}
    (routes : List BitWord) (hchosen : List.Mem (history, payload) chosen) :
    (protectedPrefixSet chosen routes).Contains (a history payload) := by
  refine ⟨a history payload, ?_, WordPrefix.refl _⟩
  exact mem_append_left (candidateGenerator_mem_of_mem hchosen)

/--
Exact endpoint separation for the checkpoint prefix set: adding router paths
introduces no new complete candidate address.
-/
theorem a_contains_protectedPrefixSet_iff
    {history payload : BitWord} {chosen : List (BitWord × BitWord)}
    {routes : List BitWord} :
    (protectedPrefixSet chosen routes).Contains (a history payload) ↔
      List.Mem (history, payload) chosen := by
  constructor
  · intro hcontains
    obtain ⟨endpoint, hgenerator, hprefix⟩ := hcontains
    cases mem_append_cases hgenerator with
    | inl hcandidate =>
        obtain ⟨pair, hchosen, heq⟩ := candidateGenerator_mem_cases hcandidate
        rcases pair with ⟨chosenHistory, chosenPayload⟩
        change a chosenHistory chosenPayload = endpoint at heq
        cases heq
        obtain ⟨hhistory, hpayload⟩ := a_prefix_eq hprefix
        cases hhistory
        cases hpayload
        exact hchosen
    | inr hrouter =>
        obtain ⟨routeHistory, hroute, heq⟩ := routerGenerator_mem_cases hrouter
        change router routeHistory = endpoint at heq
        cases heq
        exact (a_not_prefix_router history payload routeHistory hprefix).elim
  · intro hchosen
    exact selected_a_contains_protectedPrefixSet routes hchosen

/-! ## Proper-prefix closures for prepared frontier certificates -/

/-- `small` is a strict (proper) prefix of `large`. -/
def ProperWordPrefix (small large : BitWord) : Prop :=
  WordPrefix small large /\ small ≠ large

/-- Prefixing is antisymmetric on finite literal words. -/
theorem wordPrefix_antisymm {left right : BitWord}
    (hlr : WordPrefix left right) (hrl : WordPrefix right left) :
    left = right := by
  induction hlr with
  | nil right =>
      cases right with
      | nil => rfl
      | cons bit right => exact (WordPrefix.not_cons_nil bit right hrl).elim
  | cons bit htail ih =>
      cases hrl with
      | cons _ hreverse =>
          exact congrArg (List.cons bit) (ih hreverse)

/-- Prefixing a proper prefix on the left remains proper. -/
theorem properWordPrefix_left_trans {small middle large : BitWord}
    (hsm : WordPrefix small middle) (hml : ProperWordPrefix middle large) :
    ProperWordPrefix small large := by
  refine ⟨wordPrefix_trans hsm hml.1, ?_⟩
  intro heq
  have hlargeMiddle : WordPrefix large middle := by
    rw [← heq]
    exact hsm
  exact hml.2 (wordPrefix_antisymm hml.1 hlargeMiddle)

/-- No word is a proper prefix of itself. -/
theorem not_properWordPrefix_refl (word : BitWord) :
    ¬ ProperWordPrefix word word := by
  intro h
  exact h.2 rfl

/-- Global candidate prefix-freeness rules out proper candidate-to-candidate prefixes. -/
theorem a_not_proper_prefix_a
    (leftHistory leftPayload rightHistory rightPayload : BitWord) :
    ¬ ProperWordPrefix (a leftHistory leftPayload)
      (a rightHistory rightPayload) := by
  intro hproper
  obtain ⟨hhistory, hpayload⟩ := a_prefix_eq hproper.1
  apply hproper.2
  cases hhistory
  cases hpayload
  rfl

/-- A finite set represented by the proper prefixes of listed generators. -/
structure FiniteProperPrefixSet where
  generators : List BitWord

namespace FiniteProperPrefixSet

/-- Membership means being a strict prefix of one listed endpoint. -/
def Contains (set : FiniteProperPrefixSet) (word : BitWord) : Prop :=
  ∃ endpoint, List.Mem endpoint set.generators ∧
    ProperWordPrefix word endpoint

/-- Proper-prefix sets remain prefix-closed. -/
theorem contains_prefix {set : FiniteProperPrefixSet} {small large : BitWord}
    (hlarge : set.Contains large) (hprefix : WordPrefix small large) :
    set.Contains small := by
  obtain ⟨endpoint, hmem, hproper⟩ := hlarge
  exact ⟨endpoint, hmem, properWordPrefix_left_trans hprefix hproper⟩

end FiniteProperPrefixSet

/-- Proper prefixes of a duplicate-tolerant finite list of candidate endpoints. -/
def candidateProperPrefixSet
    (frontier : List (BitWord × BitWord)) : FiniteProperPrefixSet :=
  ⟨candidateGenerators frontier⟩

/-- Explicit membership in the proper-prefix closure of candidate endpoints. -/
theorem contains_candidateProperPrefixSet_iff
    {word : BitWord} {frontier : List (BitWord × BitWord)} :
    (candidateProperPrefixSet frontier).Contains word ↔
      ∃ pair, List.Mem pair frontier ∧
        ProperWordPrefix word (a pair.1 pair.2) := by
  constructor
  · intro hcontains
    obtain ⟨endpoint, hgenerator, hproper⟩ := hcontains
    obtain ⟨pair, hfrontier, heq⟩ :=
      candidateGenerator_mem_cases hgenerator
    cases heq
    exact ⟨pair, hfrontier, hproper⟩
  · rintro ⟨pair, hfrontier, hproper⟩
    exact ⟨a pair.1 pair.2, candidateGenerator_mem_of_mem hfrontier, hproper⟩

/-- No complete candidate occurs in any finite candidate proper-prefix closure. -/
theorem a_not_contains_candidateProperPrefixSet
    (history payload : BitWord) (frontier : List (BitWord × BitWord)) :
    ¬ (candidateProperPrefixSet frontier).Contains (a history payload) := by
  intro hcontains
  obtain ⟨pair, hfrontier, hproper⟩ :=
    contains_candidateProperPrefixSet_iff.mp hcontains
  exact a_not_proper_prefix_a history payload pair.1 pair.2 hproper

/--
Membership in the finite prepared set used by canonical checkpoints: all
prefixes of selected full certificate endpoints, plus only proper prefixes of
frontier certificate endpoints.
-/
def PreparedContains (chosen frontier : List (BitWord × BitWord))
    (word : BitWord) : Prop :=
  (certificatePrefixSet chosen).Contains word \/
    (candidateProperPrefixSet frontier).Contains word

/-- The prepared finite union is prefix-closed. -/
theorem preparedContains_prefix {chosen frontier : List (BitWord × BitWord)}
    {small large : BitWord}
    (hlarge : PreparedContains chosen frontier large)
    (hprefix : WordPrefix small large) :
    PreparedContains chosen frontier small := by
  cases hlarge with
  | inl hselected =>
      exact Or.inl (FinitePrefixSet.contains_prefix hselected hprefix)
  | inr hfrontier =>
      exact Or.inr (FiniteProperPrefixSet.contains_prefix hfrontier hprefix)

/--
Exact complete-candidate membership in the selected/full plus
frontier/proper finite union. Duplicate selected or frontier entries are
harmless: only membership, never list uniqueness, is used.
-/
theorem a_preparedContains_iff
    {history payload : BitWord}
    {chosen frontier : List (BitWord × BitWord)} :
    PreparedContains chosen frontier (a history payload) ↔
      List.Mem (history, payload) chosen := by
  constructor
  · intro hcontains
    cases hcontains with
    | inl hselected =>
        exact a_contains_certificatePrefixSet_iff.mp hselected
    | inr hfrontier =>
        exact (a_not_contains_candidateProperPrefixSet
          history payload frontier hfrontier).elim
  · intro hchosen
    exact Or.inl (a_contains_certificatePrefixSet_iff.mpr hchosen)

end PureSFormal.Research.ProtectedTrieFinitePrefix
