import PureSFormal.Research.ProtectedTrieExecutableScheduleFixture

/-!
# Executable source-edge schedule axiom audit
-/

#print axioms PureSFormal.Research.ProtectedTrieExecutableSchedule.replay_positiveLocalSchedule
#print axioms PureSFormal.Research.ProtectedTrieSubdivision.branchIdeal_equivalent_iff
#print axioms PureSFormal.Research.ProtectedTrieSubdivision.projection_subdivisionCheckpoint_equivalent
#print axioms PureSFormal.Research.ProtectedTrieExecutableSchedule.replayWithTrace_openingSchedule
#print axioms PureSFormal.Research.ProtectedTrieExecutableSchedule.replay_insertPathSchedule
#print axioms PureSFormal.Research.ProtectedTrieExecutableSchedule.replay_insertPathsSchedule
#print axioms PureSFormal.Research.ProtectedTrieExecutableSchedule.replay_subdivisionEdgeSchedule
#print axioms PureSFormal.Research.ProtectedTrieExecutableSchedule.subdivisionEdgeSchedule_nonempty
#print axioms PureSFormal.Research.ProtectedTrieExecutableSchedule.subdivisionEdgeSchedule_exact_spec
#print axioms PureSFormal.Research.ProtectedTrieExecutableSchedule.replay_finiteBranchSchedule
#print axioms PureSFormal.Research.ProtectedTrieExecutableSchedule.finiteBranchSchedule_exact_projections
#print axioms PureSFormal.Research.ProtectedTrieExecutableScheduleFixture.equalSuccessorZeroSchedule_exact
#print axioms PureSFormal.Research.ProtectedTrieExecutableScheduleFixture.equalSuccessorOneSchedule_exact
#print axioms PureSFormal.Research.ProtectedTrieExecutableScheduleFixture.equalSuccessorExecutableMultiplicity
