import PureSFormal.Research.ProtectedTrieConfigurationQuotient

/-!
# Literal-label and configuration-quotient axiom audit
-/

#print axioms PureSFormal.Research.ProtectedTrieLabelSemantics.strongProjection_contains_iff_labelled_extension
#print axioms PureSFormal.Research.ProtectedTrieLabelSemantics.buildTrace?_lastRow?_eq_run?
#print axioms PureSFormal.Research.ProtectedTrieLabelSemantics.labelledProjection_checkpoint_contains_prefix
#print axioms PureSFormal.Research.ProtectedTrieLabelSemantics.labelledProjection_finalRow_eq_sourceRun
#print axioms PureSFormal.Research.ProtectedTrieLabelSemantics.sourceBranchHalts_iff_targetTerminalObservation
#print axioms PureSFormal.Research.ProtectedTrieLabelSemantics.rootCheckpoint_reachable_exact
#print axioms PureSFormal.Research.ProtectedTrieLabelSemantics.valid_append_singleton_iff_step?_isSome

#print axioms PureSFormal.Research.ProtectedTrieConfigurationQuotient.configurationProjection_step_mono
#print axioms PureSFormal.Research.ProtectedTrieConfigurationQuotient.configurationProjection_step_genuine_batch
#print axioms PureSFormal.Research.ProtectedTrieConfigurationQuotient.configurationProjection_checkpoint_iff
#print axioms PureSFormal.Research.ProtectedTrieConfigurationQuotient.rowReachable_iff
#print axioms PureSFormal.Research.ProtectedTrieConfigurationQuotient.historyConfigurationMap_surjective
#print axioms PureSFormal.Research.ProtectedTrieConfigurationQuotient.historyConfigurationMap_eq_iff_sourceFinalRow?
#print axioms PureSFormal.Research.ProtectedTrieConfigurationQuotient.valid_extension_maps_to_configuration_edge
#print axioms PureSFormal.Research.ProtectedTrieConfigurationQuotient.configurationOccurrenceEdge_lifts
#print axioms PureSFormal.Research.ProtectedTrieConfigurationQuotient.equal_successor_slots_merge_vertices_preserve_edges
#print axioms PureSFormal.Research.ProtectedTrieConfigurationQuotient.equalSuccessorFixture_finalRow_zero
#print axioms PureSFormal.Research.ProtectedTrieConfigurationQuotient.equalSuccessorFixture_finalRow_one
#print axioms PureSFormal.Research.ProtectedTrieConfigurationQuotient.equalSuccessorFixture_successor_terminal
#print axioms PureSFormal.Research.ProtectedTrieConfigurationQuotient.equalSuccessorFixture_terminalObservation
#print axioms PureSFormal.Research.ProtectedTrieConfigurationQuotient.equalSuccessorFixture_preserves_two_edges
#print axioms PureSFormal.Research.ProtectedTrieConfigurationQuotient.configurationQuotientCertificate
