import PureSFormal.Research.ProtectedTrieStrongTheorem
import PureSFormal.Research.FiniteBranchBinaryCompiler

/-!
# Kernel dependency audit for the protected whole-cone theorem

These commands are intentionally part of the source tree so a clean build
prints the kernel-reported axiom dependencies of the aggregate and its concrete
resource/subdivision components.
-/

namespace PureSFormal.Research.ProtectedTrieStrongTheoremAudit

#print axioms PureSFormal.Research.FiniteBranchBinaryCompiler.finiteRuleAt?_via_binary
#print axioms PureSFormal.Research.FiniteBranchBinaryCompiler.finiteStep?_via_binary
#print axioms PureSFormal.Research.FiniteBranchBinaryCompiler.decodeOccurrenceHistoryAux_replicate
#print axioms PureSFormal.Research.FiniteBranchBinaryCompiler.decodeOccurrenceHistory?_encodeOccurrenceHistory
#print axioms PureSFormal.Research.FiniteBranchBinaryCompiler.encodeOccurrenceHistory_injective
#print axioms PureSFormal.Research.FiniteBranchBinaryCompiler.finiteBranchBinaryFirstReturn
#print axioms PureSFormal.Research.ProtectedTrieStrong.sourceEnabled_eq_true_iff
#print axioms PureSFormal.PureS.Term.redex_sLeaves_le_contractum
#print axioms PureSFormal.PureS.Term.redex_sLeaves_lt_contractum_of_one_lt
#print axioms PureSFormal.PureS.Step.sLeaves_mono
#print axioms PureSFormal.PureS.Steps.sLeaves_mono
#print axioms PureSFormal.PureS.StepsN.sLeaves_mono
#print axioms PureSFormal.Research.ProtectedTrieSubdivisionMeasure.one_lt_C_sLeaves
#print axioms PureSFormal.Research.ProtectedTrieSubdivisionMeasure.positive_first_sLeaves_strict
#print axioms PureSFormal.Research.ProtectedTrieSubdivisionMeasure.zero_reset_sLeaves_mono
#print axioms PureSFormal.Research.ProtectedTrieSubdivisionMeasure.zero_positive_first_sLeaves_strict
#print axioms PureSFormal.Research.ProtectedTrieSubdivisionMeasure.positiveProper_ne_source

#print axioms PureSFormal.Research.ProtectedTrieStrongTheorem.strongWholeMultiwayUniversality
#print axioms PureSFormal.Research.ProtectedTrieStrongTheorem.strongProjection_contains_valid_on_cone
#print axioms PureSFormal.Research.ProtectedTrieStrongTheorem.strong_subdivisionCheckpoint_reachable
#print axioms PureSFormal.Research.ProtectedTrieStrongTheorem.strong_subdivisionCheckpoint_exact
#print axioms PureSFormal.Research.ProtectedTrieStrongTheorem.strongInfiniteBranchStep
#print axioms PureSFormal.Research.ProtectedTrieStrongTheorem.strongSourceEdgeSimplePath_nonempty
#print axioms PureSFormal.Research.ProtectedTrieStrongTheorem.strong_simple_directed_subdivision
#print axioms PureSFormal.Research.ProtectedTrieMachineAgreement.selectsCell_iff_symbolCell
#print axioms PureSFormal.Research.ProtectedTrieMachineAgreement.selectsOccurrence_iff_occurrence
#print axioms PureSFormal.Research.ProtectedTrieMachineAgreement.selectsRule_iff_ruleAt?
#print axioms PureSFormal.Research.ProtectedTrieMachineAgreement.step?_eq_some_iff_textbookStep
#print axioms PureSFormal.Research.ProtectedTrieSubdivision.protectedTrie_simple_directed_subdivision
#print axioms PureSFormal.Research.ProtectedTrieSubdivision.subdivisionSimpleEdgePath_nonempty
#print axioms PureSFormal.Research.ProtectedTrieWholeObserverExactCost.strongEncoder_resource_certificate
#print axioms PureSFormal.Research.ProtectedTrieWholeObserverExactCost.runWholeLabelledObserver_labels
#print axioms PureSFormal.Research.ProtectedTrieWholeObserverExactCost.runWholeLabelledObserver_historyIdeal
#print axioms PureSFormal.Research.ProtectedTrieWholeObserverExactCost.runWholeLabelledObserver_outputCells_le
#print axioms PureSFormal.Research.ProtectedTrieWholeObserverExactCost.runWholeLabelledObserver_ticks_le
#print axioms PureSFormal.Research.ProtectedTrieWholeObserverExactCost.runWholeLabelledObserver_peak_le
#print axioms PureSFormal.Research.ProtectedTrieWholeObserverExactCost.wholeObserver_exact_resource_certificate
#print axioms PureSFormal.Research.ProtectedTrieWholeObserverExactCost.wholeObserver_resource_certificate
#print axioms PureSFormal.Research.ProtectedTrieLabelledObserver.labelledProjection_history_unique
#print axioms PureSFormal.Research.ProtectedTrieWholeObserverExactCost.parseHeaderM?_value
#print axioms PureSFormal.Research.ProtectedTrieWholeObserverExactCost.decodeNM?_value
#print axioms PureSFormal.Research.ProtectedTrieWholeObserverExactCost.decodeInstanceM?_value
#print axioms PureSFormal.Research.ProtectedTrieWholeObserverExactCost.openedPathsM_value
#print axioms PureSFormal.Research.ProtectedTrieWholeObserverExactCost.collectLabelsM_value
#print axioms PureSFormal.Research.ProtectedTrieWholeObserverExactCost.encodeInstanceLinearM_value
#print axioms PureSFormal.Research.ProtectedTrieWholeObserverExactCost.encodeMachineOntoM_value
#print axioms PureSFormal.Research.ProtectedTrieWholeObserverExactCost.encodeStateDataOntoM_value
#print axioms PureSFormal.Research.ProtectedTrieWholeObserverExactCost.parseCandidateM?_value
#print axioms PureSFormal.Research.ProtectedTrieWholeObserverExactCost.runLocalLabelVerifier_value
#print axioms PureSFormal.Research.ProtectedTrieWholeObserverExactCost.decodeInstancePrefixM?_value
#print axioms PureSFormal.Research.ProtectedTrieWholeObserverExactCost.reverseM_value
#print axioms PureSFormal.Research.ProtectedTrieWholeObserverExactCost.parsePcAuxM_value
#print axioms PureSFormal.Research.ProtectedTrieWholeObserverExactCost.parseCandidateAuxM_value
#print axioms PureSFormal.Research.ProtectedTrieTableauExactCost.bitWordBEq_eq_true_iff
#print axioms PureSFormal.Research.ProtectedTrieWholeObserverExactCost.decodeMachineM?_value
#print axioms PureSFormal.Research.ProtectedTrieWholeObserverExactCost.decodeStateRowsNM?_value
#print axioms PureSFormal.Research.ProtectedTrieWholeObserverExactCost.decodeStateRowM?_value
#print axioms PureSFormal.Research.ProtectedTrieWholeObserverExactCost.decodeOrderedCellM?_value
#print axioms PureSFormal.Research.ProtectedTrieWholeObserverExactCost.decodeRuleOptionM?_value
#print axioms PureSFormal.Research.ProtectedTrieWholeObserverExactCost.decodeRuleM?_value
#print axioms PureSFormal.Research.ProtectedTrieTableauExactCost.natEqM_value
#print axioms PureSFormal.Research.ProtectedTrieTableauExactCost.lengthM_value

end PureSFormal.Research.ProtectedTrieStrongTheoremAudit
