import PureSFormal.Research.ProtectedTrieObserverBoundary

#print axioms PureSFormal.Research.ProtectedTrieObserverBoundary.verify_initial_two_rows_iff_step
#print axioms PureSFormal.Research.ProtectedTrieObserverBoundary.initialSourceStep_reducesVia_observer
#print axioms PureSFormal.Research.ProtectedTrieObserverBoundary.initialSourceStep_manyOneReduces_observer
#print axioms PureSFormal.Research.ProtectedTrieObserverBoundary.strongEncoder_cone_currentSource
#print axioms PureSFormal.Research.ProtectedTrieObserverBoundary.strongEncoder_cone_headerBits
#print axioms PureSFormal.Research.ProtectedTrieObserverBoundary.strongEncoder_cones_source_separated
#print axioms PureSFormal.Research.ProtectedTrieObserverBoundary.PrefixLocality.buildFrom_insertPath_divergence_agree
#print axioms PureSFormal.Research.ProtectedTrieObserverBoundary.PrefixLocality.deepCanonicalCandidateAdversary
#print axioms PureSFormal.Research.ProtectedTrieObserverBoundary.PrefixLocality.no_fixed_depth_complete_provenance_observer
#print axioms PureSFormal.Research.ProtectedTrieObserverBoundary.PrefixLocality.labelledLiteralObserver_canonicalComplete
#print axioms PureSFormal.Research.ProtectedTrieObserverBoundary.PrefixLocality.labelledLiteralObserver_coneWideProvenance
#print axioms PureSFormal.Research.ProtectedTrieObserverBoundary.PrefixLocality.labelledLiteralObserver_not_prefixLocal
