import PureSFormal.Research.ProtectedTrieConfluenceObstruction

#print axioms PureSFormal.Research.ProtectedTrieConfluenceObstruction.Confluent
#print axioms PureSFormal.Research.ProtectedTrieConfluenceObstruction.decoded_cone_directed_of_confluent
#print axioms PureSFormal.Research.ProtectedTrieConfluenceObstruction.no_exclusive_fork_decoder_of_confluent
#print axioms PureSFormal.Research.ProtectedTrieConfluenceObstruction.no_distinct_terminal_fork_decoder_of_confluent
#print axioms PureSFormal.Research.ProtectedTrieConfluenceObstruction.no_exclusive_fork_decoder
#print axioms PureSFormal.Research.ProtectedTrieConfluenceObstruction.no_distinct_terminal_fork_decoder
