import PureSFormal.Research.ProtectedTrieBoundedTerminal

/-! Public axiom inventory for the bounded literal-certificate bridge. -/

#print axioms PureSFormal.Research.ProtectedTrieBoundedTerminal.candidateAddress_length
#print axioms PureSFormal.Research.ProtectedTrieBoundedTerminal.replay_candidateSchedule
#print axioms PureSFormal.Research.ProtectedTrieBoundedTerminal.candidateAddress_mem_openedPaths
#print axioms PureSFormal.Research.ProtectedTrieBoundedTerminal.terminalCandidate?_eq_true_iff
#print axioms PureSFormal.Research.ProtectedTrieBoundedTerminal.runTerminalCandidate_value
#print axioms PureSFormal.Research.ProtectedTrieBoundedTerminal.runTerminalCandidate_ticks_le
#print axioms PureSFormal.Research.ProtectedTrieBoundedTerminal.runTerminalCandidate_peak_le
#print axioms PureSFormal.Research.ProtectedTrieBoundedTerminal.candidateSchedule_length_le
#print axioms PureSFormal.Research.ProtectedTrieBoundedTerminal.candidateSchedule_length_ge_address
#print axioms PureSFormal.Research.ProtectedTrieBoundedTerminal.candidateLiteral_length_le_schedule
#print axioms PureSFormal.Research.ProtectedTrieBoundedTerminal.protectedFieldAddress_length_le
#print axioms PureSFormal.Research.ProtectedTrieBoundedTerminal.mem_map_iff_literal
#print axioms PureSFormal.Research.ProtectedTrieBoundedTerminal.mem_append_iff_literal
#print axioms PureSFormal.Research.ProtectedTrieBoundedTerminal.mem_openingLocalSchedule_length_le
#print axioms PureSFormal.Research.ProtectedTrieBoundedTerminal.mem_openingSchedule_address_length_le
#print axioms PureSFormal.Research.ProtectedTrieBoundedTerminal.mem_insertPathSchedule_address_length_le
#print axioms PureSFormal.Research.ProtectedTrieBoundedTerminal.mem_candidateSchedule_address_length_le
#print axioms PureSFormal.Research.ProtectedTrieBoundedTerminal.candidateSchedule_addressCells_le
#print axioms PureSFormal.Research.ProtectedTrieBoundedTerminal.boundedTerminalCandidate_has_bounded_literals
#print axioms PureSFormal.Research.ProtectedTrieBoundedTerminal.terminalCandidate_reaches_label
#print axioms PureSFormal.Research.ProtectedTrieBoundedTerminal.boundedTerminalCandidate_sound
#print axioms PureSFormal.Research.ProtectedTrieBoundedTerminal.sourceBranchHalts_boundedTerminalCandidate
#print axioms PureSFormal.Research.ProtectedTrieBoundedTerminal.exists_boundedTerminalCandidate_iff
