import PureSFormal.Research.PureSContractionOccurrenceInjectivity

#print axioms PureSFormal.Research.PureSContractionOccurrenceInjectivity.right_ne_app
#print axioms PureSFormal.Research.PureSContractionOccurrenceInjectivity.context_plug_injective
#print axioms PureSFormal.Research.PureSContractionOccurrenceInjectivity.step_irreflexive
#print axioms PureSFormal.Research.PureSContractionOccurrenceInjectivity.contractAt_ne_self
#print axioms PureSFormal.Research.PureSContractionOccurrenceInjectivity.contractAt_root
#print axioms PureSFormal.Research.PureSContractionOccurrenceInjectivity.optionMap_some
#print axioms PureSFormal.Research.PureSContractionOccurrenceInjectivity.root_ne_descendant
#print axioms PureSFormal.Research.PureSContractionOccurrenceInjectivity.contractAt_address_injective
#print axioms PureSFormal.Research.PureSContractionOccurrenceInjectivity.rdx_at_cursor_address
#print axioms PureSFormal.Research.PureSContractionOccurrenceInjectivity.same_source_target_occurrence
