import PureSFormal.Research.RootResetNormalCarrierEmptyExclusion
#print axioms PureSFormal.Research.RootResetNormalCarrierEmptyExclusion.ordered_reads
#print axioms PureSFormal.Research.RootResetNormalCarrierEmptyExclusion.spine_deleted_of_positive
#print axioms PureSFormal.Research.RootResetNormalCarrierEmptyExclusion.carrier_deleted_of_positive
#print axioms PureSFormal.Research.RootResetNormalCarrierEmptyExclusion.selected_deleted
#print axioms PureSFormal.Research.RootResetNormalCarrierEmptyExclusion.selected_completed
#print axioms PureSFormal.Research.RootResetNormalCarrierEmptyExclusion.first_deleted
#print axioms PureSFormal.Research.RootResetNormalCarrierEmptyExclusion.ordered_negative
#print axioms PureSFormal.Research.RootResetNormalCarrierEmptyExclusion.positive_count_negative
#print axioms PureSFormal.Research.RootResetNormalCarrierEmptyExclusion.selected_deleted_runs
#print axioms PureSFormal.Research.RootResetNormalCarrierEmptyExclusion.selected_completed_runs
#print axioms PureSFormal.Research.RootResetNormalCarrierEmptyExclusion.first_completed_runs
