import PureSFormal.Research.RootResetTermOnlyUniversalityTransfer

#print axioms PureSFormal.Research.RootResetTermOnlyUniversalityTransfer.selector
#print axioms PureSFormal.Research.RootResetTermOnlyUniversalityTransfer.AgreesOnEverySample
#print axioms PureSFormal.Research.RootResetTermOnlyUniversalityTransfer.agreesOnEverySample_of_certifiedStages
#print axioms PureSFormal.Research.RootResetTermOnlyUniversalityTransfer.AgreesOnSampledGood
#print axioms PureSFormal.Research.RootResetTermOnlyUniversalityTransfer.AgreesOnSampledState
#print axioms PureSFormal.Research.RootResetTermOnlyUniversalityTransfer.AgreesForFamily
#print axioms PureSFormal.Research.RootResetTermOnlyUniversalityTransfer.SevenFamilyAgreement
#print axioms PureSFormal.Research.RootResetTermOnlyUniversalityTransfer.agreesOnSampledState_of_sevenFamilies
#print axioms PureSFormal.Research.RootResetTermOnlyUniversalityTransfer.agreesOnSampledGood_of_sampledState
#print axioms PureSFormal.Research.RootResetTermOnlyUniversalityTransfer.agreesOnEverySample_of_sampledGood
#print axioms PureSFormal.Research.RootResetTermOnlyUniversalityTransfer.finiteCTSTermOnlyUniversalityOfAgreement
#print axioms PureSFormal.Research.RootResetTermOnlyUniversalityTransfer.termOnlyPath_eq_persistentPath_of_agreement
