import PureSFormal.Research.RootResetCarrierBoundaryGrammar

#print axioms PureSFormal.Research.RootResetCarrierBoundaryGrammar.classify_isSome_of_holds
#print axioms PureSFormal.Research.RootResetCarrierBoundaryGrammar.classify_eq_base_iff
#print axioms PureSFormal.Research.RootResetCarrierBoundaryGrammar.classify_eq_local_iff
#print axioms PureSFormal.Research.RootResetCarrierBoundaryGrammar.classify_unique
#print axioms PureSFormal.Research.RootResetCarrierBoundaryGrammar.existsUnique_activeDecomposition
#print axioms PureSFormal.Research.RootResetCarrierBoundaryGrammar.activeDecomposition_source_eq
#print axioms PureSFormal.Research.RootResetCarrierBoundaryGrammar.activeDecomposition_subterm
#print axioms PureSFormal.Research.RootResetCarrierBoundaryGrammar.activeDecomposition_address_length_lt
#print axioms PureSFormal.Research.RootResetCarrierBoundaryGrammar.local_audits_opaque
#print axioms PureSFormal.Research.RootResetCarrierBoundaryGrammar.tombstone_audit_opaque
