import PureSFormal.Research.RootResetRegisteredMarkerOccurrence

#print axioms PureSFormal.Research.RootResetRegisteredMarkerOccurrence.fresh_pass_selects_cursor
#print axioms PureSFormal.Research.RootResetRegisteredMarkerOccurrence.fresh_pass_final_cursor
#print axioms PureSFormal.Research.RootResetRegisteredMarkerOccurrence.commit_follow
#print axioms PureSFormal.Research.RootResetRegisteredMarkerOccurrence.normal_start_cursor
#print axioms PureSFormal.Research.RootResetRegisteredMarkerOccurrence.empty_start_cursor
#print axioms PureSFormal.Research.RootResetRegisteredMarkerOccurrence.commit_rdx
#print axioms PureSFormal.Research.RootResetRegisteredMarkerOccurrence.contract_performs
#print axioms PureSFormal.Research.RootResetRegisteredMarkerOccurrence.contract_step
#print axioms PureSFormal.Research.RootResetRegisteredMarkerOccurrence.contract_mutation
#print axioms PureSFormal.Research.RootResetRegisteredMarkerOccurrence.normal_post_cursor
#print axioms PureSFormal.Research.RootResetRegisteredMarkerOccurrence.empty_post_cursor
#print axioms PureSFormal.Research.RootResetRegisteredMarkerOccurrence.empty_fresh_root_occurrence
#print axioms PureSFormal.Research.RootResetRegisteredMarkerOccurrence.normal_fresh_pass
#print axioms PureSFormal.Research.RootResetRegisteredMarkerOccurrence.normal_fresh_root_occurrence
