import PureSFormal.Research.RootResetDecodedCarrierNonemptyAgreement

#print axioms PureSFormal.Research.RootResetDecodedCarrierNonemptyAgreement.base_misses_tombstone_openBase
#print axioms PureSFormal.Research.RootResetDecodedCarrierNonemptyAgreement.base_misses_tombstone_decoded
#print axioms PureSFormal.Research.RootResetDecodedCarrierNonemptyAgreement.decoded_value
#print axioms PureSFormal.Research.RootResetDecodedCarrierNonemptyAgreement.fresh_admission_restores
#print axioms PureSFormal.Research.RootResetDecodedCarrierNonemptyAgreement.decoded_fresh_runs
