import PureSFormal.Research.RootResetEndpointGeneratedMisses
#print axioms PureSFormal.Research.RootResetEndpointGeneratedMisses.fresh_pattern_arity
#print axioms PureSFormal.Research.RootResetEndpointGeneratedMisses.dispatcher_entry_missed
#print axioms PureSFormal.Research.RootResetEndpointGeneratedMisses.action_entry_missed
#print axioms PureSFormal.Research.RootResetEndpointGeneratedMisses.generated_clock_growth
#print axioms PureSFormal.Research.RootResetEndpointGeneratedMisses.generated_clock_launch
#print axioms PureSFormal.Research.RootResetEndpointGeneratedMisses.dispatcher_route_rows_missed
#print axioms PureSFormal.Research.RootResetEndpointGeneratedMisses.dispatcher_local_rows_missed
#print axioms PureSFormal.Research.RootResetEndpointGeneratedMisses.generated_dispatcher_miss
#print axioms PureSFormal.Research.RootResetEndpointGeneratedMisses.generated_action_call
#print axioms PureSFormal.Research.RootResetEndpointGeneratedMisses.generated_appender
#print axioms PureSFormal.Research.RootResetLocalDispatcherProbe.generated_finish
