import PureSFormal.Research.RootResetAllInputsTraceAgreement

#print axioms PureSFormal.Research.RootResetAllInputsTraceAgreement.bitcons_rawStageAt
#print axioms PureSFormal.Research.RootResetAllInputsTraceAgreement.bitcons_certifiedPositiveStages
#print axioms PureSFormal.Research.RootResetAllInputsTraceAgreement.bitcons_selectsEveryContractionRun
#print axioms PureSFormal.Research.RootResetAllInputsTraceAgreement.selectsEveryContractionRun
#print axioms PureSFormal.Research.RootResetAllInputsTraceAgreement.agreesOnEverySample
#print axioms PureSFormal.Research.RootResetAllInputsTraceAgreement.finiteCTSTermOnlyUniversality
#print axioms PureSFormal.Research.RootResetAllInputsTraceAgreement.transferred_path_eq
#print axioms PureSFormal.Research.RootResetAllInputsTraceAgreement.termOnlyPath_eq_persistentPath
