import PureSFormal.Research.RootResetWrappedAppenderSelectorChain

#print axioms PureSFormal.Research.RootResetWrappedAppenderSelectorChain.earlyPriorities_none
#print axioms PureSFormal.Research.RootResetWrappedAppenderSelectorChain.selectedAction_selects_firstPush_marked_pending
#print axioms PureSFormal.Research.RootResetWrappedAppenderSelectorChain.selectedActionSelection?_validRow_marked_pending_none
#print axioms PureSFormal.Research.RootResetWrappedAppenderSelectorChain.nonfinalRow_selectStep?_marked_pending
#print axioms PureSFormal.Research.RootResetWrappedAppenderSelectorChain.actionTail_appenderChain
#print axioms PureSFormal.Research.RootResetWrappedAppenderSelectorChain.actionEntries_appenderChain
#print axioms PureSFormal.Research.RootResetWrappedAppenderSelectorChain.AppenderEdge.selectStep?_marked_pending
#print axioms PureSFormal.Research.RootResetWrappedAppenderSelectorChain.AppenderChain.selections_marked_pending
#print axioms PureSFormal.Research.RootResetWrappedAppenderSelectorChain.AppenderChain.selectsSamples_marked_pending
