import PureSFormal.Research.RootResetProgressEulerTotality

#print axioms PureSFormal.Research.RootResetProgressEulerTotality.PrefixResult.source_eq
#print axioms PureSFormal.Research.RootResetProgressEulerTotality.armedRoot_reaches_prefixResult
#print axioms PureSFormal.Research.RootResetProgressEulerTotality.openRight_reaches_prefixResult
#print axioms PureSFormal.Research.RootResetProgressEulerTotality.down_reaches_prefixResult_or_afterUp
#print axioms PureSFormal.Research.RootResetProgressEulerTotality.inspect_closed_eleven_root
#print axioms PureSFormal.Research.RootResetProgressEulerTotality.inspect_closed_eleven_parent
#print axioms PureSFormal.Research.RootResetProgressEulerTotality.inspect_reaches_prefixResult_or_afterUp
#print axioms PureSFormal.Research.RootResetProgressEulerTotality.afterUp_block
#print axioms PureSFormal.Research.RootResetProgressEulerTotality.afterUp_prefixHaltsWithin
#print axioms PureSFormal.Research.RootResetProgressEulerTotality.progressPrefix_haltsWithin_linear
#print axioms PureSFormal.Research.RootResetProgressEulerTotality.WholeResult.source_eq
#print axioms PureSFormal.Research.RootResetProgressEulerTotality.WholeResult.terminal
#print axioms PureSFormal.Research.RootResetProgressEulerTotality.lifted_rootExecution_result
#print axioms PureSFormal.Research.RootResetProgressEulerTotality.abort_suffix_result
#print axioms PureSFormal.Research.RootResetProgressEulerTotality.wholeInvocation_haltsWithin_linear
#print axioms PureSFormal.Research.RootResetProgressEulerTotality.step_terminal
#print axioms PureSFormal.Research.RootResetProgressEulerTotality.run_terminal
#print axioms PureSFormal.Research.RootResetProgressEulerTotality.wholeInvocation_run_linear_result
#print axioms PureSFormal.Research.RootResetProgressEulerTotality.wholeInvocation_bare_controller_total
#print axioms PureSFormal.Research.RootResetProgressEulerTotality.wholeInvocation_moves_linear
