import PureSFormal.Research.RootResetProgressTransactionClassifier

#print axioms PureSFormal.Research.RootResetProgressTransactionClassifier.checkedSelection?_sound
#print axioms PureSFormal.Research.RootResetProgressTransactionClassifier.checkedSelection?_fields
#print axioms PureSFormal.Research.RootResetProgressTransactionClassifier.selectCompletedPath?_sound
#print axioms PureSFormal.Research.RootResetProgressTransactionClassifier.freshLocal_status_contracts
#print axioms PureSFormal.Research.RootResetProgressTransactionClassifier.freshResponse_close_contracts
#print axioms PureSFormal.Research.RootResetProgressTransactionClassifier.classifyCarrier?_cleanNonempty_sound
#print axioms PureSFormal.Research.RootResetProgressTransactionClassifier.classifyCarrier?_openCarrier_sound
#print axioms PureSFormal.Research.RootResetProgressTransactionClassifier.classifyCarrier?_complete_cleanEmpty
#print axioms PureSFormal.Research.RootResetProgressTransactionClassifier.classifyCarrier?_complete_cleanNonempty
#print axioms PureSFormal.Research.RootResetProgressTransactionClassifier.classifyCarrier?_complete_openCarrier
#print axioms PureSFormal.Research.RootResetProgressTransactionClassifier.classifyCarrier?_rejects_multipleOpens
#print axioms PureSFormal.Research.RootResetProgressTransactionClassifier.selectCompletedResponse?_sound
#print axioms PureSFormal.Research.RootResetProgressTransactionClassifier.selectCompletedResponse?_rejects_multipleOpens
#print axioms PureSFormal.Research.RootResetProgressTransactionClassifier.selectCompletedResponse?_marked_none
#print axioms PureSFormal.Research.RootResetProgressTransactionClassifier.selectCompletedResponse?_complete_open
#print axioms PureSFormal.Research.RootResetProgressTransactionClassifier.selectCompletedResponse?_complete_clean

set_option pp.proofs true in
#print PureSFormal.Research.RootResetProgressTransactionClassifier.selectCompletedResponse?_sound
