import PureSFormal.Research.RootResetMarkerTrajectoryCompleteness

#print axioms PureSFormal.Research.RootResetMarkerTrajectoryCompleteness.observed_of_reaches
#print axioms PureSFormal.Research.RootResetMarkerTrajectoryCompleteness.selected_empty_observed
#print axioms PureSFormal.Research.RootResetMarkerTrajectoryCompleteness.selected_firstEmpty_observed
#print axioms PureSFormal.Research.RootResetMarkerTrajectoryCompleteness.nonemptyBase_firstEmpty_observed
#print axioms PureSFormal.Research.RootResetMarkerTrajectoryCompleteness.clean_positiveStageSource_reachable
#print axioms PureSFormal.Research.RootResetMarkerTrajectoryCompleteness.firstEmpty_observed
#print axioms PureSFormal.Research.RootResetMarkerTrajectoryCompleteness.initiallyEmpty_observed
#print axioms PureSFormal.Research.RootResetMarkerTrajectoryCompleteness.eventuallyEmpty_implies_observed
#print axioms PureSFormal.Research.RootResetMarkerTrajectoryCompleteness.eventuallyEmpty_implies_observed_sample
#print axioms PureSFormal.Research.RootResetMarkerTrajectoryCompleteness.rootRun_eq_sample
#print axioms PureSFormal.Research.RootResetMarkerTrajectoryCompleteness.eventuallyEmpty_implies_root_observed
#print axioms PureSFormal.Research.RootResetMarkerTrajectoryCompleteness.eventuallyEmpty_implies_actual_root_event
