import PureSFormal.Research.RootResetProgressTotality

#print axioms PureSFormal.Research.RootResetProgressTotality.step_terminal
#print axioms PureSFormal.Research.RootResetProgressTotality.run_terminal
#print axioms PureSFormal.Research.RootResetProgressTotality.HaltsWithin.run_bound_terminal
#print axioms PureSFormal.Research.RootResetProgressTotality.down_reaches_terminal_or_afterUp
#print axioms PureSFormal.Research.RootResetProgressTotality.inspect_closed_eleven_parent
#print axioms PureSFormal.Research.RootResetProgressTotality.inspect_closed_eleven_root
#print axioms PureSFormal.Research.RootResetProgressTotality.inspect_eleven_terminal_or_afterUp
#print axioms PureSFormal.Research.RootResetProgressTotality.afterUp_twelve_terminal_or_shorter
#print axioms PureSFormal.Research.RootResetProgressTotality.afterUp_haltsWithin
#print axioms PureSFormal.Research.RootResetProgressTotality.depth_add_focus_size_le_erase_size
#print axioms PureSFormal.Research.RootResetProgressTotality.depth_succ_le_erase_size
#print axioms PureSFormal.Research.RootResetProgressTotality.progressFragment_haltsWithin_linear
#print axioms PureSFormal.Research.RootResetProgressTotality.progressFragment_run_linear_terminal
#print axioms PureSFormal.Research.RootResetProgressTotality.progressFragment_bare_controller_total
#print axioms PureSFormal.Research.RootResetProgressTotality.progressFragment_moves_linear
#print axioms PureSFormal.Research.RootResetProgressTotality.progressFragment_haltsWithin_finiteStateBound
