import PureSFormal.Research.RootResetFiniteAllInputsTraceAgreement
#print axioms PureSFormal.Research.RootResetFiniteAllInputsTraceAgreement.selectsEveryContractionRun
#print axioms PureSFormal.Research.RootResetFiniteAllInputsTraceAgreement.agreesWithStructuralSelector
#print axioms PureSFormal.Research.RootResetFiniteAllInputsTraceAgreement.agreesOnEverySample
#print axioms PureSFormal.Research.RootResetFiniteAllInputsTraceAgreement.finiteCTSUniversality
#print axioms PureSFormal.Research.RootResetFiniteAllInputsTraceAgreement.transferred_path_eq
#print axioms PureSFormal.Research.RootResetFiniteAllInputsTraceAgreement.termOnlyPath_eq_persistentPath
