import PureSFormal.Research.RootResetMixedNonemptyStages

#print axioms PureSFormal.Research.RootResetMixedNonemptyStages.SelectedNonfinalInvariantAt
#print axioms PureSFormal.Research.RootResetMixedNonemptyStages.completeNonfinalAt
#print axioms PureSFormal.Research.RootResetMixedNonemptyStages.allNonemptyRawAt
