import PureSFormal.Research.RootResetResponseSelectorInitialAgreement

#print axioms PureSFormal.Research.RootResetResponseSelectorInitialAgreement.twentySeven_selectStep?_initial
#print axioms PureSFormal.Research.RootResetResponseSelectorInitialAgreement.parseLocal?_generator_none
#print axioms PureSFormal.Research.RootResetResponseSelectorInitialAgreement.parseFrameR0?_generator_none
#print axioms PureSFormal.Research.RootResetResponseSelectorInitialAgreement.parsePending?_generator_none
#print axioms PureSFormal.Research.RootResetResponseSelectorInitialAgreement.routeNext?_generator_none
#print axioms PureSFormal.Research.RootResetResponseSelectorInitialAgreement.fuelParser_generator_none
#print axioms PureSFormal.Research.RootResetResponseSelectorInitialAgreement.fuelActiveContext_generator
#print axioms PureSFormal.Research.RootResetResponseSelectorInitialAgreement.activeContext_generator
#print axioms PureSFormal.Research.RootResetResponseSelectorInitialAgreement.persistent_selectStep?_initial
#print axioms PureSFormal.Research.RootResetResponseSelectorInitialAgreement.responseDescentContext_generator
#print axioms PureSFormal.Research.RootResetResponseSelectorInitialAgreement.responseOuter_generator
#print axioms PureSFormal.Research.RootResetResponseSelectorInitialAgreement.freshResponseRoot?_generator_none
#print axioms PureSFormal.Research.RootResetResponseSelectorInitialAgreement.freshDispatcherSelection?_generator_none
#print axioms PureSFormal.Research.RootResetResponseSelectorInitialAgreement.responseBoundarySelection?_generator_none
#print axioms PureSFormal.Research.RootResetResponseSelectorInitialAgreement.responseAppenderSelection?_generator_none
#print axioms PureSFormal.Research.RootResetResponseSelectorInitialAgreement.dispatcherSelection?_generator_none
#print axioms PureSFormal.Research.RootResetResponseSelectorInitialAgreement.selectedActionSelection?_generator_none
#print axioms PureSFormal.Research.RootResetResponseSelectorInitialAgreement.appenderSelection?_generator_none
#print axioms PureSFormal.Research.RootResetResponseSelectorInitialAgreement.classify_generator_ne_activatedRoute
#print axioms PureSFormal.Research.RootResetResponseSelectorInitialAgreement.activatedRouteSelection?_generator_none
#print axioms PureSFormal.Research.RootResetResponseSelectorInitialAgreement.selectStep?_initial
#print axioms PureSFormal.Research.RootResetResponseSelectorInitialAgreement.initialPrelude_selectorChain
#print axioms PureSFormal.Research.RootResetResponseSelectorInitialAgreement.clockLaunchFuel_persistentSelectorChain
