import PureSFormal.Research.RootResetSelectedFrontParserAgreement

namespace PureSFormal.Research.RootResetSelectedFrontParserAgreementAudit

#print axioms RootResetSelectedFrontParserAgreement.spineFirstLiveAddress?_emptyQueue
#print axioms RootResetSelectedFrontParserAgreement.spineFirstLiveAddress?_underQueue
#print axioms RootResetSelectedFrontParserAgreement.spineFirstLiveAddress?_ofQueueSelection
#print axioms RootResetSelectedFrontParserAgreement.firstLiveAddress?_descent_empty
#print axioms RootResetSelectedFrontParserAgreement.firstLiveAddress?_ofSelectedFront
#print axioms RootResetSelectedFrontParserAgreement.firstLiveAddress?_contracts_belowParents

end PureSFormal.Research.RootResetSelectedFrontParserAgreementAudit
