import PureSFormal.Research.RootResetProgressEulerContract

#print axioms PureSFormal.Research.RootResetProgressEulerContract.transition_stay_doneRedex_iff
#print axioms PureSFormal.Research.RootResetProgressEulerContract.transition_exec_doneRedex_iff
#print axioms PureSFormal.Research.RootResetProgressEulerContract.transition_exec_rdx_target
#print axioms PureSFormal.Research.RootResetProgressEulerContract.redexFlag_step
#print axioms PureSFormal.Research.RootResetProgressEulerContract.redexFlag_run
#print axioms PureSFormal.Research.RootResetProgressEulerContract.final_result
#print axioms PureSFormal.Research.RootResetProgressEulerContract.redexFlag_initial
#print axioms PureSFormal.Research.RootResetProgressEulerContract.wholeInvocation_mutationCount_eq_redexFlag
#print axioms PureSFormal.Research.RootResetProgressEulerContract.final_terminal_cases
#print axioms PureSFormal.Research.RootResetProgressEulerContract.final_nf_normal
#print axioms PureSFormal.Research.RootResetProgressEulerContract.final_nf_erase
#print axioms PureSFormal.Research.RootResetProgressEulerContract.final_redex_contracts
#print axioms PureSFormal.Research.RootResetProgressEulerContract.final_nf_mutationCount
#print axioms PureSFormal.Research.RootResetProgressEulerContract.final_redex_mutationCount
#print axioms PureSFormal.Research.RootResetProgressEulerContract.outcome
#print axioms PureSFormal.Research.RootResetProgressEulerContract.final_runtime_terminal
#print axioms PureSFormal.Research.RootResetProgressEulerContract.outcome_agrees
#print axioms PureSFormal.Research.RootResetProgressEulerContract.mutationCount_agrees
#print axioms PureSFormal.Research.RootResetProgressEulerContract.selectorContract
#print axioms PureSFormal.Research.RootResetProgressEulerContract.selector_exact_mutation_count
#print axioms PureSFormal.Research.RootResetProgressEulerContract.selector_halts_linear
#print axioms PureSFormal.Research.RootResetProgressEulerContract.selector_moves_linear
