import PureSFormal.Research.RootResetTraversableCompletedParents

open PureSFormal.Research.RootResetTraversableCompletedParents

#print axioms TraversableParents.toCompleted
#print axioms TraversableParents.parseLocal?_fresh
#print axioms TraversableParents.parseFreshNonempty?_fresh
#print axioms TraversableParents.parseMarkedLocal?_marked
#print axioms TraversableParents.empty
#print axioms PureSFormal.Research.RootResetTraversableCompletedParents.TraversableParents.FuelTraversableAt.toTraversable
#print axioms PureSFormal.Research.RootResetTraversableCompletedParents.TraversableParents.FuelTraversableAt.fuelActiveContext_rebuild_active
#print axioms PureSFormal.Research.RootResetTraversableCompletedParents.TraversableParents.FuelTraversableAt.fuelActiveContext_rebuild_context
#print axioms PureSFormal.Research.RootResetTraversableCompletedParents.TraversableParents.FuelTraversableAt.fuelActiveContext_rebuild_address
#print axioms PureSFormal.Research.RootResetTraversableCompletedParents.TraversableParents.FuelTraversableAt.responseOuter_rebuild_active
#print axioms PureSFormal.Research.RootResetTraversableCompletedParents.TraversableParents.FuelTraversableAt.responseOuter_rebuild_context
#print axioms PureSFormal.Research.RootResetTraversableCompletedParents.TraversableParents.FuelTraversableAt.responseOuter_rebuild_address
#print axioms TraversableParents.contextOfParents_fresh
#print axioms TraversableParents.contextOfParents_marked
#print axioms TraversableParents.activeContext_rebuild_active
#print axioms TraversableParents.activeContext_rebuild_context
#print axioms TraversableParents.activeContext_rebuild_address
