import PureSFormal.Research.RootResetProgressEulerSelector

#print axioms PureSFormal.Research.RootResetProgressEulerSelector.mem_states
#print axioms PureSFormal.Research.RootResetProgressEulerSelector.states_nodup
#print axioms PureSFormal.Research.RootResetProgressEulerSelector.states_length
#print axioms PureSFormal.Research.RootResetProgressEulerSelector.terminal_controls_absorbing
#print axioms PureSFormal.Research.RootResetProgressEulerSelector.preFallback_transition_ne_reject
#print axioms PureSFormal.Research.RootResetProgressEulerSelector.armedRoot_verifies_or_aborts
#print axioms PureSFormal.Research.RootResetProgressEulerSelector.openRight_verifies_or_aborts
#print axioms PureSFormal.Research.RootResetProgressEulerSelector.run_abort_to_euler_visit
#print axioms PureSFormal.Research.RootResetProgressEulerSelector.abort_ticks_le_erase_size
#print axioms PureSFormal.Research.RootResetProgressEulerSelector.transition_euler
#print axioms PureSFormal.Research.RootResetProgressEulerSelector.step_liftEuler
#print axioms PureSFormal.Research.RootResetProgressEulerSelector.run_liftEuler
#print axioms PureSFormal.Research.RootResetProgressEulerSelector.mutationCount_liftEuler
#print axioms PureSFormal.Research.RootResetProgressEulerSelector.runMutationCount_liftEuler
#print axioms PureSFormal.Research.RootResetProgressEulerSelector.run_abort_then_rootExecution
#print axioms PureSFormal.Research.RootResetProgressEulerSelector.abort_then_rootExecution_ticks_le
#print axioms PureSFormal.Research.RootResetProgressEulerSelector.compiled_control_state_cardinality
