import PureSFormal.Research.RootResetMixedStagePhaseSelectorChain

#print axioms PureSFormal.Research.RootResetMixedStagePhaseSelectorChain.positiveClockMutation_mixedParents_selects_next
#print axioms PureSFormal.Research.RootResetMixedStagePhaseSelectorChain.clockFirst_mixedParents_selects_first
#print axioms PureSFormal.Research.RootResetMixedStagePhaseSelectorChain.clockCompleted_mixedParents_selects_launch
#print axioms PureSFormal.Research.RootResetMixedStagePhaseSelectorChain.generatedFuelRow_mixed_selectStep?
#print axioms PureSFormal.Research.RootResetMixedStagePhaseSelectorChain.clockTail_mixedSelectorChain
#print axioms PureSFormal.Research.RootResetMixedStagePhaseSelectorChain.clock_mixedSelectorChain
#print axioms PureSFormal.Research.RootResetMixedStagePhaseSelectorChain.clockLaunch_mixed_exact_selectorChain
#print axioms PureSFormal.Research.RootResetMixedStagePhaseSelectorChain.fuelPositiveScriptSource_mixed_selects_first
#print axioms PureSFormal.Research.RootResetMixedStagePhaseSelectorChain.fuelPositiveFirst_mixed_selects_second
#print axioms PureSFormal.Research.RootResetMixedStagePhaseSelectorChain.fuelZeroScriptSource_mixed_selects_first
#print axioms PureSFormal.Research.RootResetMixedStagePhaseSelectorChain.fuelZeroFirst_mixed_selects_second
#print axioms PureSFormal.Research.RootResetMixedStagePhaseSelectorChain.fuelZeroSecond_mixed_selects_third
#print axioms PureSFormal.Research.RootResetMixedStagePhaseSelectorChain.fuelZeroThird_mixed_selects_fourth
#print axioms PureSFormal.Research.RootResetMixedStagePhaseSelectorChain.fuelZeroFourth_mixed_selects_fifth
#print axioms PureSFormal.Research.RootResetMixedStagePhaseSelectorChain.fuel_mixedSelectorChain
#print axioms PureSFormal.Research.RootResetMixedStagePhaseSelectorChain.positiveStage_mixed_exact_selectorChain
