import PureSFormal.Research.RootResetFiniteInitialEmptyStages

#print axioms PureSFormal.Research.RootResetFiniteInitialEmptyStages.initialEmpty_frame_selectorChain
#print axioms PureSFormal.Research.RootResetFiniteInitialEmptyStages.initialEmpty_completeSweep_selectorChain
#print axioms PureSFormal.Research.RootResetFiniteInitialEmptyStages.initialEmpty_completeResponses_selectorChain
#print axioms PureSFormal.Research.RootResetFiniteInitialEmptyStages.fuelPrefix_exact_selectorChain
#print axioms PureSFormal.Research.RootResetFiniteInitialEmptyStages.nonterminalEmptyHandoff_selectorChain
#print axioms PureSFormal.Research.RootResetFiniteInitialEmptyStages.nonterminal_selectorChain
#print axioms PureSFormal.Research.RootResetFiniteInitialEmptyStages.terminal_selectorChain
#print axioms PureSFormal.Research.RootResetFiniteInitialEmptyStages.jobs_selectorChain
#print axioms PureSFormal.Research.RootResetFiniteInitialEmptyStages.stage_selectorChain
#print axioms PureSFormal.Research.RootResetFiniteInitialEmptyStages.stages_selectorChain
#print axioms PureSFormal.Research.RootResetFiniteInitialEmptyStages.emptyInput_unbounded_exact_selectorChains
#print axioms PureSFormal.Research.RootResetFiniteInitialEmptyStages.emptyInput_selectsEveryContractionRun
