import PureSFormal.WeakPath.Interface

/-!
# Transfer from an exact path to a term-only selector

This module isolates the final semantic step of the root-reset argument.  A
term-only selector is a total function of the current bare term.  Its
projection relation requires the selected successor at every path index.
Consequently, pointwise agreement with an already certified exact path
transfers the complete checkpoint theorem without changing the path, encoder,
decoder, or checkpoint sequence.
-/

namespace PureSFormal.Research.RootResetTermOnlyTransfer

open PureSFormal.PureS

/-- A deterministic selector receives only the current bare term. -/
abbrev Selector := Term → Option Term

/--
The path is generated by the selector when every successor is its returned
term.  The scheduler argument is retained so this relation fits the common
`WeakPath.SchedulerProjection` interface.
-/
def Projects (selector : Selector) :
    WeakPath.SchedulerProjection Selector :=
  fun scheduler initialTerm path =>
    scheduler = selector ∧
      path.term 0 = initialTerm ∧
      ∀ index, scheduler (path.term index) = some (path.term (index + 1))

/-- Iteration with a fixed point only on selector failure. -/
def run (selector : Selector) : Nat → Term → Term
  | 0, term => term
  | index + 1, term =>
      let current := run selector index term
      (selector current).getD current

@[simp]
theorem run_zero (selector : Selector) (term : Term) :
    run selector 0 term = term :=
  rfl

@[simp]
theorem run_succ (selector : Selector) (index : Nat) (term : Term) :
    run selector (index + 1) term =
      (selector (run selector index term)).getD
        (run selector index term) :=
  rfl

/-- A generated path is definitionally equal to explicit selector iteration. -/
theorem run_eq_path
    {selector : Selector} {initialTerm : Term}
    {path : WeakPath.ReductionPath}
    (generated : Projects selector selector initialTerm path) :
    ∀ index, run selector index initialTerm = path.term index := by
  intro index
  induction index with
  | zero => exact generated.2.1.symm
  | succ index ih =>
      rw [run_succ, ih, generated.2.2 index]
      rfl

/--
Replace an operational scheduler projection by a term-only projection when
the selector returns the same next term at every contraction sample.
-/
def transferUniform
    {program : CTS.Program}
    {Scheduler : Type u}
    {sourceProjects : WeakPath.SchedulerProjection Scheduler}
    {sourceScheduler : Scheduler}
    {decoder : WeakPath.BareTermDecoder program}
    (source : WeakPath.UniformRealizes program sourceProjects sourceScheduler decoder)
    (selector : Selector)
    (agrees : ∀ word index,
      selector ((source.path word).term index) =
        some ((source.path word).term (index + 1))) :
    WeakPath.UniformRealizes program (Projects selector) selector decoder where
  encode := source.encode
  path := source.path
  checkpointTime := source.checkpointTime
  realizes word :=
    { startsAt := (source.realizes word).startsAt
      isProjection := ⟨rfl, (source.realizes word).startsAt, agrees word⟩
      checkpointZero := (source.realizes word).checkpointZero
      checkpointsIncrease := (source.realizes word).checkpointsIncrease
      exactCheckpoint := (source.realizes word).exactCheckpoint
      acceptsOnly := (source.realizes word).acceptsOnly }

/-- The transferred realization has literally the original certified path. -/
@[simp]
theorem transferUniform_path
    {program : CTS.Program}
    {Scheduler : Type u}
    {sourceProjects : WeakPath.SchedulerProjection Scheduler}
    {sourceScheduler : Scheduler}
    {decoder : WeakPath.BareTermDecoder program}
    (source : WeakPath.UniformRealizes program sourceProjects sourceScheduler decoder)
    (selector : Selector)
    (agrees : ∀ word index,
      selector ((source.path word).term index) =
        some ((source.path word).term (index + 1)))
    (word : List Bool) :
    (transferUniform source selector agrees).path word = source.path word :=
  rfl

/-- Selector iteration is identical to every term of the transferred path. -/
theorem transferUniform_run_eq
    {program : CTS.Program}
    {Scheduler : Type u}
    {sourceProjects : WeakPath.SchedulerProjection Scheduler}
    {sourceScheduler : Scheduler}
    {decoder : WeakPath.BareTermDecoder program}
    (source : WeakPath.UniformRealizes program sourceProjects sourceScheduler decoder)
    (selector : Selector)
    (agrees : ∀ word index,
      selector ((source.path word).term index) =
        some ((source.path word).term (index + 1)))
    (word : List Bool) (index : Nat) :
    run selector index (source.encode word) = (source.path word).term index := by
  apply run_eq_path
  exact (transferUniform source selector agrees).realizes word |>.isProjection

end PureSFormal.Research.RootResetTermOnlyTransfer
