import PureSFormal.Research.RootResetActiveResponseEndpointExecution
#print axioms PureSFormal.Research.RootResetActiveResponseEndpointExecution.fresh_selected
#print axioms PureSFormal.Research.RootResetActiveResponseEndpointExecution.carrier_not_two
#print axioms PureSFormal.Research.RootResetActiveResponseEndpointExecution.initial
#print axioms PureSFormal.Research.RootResetActiveResponseEndpointExecution.route
#print axioms PureSFormal.Research.RootResetActiveResponseEndpointExecution.action_call
#print axioms PureSFormal.Research.RootResetActiveResponseEndpointExecution.appender
#print axioms PureSFormal.Research.RootResetActiveResponseEndpointExecution.of_facts
#print axioms PureSFormal.Research.RootResetActiveResponseEndpointExecution.selected_response
#print axioms PureSFormal.Research.RootResetActiveResponseEndpointExecution.first_response
#print axioms PureSFormal.Research.RootResetActiveResponseEndpointExecution.initial_empty_sweep
#print axioms PureSFormal.Research.RootResetActiveResponseEndpointExecution.empty_sweep
