import PureSFormal.Research.RootResetClockFuelStages

namespace PureSFormal.Research.RootResetClockFuelStages

#print axioms decodeC?_s
#print axioms decodeC?_C
#print axioms rights_zero
#print axioms rights_succ
#print axioms rights_length
#print axioms pendingContext_nil
#print axioms pendingContext_cons
#print axioms pendingContext_address
#print axioms parseClockCore?_generated
#print axioms parseClockCore?_sound
#print axioms parseClockExitCore?_generated
#print axioms parseClockExitCore?_sound
#print axioms parseClock?_sound
#print axioms parseClock?_generated_positive
#print axioms parseClock?_generated_zero
#print axioms parseClockCore?_clockWrappers_succ_none
#print axioms parseClock?_generated_launch
#print axioms parseFuelCall?_sound
#print axioms parseFuelCall?_generated
#print axioms parsePositiveHalf?_sound
#print axioms parsePositiveHalf?_generated
#print axioms parseZeroFirst?_sound
#print axioms parseZeroFirst?_generated
#print axioms parseZeroSecond?_sound
#print axioms parseZeroSecond?_generated
#print axioms parseZeroThird?_sound
#print axioms parseZeroThird?_generated
#print axioms parseZeroFourth?_sound
#print axioms parseZeroFourth?_generated
#print axioms parseCanonicalZeroRoot?_sound
#print axioms parseCanonicalZeroRoot?_second
#print axioms parseCanonicalZeroRoot?_fourth
#print axioms parseCanonicalZeroRoot?_stage
#print axioms parseFuelRow?_sound
#print axioms FuelRow.term_headArity_le_four
#print axioms parseFuelRow?_none_of_four_lt_headArity
#print axioms decodeC?_openEnvironment_none
#print axioms parseFuelRow?_generated_positiveHalf
#print axioms parseFuelRow?_generated_zeroFirst
#print axioms parseFuelRow?_generated_zeroSecond
#print axioms zeroFirst_term_ne_zeroThird_term
#print axioms parseZeroFirst?_zeroThird_none_of_admissible
#print axioms parseFuelRow?_generated_zeroThird
#print axioms zeroSecond_term_ne_zeroFourth_term
#print axioms parseFuelRow?_generated_zeroFourth
#print axioms FuelRow.focus_subterm
#print axioms FuelRow.contractAt?_eq
#print axioms FuelRow.replace?_eq_some_target
#print axioms FuelRow.contractAt?_eq_some_target
#print axioms parseOpenBase?_sound
#print axioms parseOpenBase?_generated
#print axioms openBase_eq_independent
#print axioms OpenBaseView.term_headArity
#print axioms parseFuelEndpoint?_sound
#print axioms parseFuelActive?_sound
#print axioms parseFuelEndpoint?_row
#print axioms parseFuelEndpoint?_carrier
#print axioms parseFuelEndpoint?_canonicalCarrier
#print axioms parseEnvironment?_none_of_admissible
#print axioms parseFuelActive?_canonicalCarrier
#print axioms parseFuelActive?_complete
#print axioms FuelView.canonicalChild_subterm
#print axioms FuelView.selected_contracts_exact
#print axioms FuelView.selected_contracts
#print axioms FuelView.endpoint_size_lt_of_layers_ne_nil
#print axioms clockGrowthCore_subterm
#print axioms ClockView.focus_subterm
#print axioms ClockView.residual_pos_of_launch
#print axioms ClockView.focus_contractRoot?_eq
#print axioms ClockView.contractAt?_eq
#print axioms ClockView.selected_contracts
#print axioms parseActive?_sound
#print axioms parse?_sound
#print axioms parse?_complete
#print axioms parse?_unique
#print axioms parse?_history_marked
#print axioms WholeShape.clock_parse
#print axioms WholeShape.fuel_parse
#print axioms View.canonicalChild_subterm
#print axioms View.selected_contracts
#print axioms Active.clock_ne_fuel
#print axioms parseActive?_unique
#print axioms parseFuelRow?_generated_call
#print axioms FuelEndpoint.row_ne_carrier
#print axioms FuelView.horizon_eq
#print axioms FuelView.horizon_call
#print axioms View.source_eq
#print axioms View.canonicalChild_size_lt_of_address_cons
#print axioms parseFuelActive?_pending
#print axioms pending_payload_opaque

end PureSFormal.Research.RootResetClockFuelStages
