import PureSFormal.Research.RootResetFiniteStageLaws
#print axioms PureSFormal.Research.RootResetFiniteStageLaws.laws
#print axioms PureSFormal.Research.RootResetFiniteStageLaws.bitcons_selectsEveryContractionRun
