import PureSFormal.Research.RootResetMarkerObserverSoundness

#print axioms PureSFormal.Research.RootResetMarkerObserverSoundness.accepted_sample_implies_eventuallyEmpty
#print axioms PureSFormal.Research.RootResetMarkerObserverSoundness.sampled_observed_iff_eventuallyEmpty
#print axioms PureSFormal.Research.RootResetMarkerObserverSoundness.raw_observed_iff_eventuallyEmpty
#print axioms PureSFormal.Research.RootResetMarkerObserverSoundness.accepted_root_implies_eventuallyEmpty
#print axioms PureSFormal.Research.RootResetMarkerObserverSoundness.root_observed_iff_eventuallyEmpty
