import PureSFormal.Research.RootResetFiniteStagePhaseSelectorChain
#print axioms PureSFormal.Research.RootResetFiniteStagePhaseSelectorChain.positiveClockMutation_finiteParents_selects_next
#print axioms PureSFormal.Research.RootResetFiniteStagePhaseSelectorChain.clockFirst_finiteParents_selects_first
#print axioms PureSFormal.Research.RootResetFiniteStagePhaseSelectorChain.clockCompleted_finiteParents_selects_launch
#print axioms PureSFormal.Research.RootResetFiniteStagePhaseSelectorChain.clockTail_finiteSelectorChain
#print axioms PureSFormal.Research.RootResetFiniteStagePhaseSelectorChain.clock_finiteSelectorChain
#print axioms PureSFormal.Research.RootResetFiniteStagePhaseSelectorChain.clockLaunch_finite_exact_selectorChain
#print axioms PureSFormal.Research.RootResetFiniteStagePhaseSelectorChain.fuelPositiveScriptSource_finite_selects_first
#print axioms PureSFormal.Research.RootResetFiniteStagePhaseSelectorChain.fuelPositiveFirst_finite_selects_second
#print axioms PureSFormal.Research.RootResetFiniteStagePhaseSelectorChain.fuelZeroScriptSource_finite_selects_first
#print axioms PureSFormal.Research.RootResetFiniteStagePhaseSelectorChain.fuelZeroFirst_finite_selects_second
#print axioms PureSFormal.Research.RootResetFiniteStagePhaseSelectorChain.fuelZeroSecond_finite_selects_third
#print axioms PureSFormal.Research.RootResetFiniteStagePhaseSelectorChain.fuelZeroThird_finite_selects_fourth
#print axioms PureSFormal.Research.RootResetFiniteStagePhaseSelectorChain.fuelZeroFourth_finite_selects_fifth
#print axioms PureSFormal.Research.RootResetFiniteStagePhaseSelectorChain.fuel_finiteSelectorChain
#print axioms PureSFormal.Research.RootResetFiniteStagePhaseSelectorChain.positiveStage_finite_exact_selectorChain
