/* Build a local full-text index from the same anchors as the paper renderer. */
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const search = require('../paper/search-engine.js');
module.exports = function buildSearch(root, sections) {
  const escape = value => value.replace(/[&<>"']/g, ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const context = { renderLatex: tex => escape(search.plainText(tex)) };
  vm.createContext(context);
  vm.runInContext(fs.readFileSync(path.join(root, 'paper/markdown.js'), 'utf8'), context);
  const decode = html => html.replace(/<[^>]+>/g,' ').replace(/&(amp|lt|gt|quot|#39|nbsp);/g,(_,name)=>({amp:'&',lt:'<',gt:'>',quot:'"','#39':"'",nbsp:' '}[name])).replace(/\s+/g,' ').trim();
  const records=[];
  const searchSections=sections.map(section => ({id:section.id,label:section.label,group:section.group,anchor:context.markdownHeadingSlug(section.title),context:section.group==='Main text'?'Section '+Number(section.number):section.group==='Appendices'?'Appendix '+section.number:''}));
  sections.forEach((section, sectionIndex) => {
    // The contents repeat the manuscript, so index their title without duplicating every result.
    if(section.id==='contents') {
      records.push([sectionIndex,context.markdownHeadingSlug(section.title),section.title,'']); return;
    }
    const anchors=new Map();
    const source=fs.readFileSync(path.join(root,'docs/paper',section.file),'utf8');
    const html=context.renderMarkdown(source,{onAnchor:anchor=>anchors.set(anchor.id,search.plainText(anchor.label))});
    const boundaries=[...html.matchAll(/<(?:h[1-6]|p|li|span)\b[^>]*\bid="([^"]+)"[^>]*>/g)].filter(match=>anchors.has(match[1]));
    boundaries.forEach((match,i) => {
      const title=anchors.get(match[1]);
      let body=decode(html.slice(match.index+match[0].length,boundaries[i+1]?.index ?? html.length));
      if(body.startsWith(title)) body=body.slice(title.length).replace(/^[.:;]\s*/, '').trim();
      // Bound each passage so ranking stays useful in long, densely mathematical chapters.
      const words=body.split(/\s+/);
      for(let start=0; start<Math.max(1,words.length); start+=180) {
        records.push([sectionIndex,match[1],title,words.slice(start,start+220).join(' ')]);
      }
    });
  });
  return '// Generated by scripts/build-paper.cjs.\nwindow.PU_SEARCH_DATA = '+JSON.stringify(search.buildData(records,searchSections))+';\n';
};
