/* Refresh the file:// edition after editing docs/paper. No npm dependencies. */
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const crypto = require('node:crypto');
const root = path.resolve(__dirname, '..');
const docs = path.join(root, 'docs/paper');
const check = process.argv.includes('--check');
let differences = 0;
function emit(file, contents) {
  const destination = path.join(root, file);
  if (fs.existsSync(destination) && fs.readFileSync(destination, 'utf8') === contents) return;
  if (check) { console.error('Out of date: ' + file); differences++; return; }
  fs.mkdirSync(path.dirname(destination), { recursive: true });
  fs.writeFileSync(destination, contents);
}
function list(directory, prefix = '') {
  return fs.readdirSync(directory, { withFileTypes: true }).flatMap(entry =>
    entry.isDirectory() ? list(path.join(directory, entry.name), prefix + entry.name + '/') :
      entry.name.endsWith('.md') ? [prefix + entry.name] : []);
}
function group(file) {
  if (/^\d\d_/.test(file)) return 'Main text';
  if (file.startsWith('appendices/')) return 'Appendices';
  if (/^(glossary|references)\.md$/.test(file)) return 'Reference';
  return 'Reading guides & related work';
}
const groups = ['Main text', 'Appendices', 'Reference', 'Reading guides & related work'];
const shortTitles = ['Abstract', 'Introduction', 'Foundations', 'Space of Becoming', 'SPAP', 'Horizon Constant',
  'Complexity & Resources', 'Minimal Predictive Unit', 'Quantum Emergence', 'Consciousness Complexity',
  'Statistical Influence', 'Spacetime Emergence', 'Gravity Derivation', 'Experimental Predictions', 'Discussion', 'Conclusion'];
const relatedPapers = [{
  id: 'related--pure_s_universality--paper',
  title: 'Pure S Is Computationally Universal Under a Fixed Root-Restarted Finite Controller',
  source: 'related/pure_s_universality/paper.md',
  file: 'related/pure_s_universality/output/pdf/pure_s_universality.pdf'
}];
const sections = list(docs).filter(file => !file.startsWith('related/pure_s_universality/'))
  .sort((a, b) => groups.indexOf(group(a)) - groups.indexOf(group(b)) || a.localeCompare(b)).map(file => {
  const markdown = fs.readFileSync(path.join(docs, file), 'utf8');
  const id = file.replace(/\.md$/, '').replaceAll('/', '--');
  const title = (markdown.match(/^#\s+(.+)$/m)?.[1] || path.basename(file, '.md').replaceAll('_', ' ')).replace(/\*\*/g, '').trim();
  const number = file.match(/^(\d\d)_/)?.[1];
  const appendix = file.match(/^appendices\/appendix_([a-z])_/)?.[1].toUpperCase();
  const label = number ? shortTitles[Number(number)] : title.replace(/^Appendix\s+[A-Z][\s.:–—-]+/i, '');
  const hash = crypto.createHash('sha256').update(markdown).digest('hex');
  emit('paper/content/' + id + '.js', '// Generated from docs/paper/' + file + '. Run node scripts/build-paper.cjs.\n' +
    'window.PU_PAPER_TEXT = window.PU_PAPER_TEXT || {};\nwindow.PU_PAPER_TEXT[' + JSON.stringify(id) + '] = ' + JSON.stringify(markdown) + ';\n');
  return { id, file, title, label, group: group(file), number: number || appendix || '', hash };
});
const byNumber = n => sections.find(section => section.file.startsWith(String(n).padStart(2, '0') + '_')).id;
const byAppendix = letter => sections.find(section => section.file.startsWith('appendices/appendix_' + letter.toLowerCase() + '_')).id;
// Use the source labels in the existing scene catalogue as the source of truth.
const context = { window: { PU: {} } };
vm.runInNewContext(fs.readFileSync(path.join(root, 'visualization/js/content/catalogue.js'), 'utf8'), context);
const scenes = context.window.PU.catalogue.map(entry => {
  const refs = new Set();
  const main = entry.source.match(/Sections?\s+([\d.,;\s-]+)/i)?.[1];
  if (main) for (const part of main.split(/[,;]/)) {
    const range = part.trim().match(/^(\d+)(?:\.\d+)?(?:\s*-\s*(\d+))?/);
    if (range) for (let n = +range[1]; n <= +(range[2] || range[1]); n++) refs.add(byNumber(n));
  }
  const appendices = entry.source.match(/Append(?:ix|ices)\s+([A-Z,\s]+)/)?.[1];
  if (appendices) for (const letter of appendices.match(/[A-Z]/g) || []) refs.add(byAppendix(letter));
  return { key: entry.key, title: entry.label, source: entry.source, sections: [...refs] };
});
emit('paper/manifest.js', '// Generated by scripts/build-paper.cjs from the manuscript and scene catalogue.\nwindow.PU_PAPER = ' + JSON.stringify({ sections, scenes, relatedPapers }, null, 2) + ';\n');
emit('paper/search-index.js', require('./build-search.cjs')(root, sections));
if (differences) process.exitCode = 1;
else console.log((check ? 'Verified' : 'Updated') + ' ' + sections.length + ' manuscript sections and ' + scenes.length + ' scene mappings.');
