// Generated by scripts/build-paper.cjs from the manuscript and scene catalogue.
window.PU_PAPER = {
  "sections": [
    {
      "id": "00_abstract",
      "file": "00_abstract.md",
      "title": "The Predictive Universe",
      "label": "Abstract",
      "group": "Main text",
      "number": "00",
      "hash": "fe819d13d10d4b956d03f8e9f87dfb8928c04de392b03e3b3666a5743727074d"
    },
    {
      "id": "01_introduction",
      "file": "01_introduction.md",
      "title": "1. Introduction",
      "label": "Introduction",
      "group": "Main text",
      "number": "01",
      "hash": "4a4b8f572f30dee1ad772e672d06325b3766f484f0930c63e326e70429e3d6c7"
    },
    {
      "id": "02_foundations",
      "file": "02_foundations.md",
      "title": "2. Foundational Principles: Prediction, Optimization, and Resources",
      "label": "Foundations",
      "group": "Main text",
      "number": "02",
      "hash": "9b7e8edff0d8fe0c341555b685bb28716efd63d363f2718f54fe0b204a6dc0f5"
    },
    {
      "id": "03_space_of_becoming",
      "file": "03_space_of_becoming.md",
      "title": "3. The Dynamics of Prediction and Interaction",
      "label": "Space of Becoming",
      "group": "Main text",
      "number": "03",
      "hash": "d123996a4f9abfc8b2e88b5e0f0a10f89dc9d7fcb3fafcd87b3a9e832c500476"
    },
    {
      "id": "04_spap",
      "file": "04_spap.md",
      "title": "4. Self-Reference, Computation, and Fundamental Limits",
      "label": "SPAP",
      "group": "Main text",
      "number": "04",
      "hash": "5efdf2681d9e86d65f7fd45d6814270c855c35aa28faa634562b28bc7744ed22"
    },
    {
      "id": "05_horizon_constant",
      "file": "05_horizon_constant.md",
      "title": "5. Complexity Thresholds: Operational Threshold and Horizon Constant",
      "label": "Horizon Constant",
      "group": "Main text",
      "number": "05",
      "hash": "4b3bc3eb761f166007b94c03cfd3c33f6fd0fb10d7255407c4765979c85bdd83"
    },
    {
      "id": "06_complexity_resources",
      "file": "06_complexity_resources.md",
      "title": "6. Complexity, Performance, and Adaptation Dynamics",
      "label": "Complexity & Resources",
      "group": "Main text",
      "number": "06",
      "hash": "665c904f8fead9cf5bb3723106ac1ccef18baf707652f02730e9c43a6e8e6495"
    },
    {
      "id": "07_minimal_predictive_unit",
      "file": "07_minimal_predictive_unit.md",
      "title": "7. The Minimal Predictive Unit (MPU) Framework",
      "label": "Minimal Predictive Unit",
      "group": "Main text",
      "number": "07",
      "hash": "39ff641dbb44478063e6a9ce18b9db0c78575987f98eb608cdd80c9b4f8a99a2"
    },
    {
      "id": "08_quantum_emergence",
      "file": "08_quantum_emergence.md",
      "title": "8. Emergence of Quantum Mechanical Formalism",
      "label": "Quantum Emergence",
      "group": "Main text",
      "number": "08",
      "hash": "031ab52a6913e2d6cca6f012db320ef0c72bd45742b7b5ce55174af2fcfaa946"
    },
    {
      "id": "09_consciousness_complexity",
      "file": "09_consciousness_complexity.md",
      "title": "9. Consciousness Complexity (CC): Emergent Biasing of MPU Interactions",
      "label": "Consciousness Complexity",
      "group": "Main text",
      "number": "09",
      "hash": "717848dd2babd228143d4dd3f2fbb16bc454d117278a36c2ee63721d43902f77"
    },
    {
      "id": "10_statistical_influence",
      "file": "10_statistical_influence.md",
      "title": "10. Causality, Locality, and Statistical Influence",
      "label": "Statistical Influence",
      "group": "Main text",
      "number": "10",
      "hash": "a27527045473b1c1233f1ea6986e6eb575a1c33848aaa4a62e9d659ff7933e30"
    },
    {
      "id": "11_spacetime_emergence",
      "file": "11_spacetime_emergence.md",
      "title": "11. Emergence of Spacetime Geometry (Operational Continuum Branch)",
      "label": "Spacetime Emergence",
      "group": "Main text",
      "number": "11",
      "hash": "635da0920f49ca94db7de41fb1dcc7e4d2c6d43daaf25da27042e904b03900b2"
    },
    {
      "id": "12_gravity_derivation",
      "file": "12_gravity_derivation.md",
      "title": "12. Emergence of Gravitational Dynamics from Predictive Thermodynamics",
      "label": "Gravity Derivation",
      "group": "Main text",
      "number": "12",
      "hash": "9f79b6de6a0f7663e49a4aaeb525d3c848b11037d5a72ae649edfdefe0d35623"
    },
    {
      "id": "13_experimental_predictions",
      "file": "13_experimental_predictions.md",
      "title": "13. Experimental Predictions and Protocols",
      "label": "Experimental Predictions",
      "group": "Main text",
      "number": "13",
      "hash": "dcf7d59e166b6fbace6b90851838773c878e2e58c1d9a1012033060b97138567"
    },
    {
      "id": "14_discussion",
      "file": "14_discussion.md",
      "title": "14. Discussion",
      "label": "Discussion",
      "group": "Main text",
      "number": "14",
      "hash": "d8939259d11c5d8ad4878dca9721843198c6900ddc12e8046877db56619aa50d"
    },
    {
      "id": "15_conclusion",
      "file": "15_conclusion.md",
      "title": "15. Conclusion",
      "label": "Conclusion",
      "group": "Main text",
      "number": "15",
      "hash": "f84c924cd9df201249071cf17e0b30c899a4d0261db6b4465ad1dead4c49f565"
    },
    {
      "id": "appendices--appendix_a_core_logic",
      "file": "appendices/appendix_a_core_logic.md",
      "title": "Appendix A: Core Logic, Computation Limits, and Property R",
      "label": "Core Logic, Computation Limits, and Property R",
      "group": "Appendices",
      "number": "A",
      "hash": "2601632528fd136b28da1cfc9e7f049bbeb820b6c118a400690897ce7fd22ab9"
    },
    {
      "id": "appendices--appendix_b_complexity_costs",
      "file": "appendices/appendix_b_complexity_costs.md",
      "title": "Appendix B: Operational Complexity, Costs, and Stress–Energy Tensor Construction",
      "label": "Operational Complexity, Costs, and Stress–Energy Tensor Construction",
      "group": "Appendices",
      "number": "B",
      "hash": "c927756f471f1401a688af3016236800c16f548b11f45ff058231d0b8f2f022e"
    },
    {
      "id": "appendices--appendix_c_regularity_necessity",
      "file": "appendices/appendix_c_regularity_necessity.md",
      "title": "Appendix C: Necessity of Geometric Regularity",
      "label": "Necessity of Geometric Regularity",
      "group": "Appendices",
      "number": "C",
      "hash": "6ddcc8546e57cc9181353505325c32383e5c054bab3c0010ebb22c63a72c463a"
    },
    {
      "id": "appendices--appendix_d_variational_convergence",
      "file": "appendices/appendix_d_variational_convergence.md",
      "title": "Appendix D: Variational Perspective and Dynamical Convergence to Alignment & Regularity",
      "label": "Variational Perspective and Dynamical Convergence to Alignment & Regularity",
      "group": "Appendices",
      "number": "D",
      "hash": "67674933122b25fbaf52415611094d78f80e5fb392fad923635f22175a25351f"
    },
    {
      "id": "appendices--appendix_e_thermo_area_law",
      "file": "appendices/appendix_e_thermo_area_law.md",
      "title": "Appendix E: Thermodynamic Limits and Horizon Entropy Area Law",
      "label": "Thermodynamic Limits and Horizon Entropy Area Law",
      "group": "Appendices",
      "number": "E",
      "hash": "b5c16fa7f5d758d27fdf11e460a663e4d0fcf099664db66947ccd6c643fada55"
    },
    {
      "id": "appendices--appendix_f_aqft",
      "file": "appendices/appendix_f_aqft.md",
      "title": "Appendix F: AQFT Framework for Continuum Emergence and Locality",
      "label": "AQFT Framework for Continuum Emergence and Locality",
      "group": "Appendices",
      "number": "F",
      "hash": "d1223da661d392962fa8d03b55f1b689e6625608b23f6299dd1724ad189ff88a"
    },
    {
      "id": "appendices--appendix_g_gauge_emergence",
      "file": "appendices/appendix_g_gauge_emergence.md",
      "title": "Appendix G: Emergence of Quantum Weights and Gauge Structure",
      "label": "Emergence of Quantum Weights and Gauge Structure",
      "group": "Appendices",
      "number": "G",
      "hash": "902e178fc276bcce7cf67b683c1566a5587d99e2ad5068083876c1ee92d4e208"
    },
    {
      "id": "appendices--appendix_h_dimensions",
      "file": "appendices/appendix_h_dimensions.md",
      "title": "Appendix H: Dimensional Analysis and Emergent Scales",
      "label": "Dimensional Analysis and Emergent Scales",
      "group": "Appendices",
      "number": "H",
      "hash": "97998d32bfba2247d36845453667514d1457476b8b18add21ffc7ea78e590eb0"
    },
    {
      "id": "appendices--appendix_i_scaled_gravity",
      "file": "appendices/appendix_i_scaled_gravity.md",
      "title": "Appendix I: A PCE-Driven, Environment-Dependent Model for Emergent Gravity",
      "label": "A PCE-Driven, Environment-Dependent Model for Emergent Gravity",
      "group": "Appendices",
      "number": "I",
      "hash": "606388bceaf1f497c2528c1ea6c02199f7fb6d0f1367eece4f77acb86770ecb4"
    },
    {
      "id": "appendices--appendix_j_reflexivity_cost",
      "file": "appendices/appendix_j_reflexivity_cost.md",
      "title": "Appendix J: The Fundamental Thermodynamic Cost of Reflexivity",
      "label": "The Fundamental Thermodynamic Cost of Reflexivity",
      "group": "Appendices",
      "number": "J",
      "hash": "a05ef67c336b389dcd7537509b8ea1edcfc3da6b95ad11da2f59a6ca008d401c"
    },
    {
      "id": "appendices--appendix_k_resolving_puzzles",
      "file": "appendices/appendix_k_resolving_puzzles.md",
      "title": "Appendix K: Resolving Outstanding Puzzles in Fundamental Physics",
      "label": "Resolving Outstanding Puzzles in Fundamental Physics",
      "group": "Appendices",
      "number": "K",
      "hash": "03800166bb444110910e0956d35ba31ba684d6054dc2efbc4e4ea0facb557afa"
    },
    {
      "id": "appendices--appendix_l_cc_mechanism",
      "file": "appendices/appendix_l_cc_mechanism.md",
      "title": "Appendix L: Unified Foundation — Energy Accounting and Thermodynamic Consistency",
      "label": "Unified Foundation — Energy Accounting and Thermodynamic Consistency",
      "group": "Appendices",
      "number": "L",
      "hash": "457b04512f56396028b63b17330cbe9a4945f503489351291e6df45728cea11a"
    },
    {
      "id": "appendices--appendix_m_perspectival_quantum_dynamics",
      "file": "appendices/appendix_m_perspectival_quantum_dynamics.md",
      "title": "Appendix M: Formalism for Perspectival Quantum Dynamics",
      "label": "Formalism for Perspectival Quantum Dynamics",
      "group": "Appendices",
      "number": "M",
      "hash": "82e11a2ec3d033e76d18eb1a9d686d069608dc7dda2fe8add9b10a90ed0f86a0"
    },
    {
      "id": "appendices--appendix_n_prediction_relativity",
      "file": "appendices/appendix_n_prediction_relativity.md",
      "title": "Appendix N: Prediction Relativity and the Unified Cost of Transgression",
      "label": "Prediction Relativity and the Unified Cost of Transgression",
      "group": "Appendices",
      "number": "N",
      "hash": "b6d3350a3e02a51c5f772404c2df0f8732c02ab2571ca5f3e69a20c06c9d8486"
    },
    {
      "id": "appendices--appendix_o_arrow_of_time",
      "file": "appendices/appendix_o_arrow_of_time.md",
      "title": "Appendix O: Temporal Coherence and the Arrow of Time in the Predictive Universe",
      "label": "Temporal Coherence and the Arrow of Time in the Predictive Universe",
      "group": "Appendices",
      "number": "O",
      "hash": "ab17fdfff9f38e9bf913f03c2713fcc0e06237cca834d3ae0b37c4fd130ed477"
    },
    {
      "id": "appendices--appendix_p_philosophical_foundations",
      "file": "appendices/appendix_p_philosophical_foundations.md",
      "title": "Appendix P: Philosophical Foundations",
      "label": "Philosophical Foundations",
      "group": "Appendices",
      "number": "P",
      "hash": "b2944762dd78453213f6bc20bc23da8ce12832a5951ced049e88ddfe78e5e192"
    },
    {
      "id": "appendices--appendix_q_planck_scale",
      "file": "appendices/appendix_q_planck_scale.md",
      "title": "Appendix Q: Derivation of the Planck-MPU Scale Ratio",
      "label": "Derivation of the Planck-MPU Scale Ratio",
      "group": "Appendices",
      "number": "Q",
      "hash": "4882948008ddf3772c1ba4ab279f897fbd7257d17a54be6c2dd2f4f670c9d6b2"
    },
    {
      "id": "appendices--appendix_r_generations",
      "file": "appendices/appendix_r_generations.md",
      "title": "Appendix R: Three-Generation Structure and Fermion Mass Hierarchy",
      "label": "Three-Generation Structure and Fermion Mass Hierarchy",
      "group": "Appendices",
      "number": "R",
      "hash": "60df44909f1136df38c88e6b9fb6a4eec73dfc4fe8690abc95713a17681cc5a9"
    },
    {
      "id": "appendices--appendix_s_ccgravity",
      "file": "appendices/appendix_s_ccgravity.md",
      "title": "Appendix S: Resource Cost, Stress-Energy, and the Gravitational Self-Limitation of CC",
      "label": "Resource Cost, Stress-Energy, and the Gravitational Self-Limitation of CC",
      "group": "Appendices",
      "number": "S",
      "hash": "7818d3cbc681decc9b7d03dd97df25a898a7699d72d9c107e139786224a93744"
    },
    {
      "id": "appendices--appendix_t_electroweak_hierarchy",
      "file": "appendices/appendix_t_electroweak_hierarchy.md",
      "title": "Appendix T: Electroweak Scale, Mixing, and Higgs Quartic from Golay-Steiner Structure",
      "label": "Electroweak Scale, Mixing, and Higgs Quartic from Golay-Steiner Structure",
      "group": "Appendices",
      "number": "T",
      "hash": "0a903e17147f22f11a435b82dcff2b7e3178cd1f4c2ed2f286e236f9bfdaf79a"
    },
    {
      "id": "appendices--appendix_u_cosmological_constant",
      "file": "appendices/appendix_u_cosmological_constant.md",
      "title": "Appendix U: Vacuum-Weight and Primordial Reference Models with Golay--Steiner Compatibility",
      "label": "Vacuum-Weight and Primordial Reference Models with Golay--Steiner Compatibility",
      "group": "Appendices",
      "number": "U",
      "hash": "ad868571990f1d92016f2f75cc3c60bb2f1db4b55060c30262ba390bf3d8dfa4"
    },
    {
      "id": "appendices--appendix_v_computational_programs",
      "file": "appendices/appendix_v_computational_programs.md",
      "title": "Appendix V: Computational Programs and Numerical Consistency Checks",
      "label": "Computational Programs and Numerical Consistency Checks",
      "group": "Appendices",
      "number": "V",
      "hash": "2d7e333be1abf29360072689c808a4d920a4857644c8789096a854202a3574d7"
    },
    {
      "id": "appendices--appendix_w_alphabet_identities",
      "file": "appendices/appendix_w_alphabet_identities.md",
      "title": "Appendix W — PU’s Alphabet‑Constant Identities, Robustness, and SM Structure",
      "label": "PU’s Alphabet‑Constant Identities, Robustness, and SM Structure",
      "group": "Appendices",
      "number": "W",
      "hash": "ba739446e8ee7bc1ef34df4d85e5dacd0fc65ecb36c0d6f4f5b49a8881fcdf41"
    },
    {
      "id": "appendices--appendix_x_effective_action",
      "file": "appendices/appendix_x_effective_action.md",
      "title": "Appendix X: PU and the Effective Action",
      "label": "PU and the Effective Action",
      "group": "Appendices",
      "number": "X",
      "hash": "0b2763220016f575a609cb76bb863644ee560cf2fa30f64872fc931a249e2cc0"
    },
    {
      "id": "appendices--appendix_y_baryon_asymmetry",
      "file": "appendices/appendix_y_baryon_asymmetry.md",
      "title": "Appendix Y — Baryon Asymmetry from Predictive Anomaly Inflow",
      "label": "Baryon Asymmetry from Predictive Anomaly Inflow",
      "group": "Appendices",
      "number": "Y",
      "hash": "17a7613cf684c057f23ddf393fe4a496c1cc501b2e2a621189311548ae1cfe9b"
    },
    {
      "id": "appendices--appendix_z_fine_structure_constant",
      "file": "appendices/appendix_z_fine_structure_constant.md",
      "title": "APPENDIX Z: Certificate-Conditional Interface Ledger, Fine-Structure Candidate, and Euclidean Response-Carrier Dimension",
      "label": "Certificate-Conditional Interface Ledger, Fine-Structure Candidate, and Euclidean Response-Carrier Dimension",
      "group": "Appendices",
      "number": "Z",
      "hash": "a1805bcbc75d95ea8c8e6c118b289fa9f030f9d374e2c8e5eaf6fca6ec91f552"
    },
    {
      "id": "glossary",
      "file": "glossary.md",
      "title": "Glossary of Key Terms",
      "label": "Glossary of Key Terms",
      "group": "Reference",
      "number": "",
      "hash": "f89a1eedd81abfdbc98e3ca0e542e94e7e46aedf598bb5ba605eed37d6e2cabf"
    },
    {
      "id": "references",
      "file": "references.md",
      "title": "References",
      "label": "References",
      "group": "Reference",
      "number": "",
      "hash": "e8cf2ed4be0ff3b34df796c70a92857fc9834eb8811ffca76c7c538ee421bb38"
    },
    {
      "id": "contents",
      "file": "contents.md",
      "title": "Table of Contents",
      "label": "Table of Contents",
      "group": "Reading guides & related work",
      "number": "",
      "hash": "e688dd445b1d0e5bdf3c92c87312459eb62e269766c782f3c6e4fc257c6ce649"
    },
    {
      "id": "map",
      "file": "map.md",
      "title": "The Predictive Universe: Structural Walkthrough",
      "label": "The Predictive Universe: Structural Walkthrough",
      "group": "Reading guides & related work",
      "number": "",
      "hash": "f50bafa3256c8db00969bd51c078ef97bdd8062aa60fcc472d5241450060a5af"
    },
    {
      "id": "related--area_law_spap_qecc",
      "file": "related/area_law_spap_qecc.md",
      "title": "Conditional Holographic-Code Ansatz for the PU Horizon Area Law",
      "label": "Conditional Holographic-Code Ansatz for the PU Horizon Area Law",
      "group": "Reading guides & related work",
      "number": "",
      "hash": "4d4324531d077ce31a8ed53b781187638e96411675a2d625134f3ef85429ab60"
    },
    {
      "id": "related--comparison",
      "file": "related/comparison.md",
      "title": "Comparative Perspectives: PU in the Landscape of Fundamental Physics",
      "label": "Comparative Perspectives: PU in the Landscape of Fundamental Physics",
      "group": "Reading guides & related work",
      "number": "",
      "hash": "2dd249df085437c66ad25b45b215331b16ddf39c27f7cc1b270c01a6281465b9"
    },
    {
      "id": "related--contextual_bibliography",
      "file": "related/contextual_bibliography.md",
      "title": "Bibliography of Related Ideas",
      "label": "Bibliography of Related Ideas",
      "group": "Reading guides & related work",
      "number": "",
      "hash": "e9ff5acc35179babf6d34105b819a7bc1983e9b1f954d4ed03d79c78be6b41bd"
    },
    {
      "id": "related--lite_framework",
      "file": "related/lite_framework.md",
      "title": "LITE: Dynamic Self-Reference in Peano Arithmetic",
      "label": "LITE: Dynamic Self-Reference in Peano Arithmetic",
      "group": "Reading guides & related work",
      "number": "",
      "hash": "42c8ca9200444d8476f4004df0cc717a3a31a14e318dff68c01596205928a4f0"
    },
    {
      "id": "related--proof_life_verification_model",
      "file": "related/proof_life_verification_model.md",
      "title": "Proof-Life: A Finite Verification-Gated Toy Universe for Proof Reachability",
      "label": "Proof-Life: A Finite Verification-Gated Toy Universe for Proof Reachability",
      "group": "Reading guides & related work",
      "number": "",
      "hash": "c15e452bcffc89be71d6524d13cc833d7cfcbd862eba63eefc79b5dbfdf089b5"
    }
  ],
  "scenes": [
    {
      "key": "cogito",
      "title": "Cogito",
      "source": "Sections 1-2, 5",
      "sections": [
        "01_introduction",
        "02_foundations",
        "05_horizon_constant"
      ]
    },
    {
      "key": "becoming",
      "title": "Space of Becoming",
      "source": "Section 3",
      "sections": [
        "03_space_of_becoming"
      ]
    },
    {
      "key": "ledger",
      "title": "PPI / PCE Ledger",
      "source": "Sections 2, 6",
      "sections": [
        "02_foundations",
        "06_complexity_resources"
      ]
    },
    {
      "key": "spap",
      "title": "SPAP",
      "source": "Section 4, Appendix A",
      "sections": [
        "04_spap",
        "appendices--appendix_a_core_logic"
      ]
    },
    {
      "key": "entropy",
      "title": "Reset Ledger",
      "source": "Sections 7.5-7.6; Appendix J",
      "sections": [
        "07_minimal_predictive_unit",
        "appendices--appendix_j_reflexivity_cost"
      ]
    },
    {
      "key": "mpu",
      "title": "MPU",
      "source": "Sections 5, 7; Appendix Z",
      "sections": [
        "05_horizon_constant",
        "07_minimal_predictive_unit",
        "appendices--appendix_z_fine_structure_constant"
      ]
    },
    {
      "key": "network",
      "title": "MPU Network",
      "source": "Section 7, Appendix C",
      "sections": [
        "07_minimal_predictive_unit",
        "appendices--appendix_c_regularity_necessity"
      ]
    },
    {
      "key": "pcegeo",
      "title": "PCE Geometry",
      "source": "Appendix C",
      "sections": [
        "appendices--appendix_c_regularity_necessity"
      ]
    },
    {
      "key": "quantum",
      "title": "Quantum State",
      "source": "Section 8",
      "sections": [
        "08_quantum_emergence"
      ]
    },
    {
      "key": "spinor",
      "title": "Spinor",
      "source": "Section 8, Appendix G",
      "sections": [
        "08_quantum_emergence",
        "appendices--appendix_g_gauge_emergence"
      ]
    },
    {
      "key": "golay",
      "title": "Golay Code",
      "source": "Sections 7.6, 13.9; Appendix Z",
      "sections": [
        "07_minimal_predictive_unit",
        "13_experimental_predictions",
        "appendices--appendix_z_fine_structure_constant"
      ]
    },
    {
      "key": "dim",
      "title": "D = 4 Gate",
      "source": "Appendix Z",
      "sections": [
        "appendices--appendix_z_fine_structure_constant"
      ]
    },
    {
      "key": "gauge",
      "title": "Gauge Sectors",
      "source": "Appendix G",
      "sections": [
        "appendices--appendix_g_gauge_emergence"
      ]
    },
    {
      "key": "particles",
      "title": "Particle Defects",
      "source": "Appendices R, T, Z",
      "sections": [
        "appendices--appendix_r_generations",
        "appendices--appendix_t_electroweak_hierarchy",
        "appendices--appendix_z_fine_structure_constant"
      ]
    },
    {
      "key": "relativity",
      "title": "Relativity",
      "source": "Section 11",
      "sections": [
        "11_spacetime_emergence"
      ]
    },
    {
      "key": "gravity",
      "title": "Emergent Gravity",
      "source": "Section 12",
      "sections": [
        "12_gravity_derivation"
      ]
    },
    {
      "key": "horizon",
      "title": "Predictive Horizon",
      "source": "Appendix E",
      "sections": [
        "appendices--appendix_e_thermo_area_law"
      ]
    },
    {
      "key": "blackhole",
      "title": "Black Hole",
      "source": "Appendix K",
      "sections": [
        "appendices--appendix_k_resolving_puzzles"
      ]
    },
    {
      "key": "predictors",
      "title": "Prediction Relativity",
      "source": "Appendix N",
      "sections": [
        "appendices--appendix_n_prediction_relativity"
      ]
    },
    {
      "key": "perspectival",
      "title": "Perspectival Info",
      "source": "Appendix M",
      "sections": [
        "appendices--appendix_m_perspectival_quantum_dynamics"
      ]
    },
    {
      "key": "consciousness",
      "title": "Consciousness Com.",
      "source": "Sections 9-10, 13; Appendix L",
      "sections": [
        "09_consciousness_complexity",
        "10_statistical_influence",
        "13_experimental_predictions",
        "appendices--appendix_l_cc_mechanism"
      ]
    },
    {
      "key": "dark",
      "title": "Dark Sector",
      "source": "Appendix I",
      "sections": [
        "appendices--appendix_i_scaled_gravity"
      ]
    },
    {
      "key": "vacuum",
      "title": "False-Vacuum Weight",
      "source": "Appendix U",
      "sections": [
        "appendices--appendix_u_cosmological_constant"
      ]
    },
    {
      "key": "cascade",
      "title": "K0 Cascade",
      "source": "Sections 5, 7; Appendix Z",
      "sections": [
        "05_horizon_constant",
        "07_minimal_predictive_unit",
        "appendices--appendix_z_fine_structure_constant"
      ]
    }
  ],
  "relatedPapers": [
    {
      "id": "related--pure_s_universality--paper",
      "title": "Pure S Is Computationally Universal Under a Fixed Root-Restarted Finite Controller",
      "source": "related/pure_s_universality/paper.md",
      "file": "related/pure_s_universality/output/pdf/pure_s_universality.pdf"
    }
  ]
};
