// Generated by scripts/build-paper.cjs from the manuscript and scene catalogue.
window.PU_PAPER = {
  "sections": [
    {
      "id": "00_abstract",
      "file": "00_abstract.md",
      "title": "The Predictive Universe",
      "label": "Abstract",
      "group": "Main text",
      "number": "00",
      "hash": "67cee30eea227f860f7ed9a9e3e873fbb0bb4e7737d723db4df9a548c4119fe1"
    },
    {
      "id": "01_introduction",
      "file": "01_introduction.md",
      "title": "1. Introduction",
      "label": "Introduction",
      "group": "Main text",
      "number": "01",
      "hash": "f61772588ac19fd815ed08bad5aac48f065688600f1b64fd2500c20ea2040ee2"
    },
    {
      "id": "02_foundations",
      "file": "02_foundations.md",
      "title": "2. Foundational Principles: Prediction, Optimization, and Resources",
      "label": "Foundations",
      "group": "Main text",
      "number": "02",
      "hash": "ca3e0e3030c2d04cf94919d5ee601ef51531ee706f8a5bd2177bb1368e4a47f6"
    },
    {
      "id": "03_space_of_becoming",
      "file": "03_space_of_becoming.md",
      "title": "3. The Dynamics of Prediction and Interaction",
      "label": "Space of Becoming",
      "group": "Main text",
      "number": "03",
      "hash": "1b86e5f47cce2ac140ac6da80acb13a466823221f1762ea4da5f80bb294389ae"
    },
    {
      "id": "04_spap",
      "file": "04_spap.md",
      "title": "4. Self-Reference, Computation, and Fundamental Limits",
      "label": "SPAP",
      "group": "Main text",
      "number": "04",
      "hash": "f68d88e51507adab9fec047c52bc4ab7b65d97ebd84de13b2b53284b5dc62ab6"
    },
    {
      "id": "05_horizon_constant",
      "file": "05_horizon_constant.md",
      "title": "5. Complexity Thresholds: Operational Threshold and Horizon Constant",
      "label": "Horizon Constant",
      "group": "Main text",
      "number": "05",
      "hash": "c76ff9dabf70a761d6a771668b3accc5d7784581a1f64feb7b223b2bbd2a6138"
    },
    {
      "id": "06_complexity_resources",
      "file": "06_complexity_resources.md",
      "title": "6. Complexity, Performance, and Adaptation Dynamics",
      "label": "Complexity & Resources",
      "group": "Main text",
      "number": "06",
      "hash": "ea786fb270ace4ad82111bef3e52bb3a21ca3be193c06aaab37d086d09a42cd2"
    },
    {
      "id": "07_minimal_predictive_unit",
      "file": "07_minimal_predictive_unit.md",
      "title": "7. The Minimal Predictive Unit (MPU) Framework",
      "label": "Minimal Predictive Unit",
      "group": "Main text",
      "number": "07",
      "hash": "dd40fc136508bf453fb12afefe1b40c60c0fbe9857ddc52775df84aff7fe53ad"
    },
    {
      "id": "08_quantum_emergence",
      "file": "08_quantum_emergence.md",
      "title": "8. Emergence of Quantum Mechanical Formalism",
      "label": "Quantum Emergence",
      "group": "Main text",
      "number": "08",
      "hash": "cc583aba0f57bc2f81d8ec7a988fd82be869e3c509feb8a81c142c989e0638fb"
    },
    {
      "id": "09_consciousness_complexity",
      "file": "09_consciousness_complexity.md",
      "title": "9. Consciousness Complexity (CC): Emergent Biasing of MPU Interactions",
      "label": "Consciousness Complexity",
      "group": "Main text",
      "number": "09",
      "hash": "db461b8ef7197cffc3acf5fdd64d9a5100d089ce06b2549702cca40a06b4a891"
    },
    {
      "id": "10_statistical_influence",
      "file": "10_statistical_influence.md",
      "title": "10. Causality, Locality, and Statistical Influence",
      "label": "Statistical Influence",
      "group": "Main text",
      "number": "10",
      "hash": "f7a2d677465528e125bc3874a8954e0192cae399d0dcaa29452ba6784379f7dc"
    },
    {
      "id": "11_spacetime_emergence",
      "file": "11_spacetime_emergence.md",
      "title": "11. Emergence of Spacetime Geometry (Operational Continuum Branch)",
      "label": "Spacetime Emergence",
      "group": "Main text",
      "number": "11",
      "hash": "9b9d0c430faa84a7270a1c4452a484a4b45dc6f2a413041b974c4549ae3bcf9c"
    },
    {
      "id": "12_gravity_derivation",
      "file": "12_gravity_derivation.md",
      "title": "12. Emergence of Gravitational Dynamics from Predictive Thermodynamics",
      "label": "Gravity Derivation",
      "group": "Main text",
      "number": "12",
      "hash": "7d538c13dd70c96d26655ee26ef17c5d23b6337619c0aff59b9f5e5e078e0c1c"
    },
    {
      "id": "13_experimental_predictions",
      "file": "13_experimental_predictions.md",
      "title": "13. Experimental Predictions and Protocols",
      "label": "Experimental Predictions",
      "group": "Main text",
      "number": "13",
      "hash": "5c7cbe9f67fcccfb7094bb0e24143eb828e94cbc1c3a1a90f54ee847e282ad50"
    },
    {
      "id": "14_discussion",
      "file": "14_discussion.md",
      "title": "14. Discussion",
      "label": "Discussion",
      "group": "Main text",
      "number": "14",
      "hash": "b9e446ee5851e7feda6387a22e658ac1185cb950f26f5015d4f4ac0fb51619e4"
    },
    {
      "id": "15_conclusion",
      "file": "15_conclusion.md",
      "title": "15. Conclusion",
      "label": "Conclusion",
      "group": "Main text",
      "number": "15",
      "hash": "e577057aa9d7eec152d76c43480c71c4d549a6250669504e0487672fd096e64f"
    },
    {
      "id": "appendices--appendix_a_core_logic",
      "file": "appendices/appendix_a_core_logic.md",
      "title": "Appendix A: Core Logic, Computation Limits, and Property R",
      "label": "Core Logic, Computation Limits, and Property R",
      "group": "Appendices",
      "number": "A",
      "hash": "e1737197e9b96ed0410cfcc769a643c6c802c9122c68b566b36362e46e489af8"
    },
    {
      "id": "appendices--appendix_b_complexity_costs",
      "file": "appendices/appendix_b_complexity_costs.md",
      "title": "Appendix B: Operational Complexity, Costs, and Stress–Energy Tensor Construction",
      "label": "Operational Complexity, Costs, and Stress–Energy Tensor Construction",
      "group": "Appendices",
      "number": "B",
      "hash": "c4c3a8fef5ba57db9bcee289550191b1aaa7773cbb9939160a6e00e40811b996"
    },
    {
      "id": "appendices--appendix_c_regularity_necessity",
      "file": "appendices/appendix_c_regularity_necessity.md",
      "title": "Appendix C: Necessity of Geometric Regularity",
      "label": "Necessity of Geometric Regularity",
      "group": "Appendices",
      "number": "C",
      "hash": "af7570bd55dc9f022bc7823613d794af2a6e0a6606b02ef6edb38ac844d78ace"
    },
    {
      "id": "appendices--appendix_d_variational_convergence",
      "file": "appendices/appendix_d_variational_convergence.md",
      "title": "Appendix D: Variational Perspective and Dynamical Convergence to Alignment & Regularity",
      "label": "Variational Perspective and Dynamical Convergence to Alignment & Regularity",
      "group": "Appendices",
      "number": "D",
      "hash": "0333f50da8207bca92c007d6142a3323c72f3731784ec09e246e0a35943f6774"
    },
    {
      "id": "appendices--appendix_e_thermo_area_law",
      "file": "appendices/appendix_e_thermo_area_law.md",
      "title": "Appendix E: Thermodynamic Limits and Horizon Entropy Area Law",
      "label": "Thermodynamic Limits and Horizon Entropy Area Law",
      "group": "Appendices",
      "number": "E",
      "hash": "ac72a6c43c337f936e0c511680e8f71f86751bf543222afa5579e5ebfbd404a2"
    },
    {
      "id": "appendices--appendix_f_aqft",
      "file": "appendices/appendix_f_aqft.md",
      "title": "Appendix F: AQFT Framework for Continuum Emergence and Locality",
      "label": "AQFT Framework for Continuum Emergence and Locality",
      "group": "Appendices",
      "number": "F",
      "hash": "9775ead7b0c62e6e7f41b345beec149d1f7dc6665fff1c3e852968fd2c589ec4"
    },
    {
      "id": "appendices--appendix_g_gauge_emergence",
      "file": "appendices/appendix_g_gauge_emergence.md",
      "title": "Appendix G: Emergence of Quantum Weights and Gauge Structure",
      "label": "Emergence of Quantum Weights and Gauge Structure",
      "group": "Appendices",
      "number": "G",
      "hash": "75d4ccf3f9a8b2e970b3f14606c5d87fbaad3d5edca746e1d9687e1b7e5e2aa6"
    },
    {
      "id": "appendices--appendix_h_dimensions",
      "file": "appendices/appendix_h_dimensions.md",
      "title": "Appendix H: Dimensional Analysis and Emergent Scales",
      "label": "Dimensional Analysis and Emergent Scales",
      "group": "Appendices",
      "number": "H",
      "hash": "08410ace45d1f7c948f02bf26769dba0fe3b3c04f93a201b15e6cde1c1f04f2f"
    },
    {
      "id": "appendices--appendix_i_scaled_gravity",
      "file": "appendices/appendix_i_scaled_gravity.md",
      "title": "Appendix I: A PCE-Driven, Environment-Dependent Model for Emergent Gravity",
      "label": "A PCE-Driven, Environment-Dependent Model for Emergent Gravity",
      "group": "Appendices",
      "number": "I",
      "hash": "a0b9a3fbdbd2932dbc817a1c6c8a07f4cdf24423dfd384bd7196febb85ad5db9"
    },
    {
      "id": "appendices--appendix_j_reflexivity_cost",
      "file": "appendices/appendix_j_reflexivity_cost.md",
      "title": "Appendix J: The Fundamental Thermodynamic Cost of Reflexivity",
      "label": "The Fundamental Thermodynamic Cost of Reflexivity",
      "group": "Appendices",
      "number": "J",
      "hash": "94c464f32186027debc56c2db0e411ed1e14e32c032fe593dd146279c6dc5348"
    },
    {
      "id": "appendices--appendix_k_resolving_puzzles",
      "file": "appendices/appendix_k_resolving_puzzles.md",
      "title": "Appendix K: Resolving Outstanding Puzzles in Fundamental Physics",
      "label": "Resolving Outstanding Puzzles in Fundamental Physics",
      "group": "Appendices",
      "number": "K",
      "hash": "a8c17e52a9d41530d09aded80967b9147136877394e5d3377a0af6bc4e5f2b7a"
    },
    {
      "id": "appendices--appendix_l_cc_mechanism",
      "file": "appendices/appendix_l_cc_mechanism.md",
      "title": "Appendix L: Unified Foundation — Energy Accounting and Thermodynamic Consistency",
      "label": "Unified Foundation — Energy Accounting and Thermodynamic Consistency",
      "group": "Appendices",
      "number": "L",
      "hash": "9bf7cb6c48d8432935991ce8e0375e29d6ea70fb79d12105a5d10ec6ecf133b3"
    },
    {
      "id": "appendices--appendix_m_perspectival_quantum_dynamics",
      "file": "appendices/appendix_m_perspectival_quantum_dynamics.md",
      "title": "Appendix M: Formalism for Perspectival Quantum Dynamics",
      "label": "Formalism for Perspectival Quantum Dynamics",
      "group": "Appendices",
      "number": "M",
      "hash": "b766834b99caf6b282b6775dbc5e95cd6dcc686c63c2bd8cde037aaacaa45be9"
    },
    {
      "id": "appendices--appendix_n_prediction_relativity",
      "file": "appendices/appendix_n_prediction_relativity.md",
      "title": "Appendix N: Prediction Relativity and the Unified Cost of Transgression",
      "label": "Prediction Relativity and the Unified Cost of Transgression",
      "group": "Appendices",
      "number": "N",
      "hash": "bf16931ea19182406355aba527e883fbe3fec8bdc35db1aabde31cf47ce6244c"
    },
    {
      "id": "appendices--appendix_o_arrow_of_time",
      "file": "appendices/appendix_o_arrow_of_time.md",
      "title": "Appendix O: Temporal Coherence and the Arrow of Time in the Predictive Universe",
      "label": "Temporal Coherence and the Arrow of Time in the Predictive Universe",
      "group": "Appendices",
      "number": "O",
      "hash": "5d31ec6c28945076910161858ee35653472d5dc579d1742b435a281897f8c5ce"
    },
    {
      "id": "appendices--appendix_p_philosophical_foundations",
      "file": "appendices/appendix_p_philosophical_foundations.md",
      "title": "Appendix P: Philosophical Foundations",
      "label": "Philosophical Foundations",
      "group": "Appendices",
      "number": "P",
      "hash": "0ca9b315ed0c0ba26e2bbe4cfacfc48e14c2be87e84bcb5a2293bd08a1c2b2e0"
    },
    {
      "id": "appendices--appendix_q_planck_scale",
      "file": "appendices/appendix_q_planck_scale.md",
      "title": "Appendix Q: Derivation of the Planck-MPU Scale Ratio",
      "label": "Derivation of the Planck-MPU Scale Ratio",
      "group": "Appendices",
      "number": "Q",
      "hash": "a5715b48679d277b4298a4e50e8b71f607545c3047752dc967d017a8dc968428"
    },
    {
      "id": "appendices--appendix_r_generations",
      "file": "appendices/appendix_r_generations.md",
      "title": "Appendix R: Three-Generation Structure and Fermion Mass Hierarchy",
      "label": "Three-Generation Structure and Fermion Mass Hierarchy",
      "group": "Appendices",
      "number": "R",
      "hash": "0ce271ce1e8c13b5705436ab5e30339dbd83bcebe1ecfb27c15af7c96e12c099"
    },
    {
      "id": "appendices--appendix_s_ccgravity",
      "file": "appendices/appendix_s_ccgravity.md",
      "title": "Appendix S: Resource Cost, Stress-Energy, and the Gravitational Self-Limitation of CC",
      "label": "Resource Cost, Stress-Energy, and the Gravitational Self-Limitation of CC",
      "group": "Appendices",
      "number": "S",
      "hash": "c4057538da92b3484860952ff41b5f1c3d5eeb3e632a31498db6d64d30b12eb8"
    },
    {
      "id": "appendices--appendix_t_electroweak_hierarchy",
      "file": "appendices/appendix_t_electroweak_hierarchy.md",
      "title": "Appendix T: Electroweak Scale, Mixing, and Higgs Quartic from Golay-Steiner Structure",
      "label": "Electroweak Scale, Mixing, and Higgs Quartic from Golay-Steiner Structure",
      "group": "Appendices",
      "number": "T",
      "hash": "c8c5bc7b4d2ed1b596b07ba25f7bf252788734cf56ee3141b74caf8dc9fe88a5"
    },
    {
      "id": "appendices--appendix_u_cosmological_constant",
      "file": "appendices/appendix_u_cosmological_constant.md",
      "title": "Appendix U: Vacuum-Weight and Primordial Reference Models with Golay--Steiner Compatibility",
      "label": "Vacuum-Weight and Primordial Reference Models with Golay--Steiner Compatibility",
      "group": "Appendices",
      "number": "U",
      "hash": "1177e39656b170c28a1799da801d093e583097b505e6c467e83035c0f88fd938"
    },
    {
      "id": "appendices--appendix_v_computational_programs",
      "file": "appendices/appendix_v_computational_programs.md",
      "title": "Appendix V: Computational Programs and Numerical Consistency Checks",
      "label": "Computational Programs and Numerical Consistency Checks",
      "group": "Appendices",
      "number": "V",
      "hash": "4cf9f7164261ebe1d8c5b893f39abc65679b97358054c5389cfa9aadb055c230"
    },
    {
      "id": "appendices--appendix_w_alphabet_identities",
      "file": "appendices/appendix_w_alphabet_identities.md",
      "title": "Appendix W — PU’s Alphabet‑Constant Identities, Robustness, and SM Structure",
      "label": "PU’s Alphabet‑Constant Identities, Robustness, and SM Structure",
      "group": "Appendices",
      "number": "W",
      "hash": "ccd7a1dbcc085939483b206e3a45a71c36421cbb4e28bba2f08111a12b093ebc"
    },
    {
      "id": "appendices--appendix_x_effective_action",
      "file": "appendices/appendix_x_effective_action.md",
      "title": "Appendix X: PU and the Effective Action",
      "label": "PU and the Effective Action",
      "group": "Appendices",
      "number": "X",
      "hash": "babb056fd785c15be86271e7b8ce9c5d4cb7692c3255211909a993f88efa9367"
    },
    {
      "id": "appendices--appendix_y_baryon_asymmetry",
      "file": "appendices/appendix_y_baryon_asymmetry.md",
      "title": "Appendix Y — Baryon Asymmetry from Predictive Anomaly Inflow",
      "label": "Baryon Asymmetry from Predictive Anomaly Inflow",
      "group": "Appendices",
      "number": "Y",
      "hash": "9e2fdaf23c61bc68c17a2ba7aca094dcfd4828a9d5311c0a2fadffccd83b1b7d"
    },
    {
      "id": "appendices--appendix_z_fine_structure_constant",
      "file": "appendices/appendix_z_fine_structure_constant.md",
      "title": "APPENDIX Z: Certificate-Conditional Interface Ledger, Fine-Structure Candidate, and Euclidean Response-Carrier Dimension",
      "label": "Certificate-Conditional Interface Ledger, Fine-Structure Candidate, and Euclidean Response-Carrier Dimension",
      "group": "Appendices",
      "number": "Z",
      "hash": "a539d083a04c0f92d25beeadd0f399d3f0dbe50d497c508552ac3ac369cc84b8"
    },
    {
      "id": "glossary",
      "file": "glossary.md",
      "title": "Glossary of Key Terms",
      "label": "Glossary of Key Terms",
      "group": "Reference",
      "number": "",
      "hash": "4f3fa5e02d53c6ec7affc21a60f0a0888b095851f2b82d45d47564d88c2b42ca"
    },
    {
      "id": "references",
      "file": "references.md",
      "title": "References",
      "label": "References",
      "group": "Reference",
      "number": "",
      "hash": "d718ac90d9211bfa2e2dd736995353c4772bc08f92014135754385cf2ac8eef3"
    },
    {
      "id": "contents",
      "file": "contents.md",
      "title": "Table of Contents",
      "label": "Table of Contents",
      "group": "Reading guides & related work",
      "number": "",
      "hash": "b36534cfbb7b9c58c7af23b16437ac71ce5da2b64d900a0165c79f43ae020db2"
    },
    {
      "id": "map",
      "file": "map.md",
      "title": "The Predictive Universe: Structural Walkthrough",
      "label": "The Predictive Universe: Structural Walkthrough",
      "group": "Reading guides & related work",
      "number": "",
      "hash": "a35e4925efd245fe16eb0780fdc58551c3ccccda349ff1414a8dc52dfacd9284"
    },
    {
      "id": "related--area_law_spap_qecc",
      "file": "related/area_law_spap_qecc.md",
      "title": "Conditional Holographic-Code Ansatz for the PU Horizon Area Law",
      "label": "Conditional Holographic-Code Ansatz for the PU Horizon Area Law",
      "group": "Reading guides & related work",
      "number": "",
      "hash": "8261de5bd56fbedc2196ff098a2b33cd1e49cf15afc70f9225a2b29339207e18"
    },
    {
      "id": "related--comparison",
      "file": "related/comparison.md",
      "title": "Comparative Perspectives: PU in the Landscape of Fundamental Physics",
      "label": "Comparative Perspectives: PU in the Landscape of Fundamental Physics",
      "group": "Reading guides & related work",
      "number": "",
      "hash": "73df07f0ecd7c9efc62c1375cccba7079b389b59374796af67dddf40cdd9e0b6"
    },
    {
      "id": "related--contextual_bibliography",
      "file": "related/contextual_bibliography.md",
      "title": "Bibliography of Related Ideas",
      "label": "Bibliography of Related Ideas",
      "group": "Reading guides & related work",
      "number": "",
      "hash": "cd837bd580e43b39b6586925dd52413e3c11db2bddebf1bef91c1f1bb4b73a7c"
    },
    {
      "id": "related--lite_framework",
      "file": "related/lite_framework.md",
      "title": "LITE: Dynamic Self-Reference in Peano Arithmetic",
      "label": "LITE: Dynamic Self-Reference in Peano Arithmetic",
      "group": "Reading guides & related work",
      "number": "",
      "hash": "3db604605c357c4c615f4a885ce0e469c0dbec94d16c9e71074da4518fba5e9b"
    },
    {
      "id": "related--proof_life_verification_model",
      "file": "related/proof_life_verification_model.md",
      "title": "Proof-Life: A Finite Verification-Gated Toy Universe for Proof Reachability",
      "label": "Proof-Life: A Finite Verification-Gated Toy Universe for Proof Reachability",
      "group": "Reading guides & related work",
      "number": "",
      "hash": "e1660d90e6578764d23a6a337d291409350c049cd67ebc6bca6a52d22c4ecbd8"
    }
  ],
  "scenes": [
    {
      "key": "cogito",
      "title": "Cogito",
      "source": "Sections 1-2, 5",
      "sections": [
        "01_introduction",
        "02_foundations",
        "05_horizon_constant"
      ]
    },
    {
      "key": "becoming",
      "title": "Space of Becoming",
      "source": "Section 3",
      "sections": [
        "03_space_of_becoming"
      ]
    },
    {
      "key": "ledger",
      "title": "PPI / PCE Ledger",
      "source": "Sections 2, 6",
      "sections": [
        "02_foundations",
        "06_complexity_resources"
      ]
    },
    {
      "key": "spap",
      "title": "SPAP",
      "source": "Section 4, Appendix A",
      "sections": [
        "04_spap",
        "appendices--appendix_a_core_logic"
      ]
    },
    {
      "key": "entropy",
      "title": "Reset Ledger",
      "source": "Sections 7.5-7.6; Appendix J",
      "sections": [
        "07_minimal_predictive_unit",
        "appendices--appendix_j_reflexivity_cost"
      ]
    },
    {
      "key": "mpu",
      "title": "MPU",
      "source": "Sections 5, 7; Appendix Z",
      "sections": [
        "05_horizon_constant",
        "07_minimal_predictive_unit",
        "appendices--appendix_z_fine_structure_constant"
      ]
    },
    {
      "key": "network",
      "title": "MPU Network",
      "source": "Section 7, Appendix C",
      "sections": [
        "07_minimal_predictive_unit",
        "appendices--appendix_c_regularity_necessity"
      ]
    },
    {
      "key": "pcegeo",
      "title": "PCE Geometry",
      "source": "Appendix C",
      "sections": [
        "appendices--appendix_c_regularity_necessity"
      ]
    },
    {
      "key": "quantum",
      "title": "Quantum State",
      "source": "Section 8",
      "sections": [
        "08_quantum_emergence"
      ]
    },
    {
      "key": "spinor",
      "title": "Spinor",
      "source": "Section 8, Appendix G",
      "sections": [
        "08_quantum_emergence",
        "appendices--appendix_g_gauge_emergence"
      ]
    },
    {
      "key": "golay",
      "title": "Golay Code",
      "source": "Sections 7.6, 13.9; Appendix Z",
      "sections": [
        "07_minimal_predictive_unit",
        "13_experimental_predictions",
        "appendices--appendix_z_fine_structure_constant"
      ]
    },
    {
      "key": "dim",
      "title": "D = 4 Gate",
      "source": "Appendix Z",
      "sections": [
        "appendices--appendix_z_fine_structure_constant"
      ]
    },
    {
      "key": "gauge",
      "title": "Gauge Sectors",
      "source": "Appendix G",
      "sections": [
        "appendices--appendix_g_gauge_emergence"
      ]
    },
    {
      "key": "particles",
      "title": "Particle Defects",
      "source": "Appendices R, T, Z",
      "sections": [
        "appendices--appendix_r_generations",
        "appendices--appendix_t_electroweak_hierarchy",
        "appendices--appendix_z_fine_structure_constant"
      ]
    },
    {
      "key": "relativity",
      "title": "Relativity",
      "source": "Section 11",
      "sections": [
        "11_spacetime_emergence"
      ]
    },
    {
      "key": "gravity",
      "title": "Emergent Gravity",
      "source": "Section 12",
      "sections": [
        "12_gravity_derivation"
      ]
    },
    {
      "key": "horizon",
      "title": "Predictive Horizon",
      "source": "Appendix E",
      "sections": [
        "appendices--appendix_e_thermo_area_law"
      ]
    },
    {
      "key": "blackhole",
      "title": "Black Hole",
      "source": "Appendix K",
      "sections": [
        "appendices--appendix_k_resolving_puzzles"
      ]
    },
    {
      "key": "predictors",
      "title": "Prediction Relativity",
      "source": "Appendix N",
      "sections": [
        "appendices--appendix_n_prediction_relativity"
      ]
    },
    {
      "key": "perspectival",
      "title": "Perspectival Info",
      "source": "Appendix M",
      "sections": [
        "appendices--appendix_m_perspectival_quantum_dynamics"
      ]
    },
    {
      "key": "consciousness",
      "title": "Consciousness Com.",
      "source": "Sections 9-10, 13; Appendix L",
      "sections": [
        "09_consciousness_complexity",
        "10_statistical_influence",
        "13_experimental_predictions",
        "appendices--appendix_l_cc_mechanism"
      ]
    },
    {
      "key": "dark",
      "title": "Dark Sector",
      "source": "Appendix I",
      "sections": [
        "appendices--appendix_i_scaled_gravity"
      ]
    },
    {
      "key": "vacuum",
      "title": "False-Vacuum Weight",
      "source": "Appendix U",
      "sections": [
        "appendices--appendix_u_cosmological_constant"
      ]
    },
    {
      "key": "cascade",
      "title": "K0 Cascade",
      "source": "Sections 5, 7; Appendix Z",
      "sections": [
        "05_horizon_constant",
        "07_minimal_predictive_unit",
        "appendices--appendix_z_fine_structure_constant"
      ]
    }
  ],
  "relatedPapers": [
    {
      "id": "related--pure_s_universality--paper",
      "title": "Pure S Is Computationally Universal Under a Fixed Root-Restarted Finite Controller",
      "source": "related/pure_s_universality/paper.md",
      "file": "related/pure_s_universality/output/pdf/pure_s_universality.pdf"
    }
  ]
};
