// Generated by scripts/build-paper.cjs from the manuscript and scene catalogue.
window.PU_PAPER = {
  "sections": [
    {
      "id": "00_abstract",
      "file": "00_abstract.md",
      "title": "The Predictive Universe",
      "label": "Abstract",
      "group": "Main text",
      "number": "00",
      "hash": "cf9e7cb6e5685fe4a23de6c5be1286967a5536b3294cd345b1f9f152d062f050"
    },
    {
      "id": "01_introduction",
      "file": "01_introduction.md",
      "title": "1. Introduction",
      "label": "Introduction",
      "group": "Main text",
      "number": "01",
      "hash": "adc67931449490afb82de1bfc5d476368bb15e2378575e75295db05dac43d7ca"
    },
    {
      "id": "02_foundations",
      "file": "02_foundations.md",
      "title": "2. Foundational Principles: Prediction, Optimization, and Resources",
      "label": "Foundations",
      "group": "Main text",
      "number": "02",
      "hash": "05854d9dcb5aa8904e0554067f70dace8f1b07b700ee7bf0bb46eded97674c7e"
    },
    {
      "id": "03_space_of_becoming",
      "file": "03_space_of_becoming.md",
      "title": "3. The Dynamics of Prediction and Interaction",
      "label": "Space of Becoming",
      "group": "Main text",
      "number": "03",
      "hash": "d4918eff2be240337bf4955fae2da1204953e789b8b5334ee79a0eb29a4067b5"
    },
    {
      "id": "04_spap",
      "file": "04_spap.md",
      "title": "4. Self-Reference, Computation, and Fundamental Limits",
      "label": "SPAP",
      "group": "Main text",
      "number": "04",
      "hash": "120846897e931fba03608848543b752077583c88026e2ccf04d5eba9348db7f2"
    },
    {
      "id": "05_horizon_constant",
      "file": "05_horizon_constant.md",
      "title": "5. Complexity Thresholds: Operational Threshold and Horizon Constant",
      "label": "Horizon Constant",
      "group": "Main text",
      "number": "05",
      "hash": "34a64756d7d9f54cd53b7e2e411945b96235c0c631fa90afa2388e9956e30993"
    },
    {
      "id": "06_complexity_resources",
      "file": "06_complexity_resources.md",
      "title": "6. Complexity, Performance, and Adaptation Dynamics",
      "label": "Complexity & Resources",
      "group": "Main text",
      "number": "06",
      "hash": "cc90d6d5ecddbae437cfa041d1687e06c8fa8b1af6eda182ef6c1614df13e705"
    },
    {
      "id": "07_minimal_predictive_unit",
      "file": "07_minimal_predictive_unit.md",
      "title": "7. The Minimal Predictive Unit (MPU) Framework",
      "label": "Minimal Predictive Unit",
      "group": "Main text",
      "number": "07",
      "hash": "f7a7b1d7b3e10754ef42703da39bc3603d3f65acafa5a78fd1037b04d4ec77b4"
    },
    {
      "id": "08_quantum_emergence",
      "file": "08_quantum_emergence.md",
      "title": "8. Emergence of Quantum Mechanical Formalism",
      "label": "Quantum Emergence",
      "group": "Main text",
      "number": "08",
      "hash": "13392369407b2d1e9575b59c6e93d892accb9ff7ae9b4c240834a9472f569659"
    },
    {
      "id": "09_consciousness_complexity",
      "file": "09_consciousness_complexity.md",
      "title": "9. Consciousness Complexity (CC): Emergent Biasing of MPU Interactions",
      "label": "Consciousness Complexity",
      "group": "Main text",
      "number": "09",
      "hash": "85e29a2c76b3fad404fe798198c3f01fdf2636f733f17acf4fb2db645c48af16"
    },
    {
      "id": "10_statistical_influence",
      "file": "10_statistical_influence.md",
      "title": "10. Causality, Locality, and Statistical Influence",
      "label": "Statistical Influence",
      "group": "Main text",
      "number": "10",
      "hash": "a2ba6cbddd2ffa8e9cf3bae10c65b392a383a0020d492671eae7c2657d6874a8"
    },
    {
      "id": "11_spacetime_emergence",
      "file": "11_spacetime_emergence.md",
      "title": "11. Emergence of Spacetime Geometry (Operational Continuum Branch)",
      "label": "Spacetime Emergence",
      "group": "Main text",
      "number": "11",
      "hash": "c50eadd7740efcca77beeeb0665d2ba574a2b3e1c73eecfdc5cc5c176cb98154"
    },
    {
      "id": "12_gravity_derivation",
      "file": "12_gravity_derivation.md",
      "title": "12. Emergence of Gravitational Dynamics from Predictive Thermodynamics",
      "label": "Gravity Derivation",
      "group": "Main text",
      "number": "12",
      "hash": "a3652a5929e5ff336cd624bde6099abb3b401fa15d890d6975e2deb9ef6ce863"
    },
    {
      "id": "13_experimental_predictions",
      "file": "13_experimental_predictions.md",
      "title": "13. Experimental Predictions and Protocols",
      "label": "Experimental Predictions",
      "group": "Main text",
      "number": "13",
      "hash": "c4fe69feb59fc296d541f27f51951b690bbaf23067f481605e7482646036cd3c"
    },
    {
      "id": "14_discussion",
      "file": "14_discussion.md",
      "title": "14. Discussion",
      "label": "Discussion",
      "group": "Main text",
      "number": "14",
      "hash": "42f59117cd4361d17959994c1a484dd30d0b2f3575502bb07b18572263317860"
    },
    {
      "id": "15_conclusion",
      "file": "15_conclusion.md",
      "title": "15. Conclusion",
      "label": "Conclusion",
      "group": "Main text",
      "number": "15",
      "hash": "2ef4ed6b3b717f4e8386175de6d6bc89e26af75e3bda894d9e67e84978873a83"
    },
    {
      "id": "appendices--appendix_a_core_logic",
      "file": "appendices/appendix_a_core_logic.md",
      "title": "Appendix A: Core Logic, Computation Limits, and Property R",
      "label": "Core Logic, Computation Limits, and Property R",
      "group": "Appendices",
      "number": "A",
      "hash": "5abe9738f3f841e767940bb66bd8f9c9253be5314c8752e014d795598bb2c9be"
    },
    {
      "id": "appendices--appendix_b_complexity_costs",
      "file": "appendices/appendix_b_complexity_costs.md",
      "title": "Appendix B: Operational Complexity, Costs, and Stress–Energy Tensor Construction",
      "label": "Operational Complexity, Costs, and Stress–Energy Tensor Construction",
      "group": "Appendices",
      "number": "B",
      "hash": "4502877bfb95a5b29476c44aa15e8d429763a6a4278c459cc72fb2ea44e3ecd7"
    },
    {
      "id": "appendices--appendix_c_regularity_necessity",
      "file": "appendices/appendix_c_regularity_necessity.md",
      "title": "Appendix C: Necessity of Geometric Regularity",
      "label": "Necessity of Geometric Regularity",
      "group": "Appendices",
      "number": "C",
      "hash": "6082933ed16092a47af47e4956a6269f6911c993f624f8b0a5b9fd2541833482"
    },
    {
      "id": "appendices--appendix_d_variational_convergence",
      "file": "appendices/appendix_d_variational_convergence.md",
      "title": "Appendix D: Variational Perspective and Dynamical Convergence to Alignment & Regularity",
      "label": "Variational Perspective and Dynamical Convergence to Alignment & Regularity",
      "group": "Appendices",
      "number": "D",
      "hash": "8722889dfa48a502bcc7ce5b5d9a5cc223482e96475d5ac1fdad0d1f41e9dbf9"
    },
    {
      "id": "appendices--appendix_e_thermo_area_law",
      "file": "appendices/appendix_e_thermo_area_law.md",
      "title": "Appendix E: Thermodynamic Limits and Horizon Entropy Area Law",
      "label": "Thermodynamic Limits and Horizon Entropy Area Law",
      "group": "Appendices",
      "number": "E",
      "hash": "92440308e27798e0e899bf88e103d98e7136f394f295a43e3d03403d9fbae1c1"
    },
    {
      "id": "appendices--appendix_f_aqft",
      "file": "appendices/appendix_f_aqft.md",
      "title": "Appendix F: AQFT Framework for Continuum Emergence and Locality",
      "label": "AQFT Framework for Continuum Emergence and Locality",
      "group": "Appendices",
      "number": "F",
      "hash": "4a6c73a3b930c3114e9f90e8f7af5f251c6c500e2f2280d0e526cc32bfdd627e"
    },
    {
      "id": "appendices--appendix_g_gauge_emergence",
      "file": "appendices/appendix_g_gauge_emergence.md",
      "title": "Appendix G: Emergence of Quantum Weights and Gauge Structure",
      "label": "Emergence of Quantum Weights and Gauge Structure",
      "group": "Appendices",
      "number": "G",
      "hash": "bbb6617aec98c0b656e723cdc58dd605d128108936d05bd804ad85b1a44f5f87"
    },
    {
      "id": "appendices--appendix_h_dimensions",
      "file": "appendices/appendix_h_dimensions.md",
      "title": "Appendix H: Dimensional Analysis and Emergent Scales",
      "label": "Dimensional Analysis and Emergent Scales",
      "group": "Appendices",
      "number": "H",
      "hash": "18740ba292f961d137f842bb4d6dfbbaad266d2ff72c98a9e42d7d8b3611563a"
    },
    {
      "id": "appendices--appendix_i_scaled_gravity",
      "file": "appendices/appendix_i_scaled_gravity.md",
      "title": "Appendix I: A PCE-Driven, Environment-Dependent Model for Emergent Gravity",
      "label": "A PCE-Driven, Environment-Dependent Model for Emergent Gravity",
      "group": "Appendices",
      "number": "I",
      "hash": "413cb2cd5052ddb2760e0da81a60f2275d425b3d60327dbaaff356ad724cac36"
    },
    {
      "id": "appendices--appendix_j_reflexivity_cost",
      "file": "appendices/appendix_j_reflexivity_cost.md",
      "title": "Appendix J: The Fundamental Thermodynamic Cost of Reflexivity",
      "label": "The Fundamental Thermodynamic Cost of Reflexivity",
      "group": "Appendices",
      "number": "J",
      "hash": "15e693ef96da2b4b5e8d15074a00db520cd73683b3bc7f037a2026270f4c6dbe"
    },
    {
      "id": "appendices--appendix_k_resolving_puzzles",
      "file": "appendices/appendix_k_resolving_puzzles.md",
      "title": "Appendix K: Resolving Outstanding Puzzles in Fundamental Physics",
      "label": "Resolving Outstanding Puzzles in Fundamental Physics",
      "group": "Appendices",
      "number": "K",
      "hash": "278e9e25c49e6f0e9a6aaa0c029e52a3ae1e13dfbe4c3a7becd08f2cc69b1621"
    },
    {
      "id": "appendices--appendix_l_cc_mechanism",
      "file": "appendices/appendix_l_cc_mechanism.md",
      "title": "Appendix L: Unified Foundation — Energy Accounting and Thermodynamic Consistency",
      "label": "Unified Foundation — Energy Accounting and Thermodynamic Consistency",
      "group": "Appendices",
      "number": "L",
      "hash": "3ed3416914a2a44c33eaa57a047bfa36f9433ed73e2beeabfe666627ca49dd91"
    },
    {
      "id": "appendices--appendix_m_perspectival_quantum_dynamics",
      "file": "appendices/appendix_m_perspectival_quantum_dynamics.md",
      "title": "Appendix M: Formalism for Perspectival Quantum Dynamics",
      "label": "Formalism for Perspectival Quantum Dynamics",
      "group": "Appendices",
      "number": "M",
      "hash": "c1b16987001f6a32aea846b802054d7e3012d9920e1f99b7ddd3fca2ca10d65f"
    },
    {
      "id": "appendices--appendix_n_prediction_relativity",
      "file": "appendices/appendix_n_prediction_relativity.md",
      "title": "Appendix N: Prediction Relativity and the Unified Cost of Transgression",
      "label": "Prediction Relativity and the Unified Cost of Transgression",
      "group": "Appendices",
      "number": "N",
      "hash": "36bbd44990f9121902976cecff8a21db11166ad53c6eafb23a5defa79ffd0cf7"
    },
    {
      "id": "appendices--appendix_o_arrow_of_time",
      "file": "appendices/appendix_o_arrow_of_time.md",
      "title": "Appendix O: Temporal Coherence and the Arrow of Time in the Predictive Universe",
      "label": "Temporal Coherence and the Arrow of Time in the Predictive Universe",
      "group": "Appendices",
      "number": "O",
      "hash": "a49e78ef5180818ea448a41099cc61ab5bb99504ff998d4c476bf2f63f4fecfd"
    },
    {
      "id": "appendices--appendix_p_philosophical_foundations",
      "file": "appendices/appendix_p_philosophical_foundations.md",
      "title": "Appendix P: Philosophical Foundations",
      "label": "Philosophical Foundations",
      "group": "Appendices",
      "number": "P",
      "hash": "d633dd936ab3ffde6a1c10a1e9350e33c582b8581de8a4f20a767e787d0075d4"
    },
    {
      "id": "appendices--appendix_q_planck_scale",
      "file": "appendices/appendix_q_planck_scale.md",
      "title": "Appendix Q: Derivation of the Planck-MPU Scale Ratio",
      "label": "Derivation of the Planck-MPU Scale Ratio",
      "group": "Appendices",
      "number": "Q",
      "hash": "d34c16fca7382c51773175e484fd09f366aba553222ee44a9e89c13d0e0562ec"
    },
    {
      "id": "appendices--appendix_r_generations",
      "file": "appendices/appendix_r_generations.md",
      "title": "Appendix R: Three-Generation Structure and Fermion Mass Hierarchy",
      "label": "Three-Generation Structure and Fermion Mass Hierarchy",
      "group": "Appendices",
      "number": "R",
      "hash": "ef05fa66eb2a8e7085d307e6a22606704d62f26ee0b75a30d8d77c1dcb4e9d9c"
    },
    {
      "id": "appendices--appendix_s_ccgravity",
      "file": "appendices/appendix_s_ccgravity.md",
      "title": "Appendix S: Resource Cost, Stress-Energy, and the Gravitational Self-Limitation of CC",
      "label": "Resource Cost, Stress-Energy, and the Gravitational Self-Limitation of CC",
      "group": "Appendices",
      "number": "S",
      "hash": "e66959ef65f1482fbb34e895bc5b974d43d8598cc324e7dbb22a293e65e0a5f8"
    },
    {
      "id": "appendices--appendix_t_electroweak_hierarchy",
      "file": "appendices/appendix_t_electroweak_hierarchy.md",
      "title": "Appendix T: Electroweak Scale, Mixing, and Higgs Quartic from Golay-Steiner Structure",
      "label": "Electroweak Scale, Mixing, and Higgs Quartic from Golay-Steiner Structure",
      "group": "Appendices",
      "number": "T",
      "hash": "681d1f549df3a2d285795fed9bdcee67ee6b021b829bdab738857395e9143deb"
    },
    {
      "id": "appendices--appendix_u_cosmological_constant",
      "file": "appendices/appendix_u_cosmological_constant.md",
      "title": "Appendix U: Vacuum-Weight and Primordial Reference Models with Golay--Steiner Compatibility",
      "label": "Vacuum-Weight and Primordial Reference Models with Golay--Steiner Compatibility",
      "group": "Appendices",
      "number": "U",
      "hash": "9f7216be92053c8c598b884914342580dab6426fc52ac5bd1cc2ae2f44e36756"
    },
    {
      "id": "appendices--appendix_v_computational_programs",
      "file": "appendices/appendix_v_computational_programs.md",
      "title": "Appendix V: Computational Programs and Numerical Consistency Checks",
      "label": "Computational Programs and Numerical Consistency Checks",
      "group": "Appendices",
      "number": "V",
      "hash": "4963d13140e20d3ba71e6c450a5d4cc16d569cd6ce602a9b83681292006dd74e"
    },
    {
      "id": "appendices--appendix_w_alphabet_identities",
      "file": "appendices/appendix_w_alphabet_identities.md",
      "title": "Appendix W — PU’s Alphabet‑Constant Identities, Robustness, and SM Structure",
      "label": "PU’s Alphabet‑Constant Identities, Robustness, and SM Structure",
      "group": "Appendices",
      "number": "W",
      "hash": "35f058277d59cb447db6d83c722f064efa295d9ced7411ec9fe36d83c7639664"
    },
    {
      "id": "appendices--appendix_x_effective_action",
      "file": "appendices/appendix_x_effective_action.md",
      "title": "Appendix X: PU and the Effective Action",
      "label": "PU and the Effective Action",
      "group": "Appendices",
      "number": "X",
      "hash": "5e80918e7e5253a09ac00887685e7d1319b919bf3c23efcf8872ac87c27ab2a2"
    },
    {
      "id": "appendices--appendix_y_baryon_asymmetry",
      "file": "appendices/appendix_y_baryon_asymmetry.md",
      "title": "Appendix Y — Baryon Asymmetry from Predictive Anomaly Inflow",
      "label": "Baryon Asymmetry from Predictive Anomaly Inflow",
      "group": "Appendices",
      "number": "Y",
      "hash": "9467cee60b1581eaf2090caf14d86205e0f1c596964a206856f4530c83ea0e23"
    },
    {
      "id": "appendices--appendix_z_fine_structure_constant",
      "file": "appendices/appendix_z_fine_structure_constant.md",
      "title": "APPENDIX Z: Certificate-Conditional Interface Ledger, Fine-Structure Candidate, and Euclidean Response-Carrier Dimension",
      "label": "Certificate-Conditional Interface Ledger, Fine-Structure Candidate, and Euclidean Response-Carrier Dimension",
      "group": "Appendices",
      "number": "Z",
      "hash": "8f850e45b443c7e0005f1df127467b44757c5b09cef5779445b8983ca6528c8e"
    },
    {
      "id": "glossary",
      "file": "glossary.md",
      "title": "Glossary of Key Terms",
      "label": "Glossary of Key Terms",
      "group": "Reference",
      "number": "",
      "hash": "442d1dfb659994761ed5fc49506750fd880853eeb99ec985fe7872e53ae0da57"
    },
    {
      "id": "references",
      "file": "references.md",
      "title": "References",
      "label": "References",
      "group": "Reference",
      "number": "",
      "hash": "e2de201161f2b59658ff42ef9edac1b5be20ae52863553b3dcbbd16b0c1d67b4"
    },
    {
      "id": "contents",
      "file": "contents.md",
      "title": "Table of Contents",
      "label": "Table of Contents",
      "group": "Reading guides & related work",
      "number": "",
      "hash": "74d95e0fe0fdcd21a343ba82e8dd27679cf441b8043ae343958e0281453a104e"
    },
    {
      "id": "map",
      "file": "map.md",
      "title": "The Predictive Universe: Structural Walkthrough",
      "label": "The Predictive Universe: Structural Walkthrough",
      "group": "Reading guides & related work",
      "number": "",
      "hash": "4ca9eba7056c2891bd656550f41d16ba2ed6f41a971026daf55f4654a20e38ba"
    },
    {
      "id": "related--area_law_spap_qecc",
      "file": "related/area_law_spap_qecc.md",
      "title": "Conditional Holographic-Code Ansatz for the PU Horizon Area Law",
      "label": "Conditional Holographic-Code Ansatz for the PU Horizon Area Law",
      "group": "Reading guides & related work",
      "number": "",
      "hash": "4d4324531d077ce31a8ed53b781187638e96411675a2d625134f3ef85429ab60"
    },
    {
      "id": "related--comparison",
      "file": "related/comparison.md",
      "title": "Comparative Perspectives: PU in the Landscape of Fundamental Physics",
      "label": "Comparative Perspectives: PU in the Landscape of Fundamental Physics",
      "group": "Reading guides & related work",
      "number": "",
      "hash": "2dd249df085437c66ad25b45b215331b16ddf39c27f7cc1b270c01a6281465b9"
    },
    {
      "id": "related--contextual_bibliography",
      "file": "related/contextual_bibliography.md",
      "title": "Bibliography of Related Ideas",
      "label": "Bibliography of Related Ideas",
      "group": "Reading guides & related work",
      "number": "",
      "hash": "e9ff5acc35179babf6d34105b819a7bc1983e9b1f954d4ed03d79c78be6b41bd"
    },
    {
      "id": "related--lite_framework",
      "file": "related/lite_framework.md",
      "title": "LITE: Dynamic Self-Reference in Peano Arithmetic",
      "label": "LITE: Dynamic Self-Reference in Peano Arithmetic",
      "group": "Reading guides & related work",
      "number": "",
      "hash": "42c8ca9200444d8476f4004df0cc717a3a31a14e318dff68c01596205928a4f0"
    },
    {
      "id": "related--proof_life_verification_model",
      "file": "related/proof_life_verification_model.md",
      "title": "Proof-Life: A Finite Verification-Gated Toy Universe for Proof Reachability",
      "label": "Proof-Life: A Finite Verification-Gated Toy Universe for Proof Reachability",
      "group": "Reading guides & related work",
      "number": "",
      "hash": "d81215b79c3023eeb6f634bd8074838dfd2fd378f9c8faa85bd2a55c862005bb"
    }
  ],
  "scenes": [
    {
      "key": "cogito",
      "title": "Cogito",
      "source": "Sections 1-2, 5",
      "sections": [
        "01_introduction",
        "02_foundations",
        "05_horizon_constant"
      ]
    },
    {
      "key": "becoming",
      "title": "Space of Becoming",
      "source": "Section 3",
      "sections": [
        "03_space_of_becoming"
      ]
    },
    {
      "key": "ledger",
      "title": "PPI / PCE Ledger",
      "source": "Sections 2, 6",
      "sections": [
        "02_foundations",
        "06_complexity_resources"
      ]
    },
    {
      "key": "spap",
      "title": "SPAP",
      "source": "Section 4, Appendix A",
      "sections": [
        "04_spap",
        "appendices--appendix_a_core_logic"
      ]
    },
    {
      "key": "entropy",
      "title": "Reset Ledger",
      "source": "Sections 7.5-7.6; Appendices E, J",
      "sections": [
        "07_minimal_predictive_unit",
        "appendices--appendix_e_thermo_area_law",
        "appendices--appendix_j_reflexivity_cost"
      ]
    },
    {
      "key": "mpu",
      "title": "MPU",
      "source": "Sections 5, 7; Appendix Z",
      "sections": [
        "05_horizon_constant",
        "07_minimal_predictive_unit",
        "appendices--appendix_z_fine_structure_constant"
      ]
    },
    {
      "key": "network",
      "title": "MPU Network",
      "source": "Section 7, Appendix C",
      "sections": [
        "07_minimal_predictive_unit",
        "appendices--appendix_c_regularity_necessity"
      ]
    },
    {
      "key": "pcegeo",
      "title": "PCE Geometry",
      "source": "Appendix C",
      "sections": [
        "appendices--appendix_c_regularity_necessity"
      ]
    },
    {
      "key": "quantum",
      "title": "Quantum State",
      "source": "Section 8",
      "sections": [
        "08_quantum_emergence"
      ]
    },
    {
      "key": "spinor",
      "title": "Spinor",
      "source": "Section 8, Appendix G",
      "sections": [
        "08_quantum_emergence",
        "appendices--appendix_g_gauge_emergence"
      ]
    },
    {
      "key": "golay",
      "title": "Golay Code",
      "source": "Sections 7.6, 13.9; Appendix Z",
      "sections": [
        "07_minimal_predictive_unit",
        "13_experimental_predictions",
        "appendices--appendix_z_fine_structure_constant"
      ]
    },
    {
      "key": "dim",
      "title": "D = 4 Gate",
      "source": "Appendix Z",
      "sections": [
        "appendices--appendix_z_fine_structure_constant"
      ]
    },
    {
      "key": "gauge",
      "title": "Gauge Sectors",
      "source": "Appendix G",
      "sections": [
        "appendices--appendix_g_gauge_emergence"
      ]
    },
    {
      "key": "particles",
      "title": "Particle Defects",
      "source": "Appendices R, T, Z",
      "sections": [
        "appendices--appendix_r_generations",
        "appendices--appendix_t_electroweak_hierarchy",
        "appendices--appendix_z_fine_structure_constant"
      ]
    },
    {
      "key": "relativity",
      "title": "Relativity",
      "source": "Section 11",
      "sections": [
        "11_spacetime_emergence"
      ]
    },
    {
      "key": "gravity",
      "title": "Emergent Gravity",
      "source": "Section 12",
      "sections": [
        "12_gravity_derivation"
      ]
    },
    {
      "key": "horizon",
      "title": "Predictive Horizon",
      "source": "Section 12; Appendix E",
      "sections": [
        "12_gravity_derivation",
        "appendices--appendix_e_thermo_area_law"
      ]
    },
    {
      "key": "blackhole",
      "title": "Black Hole",
      "source": "Appendix K",
      "sections": [
        "appendices--appendix_k_resolving_puzzles"
      ]
    },
    {
      "key": "predictors",
      "title": "Prediction Relativity",
      "source": "Appendix N",
      "sections": [
        "appendices--appendix_n_prediction_relativity"
      ]
    },
    {
      "key": "perspectival",
      "title": "Perspectival Info",
      "source": "Appendix M",
      "sections": [
        "appendices--appendix_m_perspectival_quantum_dynamics"
      ]
    },
    {
      "key": "consciousness",
      "title": "Consciousness Com.",
      "source": "Sections 9-10, 13; Appendix L",
      "sections": [
        "09_consciousness_complexity",
        "10_statistical_influence",
        "13_experimental_predictions",
        "appendices--appendix_l_cc_mechanism"
      ]
    },
    {
      "key": "dark",
      "title": "Dark Sector",
      "source": "Appendix I",
      "sections": [
        "appendices--appendix_i_scaled_gravity"
      ]
    },
    {
      "key": "vacuum",
      "title": "False-Vacuum Weight",
      "source": "Appendix U",
      "sections": [
        "appendices--appendix_u_cosmological_constant"
      ]
    },
    {
      "key": "cascade",
      "title": "K0 Cascade",
      "source": "Sections 5, 7; Appendix Z",
      "sections": [
        "05_horizon_constant",
        "07_minimal_predictive_unit",
        "appendices--appendix_z_fine_structure_constant"
      ]
    }
  ],
  "relatedPapers": [
    {
      "id": "related--pure_s_universality--paper",
      "title": "Pure S Is Computationally Universal Under a Fixed Root-Restarted Finite Controller",
      "source": "related/pure_s_universality/paper.md",
      "file": "related/pure_s_universality/output/pdf/pure_s_universality.pdf"
    }
  ]
};
