/* Local Unicode math symbols and operator names. */
const PU_MATH_SYMBOLS = {
  "greek": {
    "alpha": "α",
    "beta": "β",
    "gamma": "γ",
    "delta": "δ",
    "epsilon": "ϵ",
    "varepsilon": "ε",
    "zeta": "ζ",
    "eta": "η",
    "theta": "θ",
    "vartheta": "ϑ",
    "iota": "ι",
    "kappa": "κ",
    "lambda": "λ",
    "mu": "μ",
    "nu": "ν",
    "xi": "ξ",
    "pi": "π",
    "varpi": "ϖ",
    "rho": "ρ",
    "varrho": "ϱ",
    "sigma": "σ",
    "varsigma": "ς",
    "tau": "τ",
    "upsilon": "υ",
    "phi": "ϕ",
    "varphi": "φ",
    "chi": "χ",
    "psi": "ψ",
    "omega": "ω",
    "Gamma": "Γ",
    "Delta": "Δ",
    "Theta": "Θ",
    "Lambda": "Λ",
    "Xi": "Ξ",
    "Pi": "Π",
    "Sigma": "Σ",
    "Upsilon": "Υ",
    "Phi": "Φ",
    "Psi": "Ψ",
    "Omega": "Ω"
  },
  "syms": {
    "infty": "∞",
    "partial": "∂",
    "nabla": "∇",
    "forall": "∀",
    "exists": "∃",
    "nexists": "∄",
    "emptyset": "∅",
    "varnothing": "∅",
    "cdot": "·",
    "cdots": "⋯",
    "ldots": "…",
    "dots": "…",
    "ddots": "⋱",
    "vdots": "⋮",
    "times": "×",
    "div": "÷",
    "pm": "±",
    "mp": "∓",
    "circ": "∘",
    "bullet": "•",
    "star": "⋆",
    "ast": "∗",
    "dagger": "†",
    "leq": "≤",
    "le": "≤",
    "geq": "≥",
    "ge": "≥",
    "neq": "≠",
    "ne": "≠",
    "approx": "≈",
    "equiv": "≡",
    "sim": "∼",
    "simeq": "≃",
    "cong": "≅",
    "propto": "∝",
    "ll": "≪",
    "gg": "≫",
    "ggg": "⋙",
    "lesssim": "≲",
    "gtrsim": "≳",
    "asymp": "≍",
    "subset": "⊂",
    "supset": "⊃",
    "subseteq": "⊆",
    "supseteq": "⊇",
    "subsetneq": "⊊",
    "supsetneq": "⊋",
    "nsubseteq": "⊈",
    "Subset": "⋐",
    "in": "∈",
    "notin": "∉",
    "ni": "∋",
    "colon": ":",
    "cup": "∪",
    "cap": "∩",
    "sqcup": "⊔",
    "bigsqcup": "⨆",
    "setminus": "∖",
    "vee": "∨",
    "wedge": "∧",
    "oplus": "⊕",
    "otimes": "⊗",
    "boxtimes": "⊠",
    "odot": "⊙",
    "mid": "|",
    "to": "→",
    "rightarrow": "→",
    "leftarrow": "←",
    "Rightarrow": "⇒",
    "Leftarrow": "⇐",
    "leftrightarrow": "↔",
    "Leftrightarrow": "⇔",
    "mapsto": "↦",
    "longmapsto": "⟼",
    "rightrightarrows": "⇉",
    "longleftrightarrow": "⟷",
    "dashrightarrow": "⇢",
    "leadsto": "↝",
    "curvearrowright": "↷",
    "rightsquigarrow": "⇝",
    "langle": "⟨",
    "rangle": "⟩",
    "lbrack": "[",
    "rbrack": "]",
    "lfloor": "⌊",
    "rfloor": "⌋",
    "lceil": "⌈",
    "rceil": "⌉",
    "lVert": "‖",
    "rVert": "‖",
    "vert": "|",
    "Vert": "‖",
    "lvert": "|",
    "rvert": "|",
    "ulcorner": "⌜",
    "urcorner": "⌝",
    "backslash": "\\",
    "angle": "∠",
    "natural": "♮",
    "ell": "ℓ",
    "hbar": "ℏ",
    "Re": "ℜ",
    "Im": "ℑ",
    "wp": "℘",
    "aleph": "ℵ",
    "prime": "′",
    "neg": "¬",
    "flat": "♭",
    "sharp": "♯",
    "quad": "  ",
    "qquad": "    ",
    "land": "∧",
    "lor": "∨",
    "lnot": "¬",
    "implies": "⟹",
    "iff": "⟺",
    "top": "⊤",
    "bot": "⊥",
    "vdash": "⊢",
    "Vdash": "⊩",
    "models": "⊨",
    "perp": "⊥",
    "parallel": "∥",
    "leqslant": "⩽",
    "geqslant": "⩾",
    "coloneqq": "≔",
    "eqqcolon": "≕",
    "triangleq": "≜",
    "defeq": "≝",
    "diamond": "⋄",
    "triangleleft": "◁",
    "triangleright": "▷",
    "lhd": "◁",
    "rhd": "▷",
    "square": "□",
    "blacksquare": "■",
    "triangle": "△",
    "bigtriangleup": "△",
    "bigtriangledown": "▽",
    "succ": "≻",
    "prec": "≺",
    "succeq": "⪰",
    "preceq": "⪯",
    "imath": "ı",
    "jmath": "ȷ",
    "ltimes": "⋉",
    "rtimes": "⋊",
    "bowtie": "⋈",
    "Join": "⋈",
    "smile": "⌣",
    "frown": "⌢",
    "checkmark": "✓",
    "maltese": "✠",
    "restriction": "↾",
    "ominus": "⊖",
    "boxplus": "⊞",
    "rightleftarrows": "⇄",
    "sqcap": "⊓",
    "nsucceq": "⋡",
    "nvdash": "⊬",
    "oslash": "⊘",
    "hookrightarrow": "↪",
    "hookleftarrow": "↩",
    "longrightarrow": "⟶",
    "longleftarrow": "⟵",
    "Longrightarrow": "⟹",
    "Longleftarrow": "⟸",
    "Longleftrightarrow": "⟺",
    "leftsquigarrow": "⇜",
    "twoheadrightarrow": "↠",
    "rightharpoonup": "⇀",
    "rightharpoondown": "⇁",
    "uparrow": "↑",
    "downarrow": "↓",
    "updownarrow": "↕",
    "Uparrow": "⇑",
    "Downarrow": "⇓",
    "nearrow": "↗",
    "searrow": "↘",
    "nwarrow": "↖",
    "swarrow": "↙",
    "circlearrowleft": "↺",
    "circlearrowright": "↻"
  },
  "bigOps": {
    "int": "∫",
    "iint": "∬",
    "iiint": "∭",
    "oint": "∮",
    "sum": "∑",
    "prod": "∏",
    "coprod": "∐",
    "bigcup": "⋃",
    "bigcap": "⋂",
    "bigoplus": "⨁",
    "bigotimes": "⨂",
    "bigvee": "⋁",
    "bigwedge": "⋀",
    "bigsqcap": "⨅",
    "fint": "⨍"
  },
  "named": [
    "lim",
    "limsup",
    "liminf",
    "min",
    "max",
    "sup",
    "inf",
    "det",
    "dim",
    "ker",
    "deg",
    "hom",
    "arg",
    "log",
    "ln",
    "sin",
    "cos",
    "tan",
    "cot",
    "sec",
    "csc",
    "arcsin",
    "arccos",
    "arctan",
    "sinh",
    "cosh",
    "tanh",
    "coth",
    "exp",
    "Pr",
    "gcd",
    "tr",
    "Tr",
    "STr",
    "Str",
    "diag",
    "sgn",
    "mod",
    "Re",
    "Im",
    "im",
    "Dom",
    "Hom",
    "spec",
    "Spec",
    "sinc",
    "span",
    "supp",
    "rank",
    "Var",
    "Vol",
    "Pf",
    "weight",
    "eval",
    "Cov",
    "ch",
    "Aut",
    "Gr",
    "descArity",
    "or",
    "dist",
    "Ind",
    "id",
    "Pic",
    "coker",
    "Ann",
    "Seg",
    "Neg",
    "diam",
    "Lip",
    "Rep",
    "Box",
    "Req",
    "Ric",
    "SF",
    "int",
    "EssIm",
    "Inv",
    "conv",
    "Ran",
    "polylog",
    "Ent",
    "WF",
    "KL",
    "varinjlim",
    "CodeLength",
    "Adeq",
    "End",
    "rk",
    "Atom"
  ]
};
