import PureSFormal.Computation.CookWordConstructionMachine

#print axioms PureSFormal.Computation.CookWordConstructionMachine.replicateOnto_execution
#print axioms PureSFormal.Computation.CookWordConstructionMachine.replicateOnto_value
#print axioms PureSFormal.Computation.CookWordConstructionMachine.replicateOnto_operations
#print axioms PureSFormal.Computation.CookWordConstructionMachine.fixedBlock_value
#print axioms PureSFormal.Computation.CookWordConstructionMachine.selectOperations_le
#print axioms PureSFormal.Computation.CookWordConstructionMachine.append_execution
#print axioms PureSFormal.Computation.CookWordConstructionMachine.encodeOnto_execution
#print axioms PureSFormal.Computation.CookWordConstructionMachine.encodeOnto_value
#print axioms PureSFormal.Computation.CookWordConstructionMachine.encodeOnto_operations_le
#print axioms PureSFormal.Computation.CookWordConstructionMachine.encodeWord_value
#print axioms PureSFormal.Computation.CookWordConstructionMachine.encodeWord_operations_le
#print axioms PureSFormal.Computation.CookWordConstructionMachine.encodeWord_length
#print axioms PureSFormal.Computation.CookWordConstructionMachine.digit_value
#print axioms PureSFormal.Computation.CookWordConstructionMachine.digit_operations
#print axioms PureSFormal.Computation.CookWordConstructionMachine.counter_execution
#print axioms PureSFormal.Computation.CookWordConstructionMachine.counter_value
#print axioms PureSFormal.Computation.CookWordConstructionMachine.counter_operations_le
#print axioms PureSFormal.Computation.CookWordConstructionMachine.materialize_value
#print axioms PureSFormal.Computation.CookWordConstructionMachine.materialize_operations
#print axioms PureSFormal.Computation.CookWordConstructionMachine.runWord_length
#print axioms PureSFormal.Computation.CookWordConstructionMachine.headCount_value
#print axioms PureSFormal.Computation.CookWordConstructionMachine.headCount_operations
#print axioms PureSFormal.Computation.CookWordConstructionMachine.canonicalWord_value
#print axioms PureSFormal.Computation.CookWordConstructionMachine.canonicalWord_length
#print axioms PureSFormal.Computation.CookWordConstructionMachine.canonicalWord_operations_le
#print axioms PureSFormal.Computation.CookWordConstructionMachine.canonicalBits_value
#print axioms PureSFormal.Computation.CookWordConstructionMachine.canonicalBits_length
#print axioms PureSFormal.Computation.CookWordConstructionMachine.canonicalBits_operations_le
#print axioms PureSFormal.Computation.CookWordConstructionMachine.canonicalBits_operations_le_sizes
#print axioms PureSFormal.Computation.CookWordConstructionMachine.materialize_execution
#print axioms PureSFormal.Computation.CookWordConstructionMachine.canonicalWord_execution
#print axioms PureSFormal.Computation.CookWordConstructionMachine.canonicalBits_execution

