import PureSFormal.Computation.CookSeedTerminalPrimitive

#print axioms PureSFormal.Computation.CookSeedTerminalPrimitive.prepare_value
#print axioms PureSFormal.Computation.CookSeedTerminalPrimitive.ordinary_le
#print axioms PureSFormal.Computation.CookSeedTerminalPrimitive.primitive_le
#print axioms PureSFormal.Computation.CookSeedTerminalPrimitive.prepare_operations_le
#print axioms PureSFormal.Computation.CookSeedTerminalPrimitive.fourth_value
#print axioms PureSFormal.Computation.CookSeedTerminalPrimitive.fourth_operations
#print axioms PureSFormal.Computation.CookSeedTerminalPrimitive.payloadSecond_value
#print axioms PureSFormal.Computation.CookSeedTerminalPrimitive.payloadSecond_operations_le
#print axioms PureSFormal.Computation.CookSeedTerminalPrimitive.mapIndex
#print axioms PureSFormal.Computation.CookSeedTerminalPrimitive.widthHalts_value
#print axioms PureSFormal.Computation.CookSeedTerminalPrimitive.widthHalts_operations_le
#print axioms PureSFormal.Computation.CookSeedTerminalPrimitive.zeroIndex_value
#print axioms PureSFormal.Computation.CookSeedTerminalPrimitive.zeroIndex_operations
#print axioms PureSFormal.Computation.CookSeedTerminalPrimitive.zeroNextHalts_value
#print axioms PureSFormal.Computation.CookSeedTerminalPrimitive.zeroNextHalts_operations_le
#print axioms PureSFormal.Computation.CookSeedTerminalPrimitive.restoreAddress_value
#print axioms PureSFormal.Computation.CookSeedTerminalPrimitive.restoreAddress_operations_le
#print axioms PureSFormal.Computation.CookSeedTerminalPrimitive.ruleUndefined_value
#print axioms PureSFormal.Computation.CookSeedTerminalPrimitive.ruleUndefined_operations_le
#print axioms PureSFormal.Computation.CookSeedTerminalPrimitive.lookupOption_value
#print axioms PureSFormal.Computation.CookSeedTerminalPrimitive.lookupOption_operations_le
#print axioms PureSFormal.Computation.CookSeedTerminalPrimitive.terminalRow_value
#print axioms PureSFormal.Computation.CookSeedTerminalPrimitive.terminalResult_operations_le
#print axioms PureSFormal.Computation.CookSeedTerminalPrimitive.terminalRow_operations_le
#print axioms PureSFormal.Computation.CookSeedTerminalPrimitive.terminalBudget_mono
#print axioms PureSFormal.Computation.CookSeedTerminalPrimitive.terminal_certificate
