import PureSFormal.Computation.DeletionTwoTableConstructionMachine

#print axioms PureSFormal.Computation.DeletionTwoTableConstructionMachine.rename_value
#print axioms PureSFormal.Computation.DeletionTwoTableConstructionMachine.rename_operations_le
#print axioms PureSFormal.Computation.DeletionTwoTableConstructionMachine.wordOnto_value
#print axioms PureSFormal.Computation.DeletionTwoTableConstructionMachine.wordOnto_operations_le
#print axioms PureSFormal.Computation.DeletionTwoTableConstructionMachine.rhs_value
#print axioms PureSFormal.Computation.DeletionTwoTableConstructionMachine.rhs_operations_le
#print axioms PureSFormal.Computation.DeletionTwoTableConstructionMachine.tableOnto_value
#print axioms PureSFormal.Computation.DeletionTwoTableConstructionMachine.tableOnto_operations_le
#print axioms PureSFormal.Computation.DeletionTwoTableConstructionMachine.normalizeProgram_value
#print axioms PureSFormal.Computation.DeletionTwoTableConstructionMachine.normalizeProgram_operations_le
#print axioms PureSFormal.Computation.DeletionTwoTableConstructionMachine.normalizeWord_value
#print axioms PureSFormal.Computation.DeletionTwoTableConstructionMachine.normalizeWord_operations_le
#print axioms PureSFormal.Computation.DeletionTwoTableConstructionMachine.normalizeJob_value
#print axioms PureSFormal.Computation.DeletionTwoTableConstructionMachine.normalizeJob_operations_le
#print axioms PureSFormal.Computation.DeletionTwoTableConstructionMachine.normalizeProgram_rows
#print axioms PureSFormal.Computation.DeletionTwoTableConstructionMachine.normalizeWord_length
#print axioms PureSFormal.Computation.DeletionTwoTableConstructionMachine.rhs_length_le
#print axioms PureSFormal.Computation.DeletionTwoTableConstructionMachine.normalizedRows_cells_le
#print axioms PureSFormal.Computation.DeletionTwoTableConstructionMachine.tableCells_append
#print axioms PureSFormal.Computation.DeletionTwoTableConstructionMachine.normalizeProgram_cells_le
#print axioms PureSFormal.Computation.DeletionTwoTableConstructionMachine.normalizeJob_threeCounter_value
#print axioms PureSFormal.Computation.DeletionTwoTableConstructionMachine.normalizeJob_threeCounter_operations_le
#print axioms PureSFormal.Computation.DeletionTwoTableConstructionMachine.cookBits_value
#print axioms PureSFormal.Computation.DeletionTwoTableConstructionMachine.cookBits_operations_le
#print axioms PureSFormal.Computation.DeletionTwoTableConstructionMachine.wordOnto_execution
#print axioms PureSFormal.Computation.DeletionTwoTableConstructionMachine.rhs_execution
#print axioms PureSFormal.Computation.DeletionTwoTableConstructionMachine.tableOnto_execution
#print axioms PureSFormal.Computation.DeletionTwoTableConstructionMachine.normalizeProgram_execution
#print axioms PureSFormal.Computation.DeletionTwoTableConstructionMachine.normalizeWord_execution
#print axioms PureSFormal.Computation.DeletionTwoTableConstructionMachine.normalizeJob_execution
#print axioms PureSFormal.Computation.DeletionTwoTableConstructionMachine.cookBits_execution

