import PureSFormal.Computation.DeterministicTapeEncoderConstructionMachine

#print axioms PureSFormal.Computation.DeterministicTapeEncoderConstructionMachine.initialBudget
#print axioms PureSFormal.Computation.DeterministicTapeEncoderConstructionMachine.downstreamBudget
#print axioms PureSFormal.Computation.DeterministicTapeEncoderConstructionMachine.downstream_operations_le
#print axioms PureSFormal.Computation.DeterministicTapeEncoderConstructionMachine.fromSource
#print axioms PureSFormal.Computation.DeterministicTapeEncoderConstructionMachine.fromSource_value
#print axioms PureSFormal.Computation.DeterministicTapeEncoderConstructionMachine.sourceBudget
#print axioms PureSFormal.Computation.DeterministicTapeEncoderConstructionMachine.fromSource_operations_le
#print axioms PureSFormal.Computation.DeterministicTapeEncoderConstructionMachine.sourceBits
#print axioms PureSFormal.Computation.DeterministicTapeEncoderConstructionMachine.sourceBits_value
#print axioms PureSFormal.Computation.DeterministicTapeEncoderConstructionMachine.bitsBudget
#print axioms PureSFormal.Computation.DeterministicTapeEncoderConstructionMachine.sourceBits_operations_le
#print axioms PureSFormal.Computation.DeterministicTapeEncoderConstructionMachine.sourceBits_program_agreement
#print axioms PureSFormal.Computation.DeterministicTapeEncoderConstructionMachine.actions
#print axioms PureSFormal.Computation.DeterministicTapeEncoderConstructionMachine.sourceTerm
#print axioms PureSFormal.Computation.DeterministicTapeEncoderConstructionMachine.sourceTerm_value
#print axioms PureSFormal.Computation.DeterministicTapeEncoderConstructionMachine.termBudget
#print axioms PureSFormal.Computation.DeterministicTapeEncoderConstructionMachine.sourceTerm_operations_le
#print axioms PureSFormal.Computation.DeterministicTapeEncoderConstructionMachine.sourceTerm_program_agreement
#print axioms PureSFormal.Computation.DeterministicTapeEncoderConstructionMachine.SourceExecution
#print axioms PureSFormal.Computation.DeterministicTapeEncoderConstructionMachine.fromSource_execution
#print axioms PureSFormal.Computation.DeterministicTapeEncoderConstructionMachine.BitsExecution
#print axioms PureSFormal.Computation.DeterministicTapeEncoderConstructionMachine.bitsExecution_compose
#print axioms PureSFormal.Computation.DeterministicTapeEncoderConstructionMachine.sourceBits_execution
#print axioms PureSFormal.Computation.DeterministicTapeEncoderConstructionMachine.TermExecution
#print axioms PureSFormal.Computation.DeterministicTapeEncoderConstructionMachine.sourceTerm_execution
#print axioms PureSFormal.Computation.DeterministicTapeEncoderConstructionMachine.complete_encoder_certificate
