import PureSFormal.Computation.DeterministicTapeRootResetOutput
#print axioms PureSFormal.Computation.DeterministicTapeRootResetOutput.termAt_eq_persistent
#print axioms PureSFormal.Computation.DeterministicTapeRootResetOutput.selected_next
#print axioms PureSFormal.Computation.DeterministicTapeRootResetOutput.termAt_step
#print axioms PureSFormal.Computation.DeterministicTapeRootResetOutput.exists_literalRow_iff
#print axioms PureSFormal.Computation.DeterministicTapeRootResetOutput.exists_terminalRow_iff
#print axioms PureSFormal.Computation.DeterministicTapeRootResetOutput.exists_scannedOutput_iff
#print axioms PureSFormal.Computation.DeterministicTapeRootResetOutput.nonhalting_rejects_terminal
#print axioms PureSFormal.Computation.DeterministicTapeRootResetOutput.bitToggle_output_iff
#print axioms PureSFormal.Computation.DeterministicTapeRootResetOutput.source_output_iff
