import PureSFormal.Computation.DeterministicTapeEncodingPrimitives

#print axioms PureSFormal.Computation.DeterministicTapeEncodingPrimitives.Program.eval_machine
#print axioms PureSFormal.Computation.DeterministicTapeEncodingPrimitives.Program.eval_initialState
#print axioms PureSFormal.Computation.DeterministicTapeEncodingPrimitives.Program.eval_input
#print axioms PureSFormal.Computation.DeterministicTapeEncodingPrimitives.Program.eval_bitStateStep
#print axioms PureSFormal.Computation.DeterministicTapeEncodingPrimitives.Program.bitListCode_cons_tail
#print axioms PureSFormal.Computation.DeterministicTapeEncodingPrimitives.Program.bitListCode_cons_head
#print axioms PureSFormal.Computation.DeterministicTapeEncodingPrimitives.Program.bitList_length_le_code
#print axioms PureSFormal.Computation.DeterministicTapeEncodingPrimitives.Program.bitStateStepValue_cons
#print axioms PureSFormal.Computation.DeterministicTapeEncodingPrimitives.Program.iterate_bitState_nil
#print axioms PureSFormal.Computation.DeterministicTapeEncodingPrimitives.Program.iterate_bitState_of_length_le
#print axioms PureSFormal.Computation.DeterministicTapeEncodingPrimitives.Program.eval_bitListToNatList_code
#print axioms PureSFormal.Computation.DeterministicTapeEncodingPrimitives.Program.eval_bitListToNatList
#print axioms PureSFormal.Computation.DeterministicTapeEncodingPrimitives.Program.eval_natListToBitList
#print axioms PureSFormal.Computation.DeterministicTapeEncodingPrimitives.machine_primitiveRecursive
#print axioms PureSFormal.Computation.DeterministicTapeEncodingPrimitives.initialState_primitiveRecursive
#print axioms PureSFormal.Computation.DeterministicTapeEncodingPrimitives.input_primitiveRecursive
#print axioms PureSFormal.Computation.DeterministicTapeEncodingPrimitives.bitListToNatList_primitiveRecursive
#print axioms PureSFormal.Computation.DeterministicTapeEncodingPrimitives.natListToBitList_primitiveRecursive
