import PureSFormal.Computation.DeterministicTapeThreeCounterComputability

#print axioms PureSFormal.Computation.DeterministicTapeThreeCounterComputability.instructionDecode?_code
#print axioms PureSFormal.Computation.DeterministicTapeThreeCounterComputability.programDecode?_code
#print axioms PureSFormal.Computation.DeterministicTapeThreeCounterComputability.machineCode_eq_rows
#print axioms PureSFormal.Computation.DeterministicTapeThreeCounterComputability.ruleFor_getD
#print axioms PureSFormal.Computation.DeterministicTapeThreeCounterComputability.Program.eval_row
#print axioms PureSFormal.Computation.DeterministicTapeThreeCounterComputability.Program.eval_ruleOption
#print axioms PureSFormal.Computation.DeterministicTapeThreeCounterComputability.Program.eval_ruleWrite_some
#print axioms PureSFormal.Computation.DeterministicTapeThreeCounterComputability.Program.eval_ruleMove_some
#print axioms PureSFormal.Computation.DeterministicTapeThreeCounterComputability.Program.eval_ruleNext_some
#print axioms PureSFormal.Computation.DeterministicTapeThreeCounterComputability.Program.eval_pushBit
#print axioms PureSFormal.Computation.DeterministicTapeThreeCounterComputability.Program.eval_finish
#print axioms PureSFormal.Computation.DeterministicTapeThreeCounterComputability.Program.eval_phase
#print axioms PureSFormal.Computation.DeterministicTapeThreeCounterComputability.Program.eval_select
#print axioms PureSFormal.Computation.DeterministicTapeThreeCounterComputability.tabulate_eq_range_map
#print axioms PureSFormal.Computation.DeterministicTapeThreeCounterComputability.tabulate_getD
#print axioms PureSFormal.Computation.DeterministicTapeThreeCounterComputability.Program.eval_tableEntry
#print axioms PureSFormal.Computation.DeterministicTapeThreeCounterComputability.Program.eval_tableBound
#print axioms PureSFormal.Computation.DeterministicTapeThreeCounterComputability.Program.table
#print axioms PureSFormal.Computation.DeterministicTapeThreeCounterComputability.Program.eval_table_machine
#print axioms PureSFormal.Computation.DeterministicTapeThreeCounterComputability.Program.eval_table
#print axioms PureSFormal.Computation.DeterministicTapeThreeCounterComputability.Program.instanceTable
#print axioms PureSFormal.Computation.DeterministicTapeThreeCounterComputability.Program.eval_instanceTable
#print axioms PureSFormal.Computation.DeterministicTapeThreeCounterComputability.compileMachine_primitiveRecursive
#print axioms PureSFormal.Computation.DeterministicTapeThreeCounterComputability.compileInstanceMachine_primitiveRecursive
#print axioms PureSFormal.Computation.DeterministicTapeThreeCounterComputability.compiledTable_decode
#print axioms PureSFormal.Computation.DeterministicTapeThreeCounterComputability.compiledInstanceTable_decode
