import PureSFormal.Computation.DeterministicTapePrimitiveChronology

/-! Authored declaration axiom queries for DeterministicTapePrimitiveChronology. -/

#print axioms PureSFormal.Computation.DeterministicTapePrimitiveChronology.boundaryTime
#print axioms PureSFormal.Computation.DeterministicTapePrimitiveChronology.boundaryTime_decodes
#print axioms PureSFormal.Computation.DeterministicTapePrimitiveChronology.boundaryTime_lt_succ
#print axioms PureSFormal.Computation.DeterministicTapePrimitiveChronology.source_prefix_defined
#print axioms PureSFormal.Computation.DeterministicTapePrimitiveChronology.boundaryTime_strict
#print axioms PureSFormal.Computation.DeterministicTapePrimitiveChronology.accepted_at_boundaryTime
#print axioms PureSFormal.Computation.DeterministicTapePrimitiveChronology.sourceTime
#print axioms PureSFormal.Computation.DeterministicTapePrimitiveChronology.sourceTime_decodes
#print axioms PureSFormal.Computation.DeterministicTapePrimitiveChronology.sourceTime_strict
#print axioms PureSFormal.Computation.DeterministicTapePrimitiveChronology.sourceTime_exact_iff
#print axioms PureSFormal.Computation.DeterministicTapePrimitiveChronology.padded_sourceTime_decodes
#print axioms PureSFormal.Computation.DeterministicTapePrimitiveChronology.padded_sourceTime_strict
#print axioms PureSFormal.Computation.DeterministicTapePrimitiveChronology.padded_sourceTime_exact_iff
#print axioms PureSFormal.Computation.DeterministicTapePrimitiveChronology.padded_sourceTime_running_live

