import PureSFormal.Computation.DeterministicTapeOutputPrimitive

#print axioms PureSFormal.Computation.DeterministicTapeOutputPrimitive.row_value
#print axioms PureSFormal.Computation.DeterministicTapeOutputPrimitive.terminal_value
#print axioms PureSFormal.Computation.DeterministicTapeOutputPrimitive.scanned_value
#print axioms PureSFormal.Computation.DeterministicTapeOutputPrimitive.row_operations_le
#print axioms PureSFormal.Computation.DeterministicTapeOutputPrimitive.terminal_operations_le
#print axioms PureSFormal.Computation.DeterministicTapeOutputPrimitive.scanned_operations_le
#print axioms PureSFormal.Computation.DeterministicTapeOutputPrimitive.row_resource_certificate
#print axioms PureSFormal.Computation.DeterministicTapeOutputPrimitive.terminal_resource_certificate
#print axioms PureSFormal.Computation.DeterministicTapeOutputPrimitive.scanned_resource_certificate
#print axioms PureSFormal.Computation.DeterministicTapeOutputPrimitive.source_output_iff
#print axioms PureSFormal.Computation.DeterministicTapeOutputPrimitive.source_terminal_iff
