import PureSFormal.Computation.DeterministicTapeStatePaddingComputability

#print axioms PureSFormal.Computation.DeterministicTapeStatePaddingComputability.Program.eval_maximum
#print axioms PureSFormal.Computation.DeterministicTapeStatePaddingComputability.Program.eval_ruleTarget
#print axioms PureSFormal.Computation.DeterministicTapeStatePaddingComputability.Program.eval_rowTarget
#print axioms PureSFormal.Computation.DeterministicTapeStatePaddingComputability.Program.fold_tableStep
#print axioms PureSFormal.Computation.DeterministicTapeStatePaddingComputability.Program.eval_tableTarget
#print axioms PureSFormal.Computation.DeterministicTapeStatePaddingComputability.Program.eval_allocationSize
#print axioms PureSFormal.Computation.DeterministicTapeStatePaddingComputability.Program.eval_paddedMachine
#print axioms PureSFormal.Computation.DeterministicTapeStatePaddingComputability.Program.pad
#print axioms PureSFormal.Computation.DeterministicTapeStatePaddingComputability.Program.eval_pad
#print axioms PureSFormal.Computation.DeterministicTapeStatePaddingComputability.Program.eval_paddedBits
#print axioms PureSFormal.Computation.DeterministicTapeStatePaddingComputability.Program.paddedTerm
#print axioms PureSFormal.Computation.DeterministicTapeStatePaddingComputability.Program.eval_paddedTerm
#print axioms PureSFormal.Computation.DeterministicTapeStatePaddingComputability.pad_primitiveRecursive
#print axioms PureSFormal.Computation.DeterministicTapeStatePaddingComputability.pad_decodes
#print axioms PureSFormal.Computation.DeterministicTapeStatePaddingComputability.paddedTerm_primitiveRecursive
#print axioms PureSFormal.Computation.DeterministicTapeStatePaddingComputability.paddedTerm_computable
#print axioms PureSFormal.Computation.DeterministicTapeStatePaddingComputability.paddedTerm_decodes
