import PureSFormal.Computation.DeterministicTapeCookTrajectoryReadback

#print axioms PureSFormal.Computation.DeterministicTapeCookTrajectoryReadback.nonhaltingBefore_of_endpoint
#print axioms PureSFormal.Computation.DeterministicTapeCookTrajectoryReadback.ordinary_encodeState_step
#print axioms PureSFormal.Computation.DeterministicTapeCookTrajectoryReadback.ordinary_encodeState_run
#print axioms PureSFormal.Computation.DeterministicTapeCookTrajectoryReadback.ordinary_encodeState_notHalted
#print axioms PureSFormal.Computation.DeterministicTapeCookTrajectoryReadback.tokensValid_iterate
#print axioms PureSFormal.Computation.DeterministicTapeCookTrajectoryReadback.exists_normalized_source_boundary
#print axioms PureSFormal.Computation.DeterministicTapeCookTrajectoryReadback.exists_normalized_decoded_boundary
#print axioms PureSFormal.Computation.DeterministicTapeCookTrajectoryReadback.exists_decodeCounter?_iterate
#print axioms PureSFormal.Computation.DeterministicTapeCookTrajectoryReadback.exists_literalRow_at_actualCTS
#print axioms PureSFormal.Computation.DeterministicTapeCookTrajectoryReadback.exists_terminalRow_at_actualCTS
