import PureSFormal.Computation.DeterministicTapePaddedEncoderConstructionMachine

#print axioms PureSFormal.Computation.DeterministicTapePaddedEncoderConstructionMachine.sourceBits
#print axioms PureSFormal.Computation.DeterministicTapePaddedEncoderConstructionMachine.sourceBits_value
#print axioms PureSFormal.Computation.DeterministicTapePaddedEncoderConstructionMachine.bitsBudget
#print axioms PureSFormal.Computation.DeterministicTapePaddedEncoderConstructionMachine.sourceBits_operations_le
#print axioms PureSFormal.Computation.DeterministicTapePaddedEncoderConstructionMachine.sourceBits_program_agreement
#print axioms PureSFormal.Computation.DeterministicTapePaddedEncoderConstructionMachine.sourceTerm
#print axioms PureSFormal.Computation.DeterministicTapePaddedEncoderConstructionMachine.sourceTerm_value
#print axioms PureSFormal.Computation.DeterministicTapePaddedEncoderConstructionMachine.termBudget
#print axioms PureSFormal.Computation.DeterministicTapePaddedEncoderConstructionMachine.sourceTerm_operations_le
#print axioms PureSFormal.Computation.DeterministicTapePaddedEncoderConstructionMachine.sourceTerm_program_agreement
#print axioms PureSFormal.Computation.DeterministicTapePaddedEncoderConstructionMachine.sourceTerm_size_le
#print axioms PureSFormal.Computation.DeterministicTapePaddedEncoderConstructionMachine.BitsExecution
#print axioms PureSFormal.Computation.DeterministicTapePaddedEncoderConstructionMachine.bitsExecution_compose
#print axioms PureSFormal.Computation.DeterministicTapePaddedEncoderConstructionMachine.sourceBits_execution
#print axioms PureSFormal.Computation.DeterministicTapePaddedEncoderConstructionMachine.TermExecution
#print axioms PureSFormal.Computation.DeterministicTapePaddedEncoderConstructionMachine.sourceTerm_execution
#print axioms PureSFormal.Computation.DeterministicTapePaddedEncoderConstructionMachine.sourceTerm_is_actual_initial
#print axioms PureSFormal.Computation.DeterministicTapePaddedEncoderConstructionMachine.complete_padded_encoder_certificate
#print axioms PureSFormal.Computation.DeterministicTapePaddedEncoderConstructionMachine.encoder
#print axioms PureSFormal.Computation.DeterministicTapePaddedEncoderConstructionMachine.encoder_primitiveRecursive
#print axioms PureSFormal.Computation.DeterministicTapePaddedEncoderConstructionMachine.encoder_reducesVia
#print axioms PureSFormal.Computation.DeterministicTapePaddedEncoderConstructionMachine.computableManyOneReduction
#print axioms PureSFormal.Computation.DeterministicTapePaddedEncoderConstructionMachine.closedProgramReduction
