import PureSFormal.Computation.DeterministicTapeInitialConstructionMachine

#print axioms PureSFormal.Computation.DeterministicTapeInitialConstructionMachine.stack_value
#print axioms PureSFormal.Computation.DeterministicTapeInitialConstructionMachine.stack_operations_le
#print axioms PureSFormal.Computation.DeterministicTapeInitialConstructionMachine.initial_value
#print axioms PureSFormal.Computation.DeterministicTapeInitialConstructionMachine.initial_operations_le
#print axioms PureSFormal.Computation.DeterministicTapeInitialConstructionMachine.stack_execution
#print axioms PureSFormal.Computation.DeterministicTapeInitialConstructionMachine.initial_execution
