import PureSFormal.Computation.DeterministicTapeInitialConstructionMachine
import PureSFormal.PureS.ParserNatDivisionPrimitive

/-!
# Measured decoding of the total source-instance numbering

Input naturals are unary immutable chains. Cantor coordinates are generated by
walking the diagonal enumeration; quotient/remainder uses the unary primitive.
Fuel counters share the original code and are destructed structurally. They
make decoding total on all helper inputs, and the public decoder supplies a
proved sufficient fuel value. No source transition is executed.
-/
namespace PureSFormal.Computation.DeterministicTapeDecodeConstructionMachine

open PureSFormal.PureS
open PureSFormal.PureS.ParserPrimitiveMachine (Result)
open PureSFormal.Research.ProtectedTrieDeterministicCompiler
open PureSFormal.Research.ProtectedTrieMachine (Direction)

set_option maxRecDepth 4096

inductive FrontOperation where
  | observe | readChild | allocateRecord | allocateCons
  deriving DecidableEq, Repr

/-- Four coordinate reads, one binary-digit observation, the three-operation
direction-digit inspection, and allocation of the source rule record. -/
def ruleTrace : List FrontOperation :=
  [.readChild, .readChild, .readChild, .readChild, .observe,
    .observe, .readChild, .observe, .allocateRecord]

/-- Both fuel/code constructors and predecessors, two coordinate reads,
and the emitted source-table cons cell. -/
def rowsTrace : List FrontOperation :=
  [.observe, .readChild, .observe, .readChild, .readChild, .readChild, .allocateCons]

/-- The list decoder's fixed work includes both recursive arguments, both
division coordinates, the full is-one test, and the emitted Boolean cons. -/
def bitsTrace : List FrontOperation :=
  [.observe, .readChild, .observe, .readChild, .readChild, .readChild,
    .observe, .readChild, .observe, .allocateCons]

theorem frontEnd_trace_allowances :
    ruleTrace.length ≤ 12 ∧ rowsTrace.length ≤ 10 ∧ bitsTrace.length ≤ 12 := by decide

def nextPair : Nat × Nat → Result (Nat × Nat)
  | (0, right) => ⟨(Nat.succ right, 0), 7⟩
  | (.succ left, right) => ⟨(left, Nat.succ right), 7⟩

def unpair : Nat → Result (Nat × Nat)
  | 0 => ⟨(0, 0), 3⟩
  | .succ number =>
      let previous := unpair number
      let current := nextPair previous.value
      ⟨current.value, previous.operations + current.operations + 3⟩

theorem nextPair_value (pair : Nat × Nat) : (nextPair pair).value = Term.nextPair pair := by
  cases pair with | mk left right => cases left <;> rfl

theorem nextPair_operations (pair : Nat × Nat) : (nextPair pair).operations = 7 := by
  cases pair with | mk left right => cases left <;> rfl

theorem unpair_value (number : Nat) : (unpair number).value = Term.unpair number := by
  induction number with
  | zero => rfl
  | succ number ih => simp only [unpair, nextPair_value, ih, Term.unpair]

theorem unpair_operations (number : Nat) : (unpair number).operations = 10 * number + 3 := by
  induction number with
  | zero => rfl
  | succ number ih =>
      simp only [unpair, nextPair_operations, ih, Nat.mul_succ,
        show 10 = 7 + 3 by rfl, Nat.add_assoc, Nat.add_comm, Nat.add_left_comm]

theorem unpair_sum_le (number : Nat) : (unpair number).value.1 + (unpair number).value.2 ≤ number := by
  rw [unpair_value]
  have bound := Term.sum_le_pair (Term.unpair number).1 (Term.unpair number).2
  rw [Term.pair_unpair] at bound
  exact bound

theorem unpair_left_le (number : Nat) : (unpair number).value.1 ≤ number :=
  Nat.le_trans (Nat.le_add_right _ _) (unpair_sum_le number)

theorem unpair_right_le (number : Nat) : (unpair number).value.2 ≤ number :=
  Nat.le_trans (Nat.le_add_left _ _) (unpair_sum_le number)

def ruleWrite : Nat → Bool
  | 0 => false
  | _ => true

def ruleMove : Nat → PureSFormal.Research.ProtectedTrieMachine.Direction
  | 0 => .left
  | 1 => .stay
  | _ => .right

def rule (number : Nat) : Result DeterministicTape.Rule :=
  let binary := ParserNatDivisionPrimitive.divMod 2 number
  let ternary := ParserNatDivisionPrimitive.divMod 3 binary.value.1
  ⟨{ write := ruleWrite binary.value.2,
     move := ruleMove ternary.value.2,
     nextState := ternary.value.1 }, binary.operations + ternary.operations + 12⟩

theorem rule_value (number : Nat) : (rule number).value = DeterministicTapeCode.ruleDecode number := by
  simp only [rule, ruleWrite, ruleMove, ParserNatDivisionPrimitive.divMod_value,
    DeterministicTapeCode.ruleDecode, DeterministicTapeCode.boolDecode, DeterministicTapeCode.directionDecode]
  rfl

theorem rule_operations_le (number : Nat) : (rule number).operations ≤ 48 * number + 18 := by
  have first := ParserNatDivisionPrimitive.divMod_operations_le 2 number
  have second := Nat.le_trans (ParserNatDivisionPrimitive.divMod_operations_le 3
    (ParserNatDivisionPrimitive.divMod 2 number).value.1)
    (Nat.add_le_add_right (Nat.mul_le_mul_left 26 (ParserNatDivisionPrimitive.quotient_le 2 number)) 3)
  have combined := Nat.add_le_add_right (Nat.add_le_add first second) 12
  simpa only [rule, show 4 * 2 + 14 = 22 by rfl, show 4 * 3 + 14 = 26 by rfl,
    show 48 = 22 + 26 by rfl, show 18 = 3 + 3 + 12 by rfl,
    Nat.add_mul, Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using combined

def optionRule : Nat → Result (Option DeterministicTape.Rule)
  | 0 => ⟨none, 2⟩
  | .succ number =>
      let current := rule number
      ⟨some current.value, current.operations + 4⟩

theorem optionRule_value (number : Nat) :
    (optionRule number).value = DeterministicTapeCode.optionDecode DeterministicTapeCode.ruleDecode number := by
  cases number <;> simp only [optionRule, rule_value, DeterministicTapeCode.optionDecode]

theorem optionRule_operations_le (number : Nat) : (optionRule number).operations ≤ 48 * number + 22 := by
  cases number with
  | zero => exact (by decide : 2 ≤ 22)
  | succ number =>
      have bound := Nat.add_le_add_right (rule_operations_le number) 4
      exact Nat.le_trans bound (Nat.add_le_add_right (Nat.mul_le_mul_left 48 (Nat.le_succ number)) 22)

def row (number : Nat) : Result DeterministicTape.StateRow :=
  let coordinates := unpair number
  let left := optionRule coordinates.value.1
  let right := optionRule coordinates.value.2
  ⟨⟨left.value, right.value⟩, coordinates.operations + left.operations + right.operations + 4⟩

theorem row_value (number : Nat) : (row number).value = DeterministicTapeCode.stateRowDecode number := by
  simp only [row, unpair_value, optionRule_value, DeterministicTapeCode.stateRowDecode]

theorem row_operations_le (number : Nat) : (row number).operations ≤ 106 * number + 51 := by
  have left := Nat.le_trans (optionRule_operations_le (unpair number).value.1)
    (Nat.add_le_add_right (Nat.mul_le_mul_left 48 (unpair_left_le number)) 22)
  have right := Nat.le_trans (optionRule_operations_le (unpair number).value.2)
    (Nat.add_le_add_right (Nat.mul_le_mul_left 48 (unpair_right_le number)) 22)
  have bound := Nat.add_le_add_right (Nat.add_le_add (Nat.add_le_add_left left (unpair number).operations) right) 4
  simpa only [row, unpair_operations, show 106 = 10 + 48 + 48 by rfl,
    show 51 = 3 + 22 + 22 + 4 by rfl, Nat.add_mul,
    Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using bound

def rows : Nat → Nat → Result (List DeterministicTape.StateRow)
  | 0, _ => ⟨[], 2⟩
  | .succ _, 0 => ⟨[], 2⟩
  | .succ fuel, .succ number =>
      let coordinates := unpair number
      let current := row coordinates.value.1
      let rest := rows fuel coordinates.value.2
      ⟨current.value :: rest.value, coordinates.operations + current.operations + rest.operations + 10⟩

theorem rows_value (fuel number : Nat) (enough : number ≤ fuel) :
    (rows fuel number).value = DeterministicTapeCode.NatList.decode DeterministicTapeCode.stateRowDecode number := by
  induction fuel generalizing number with
  | zero =>
      have zero := Nat.eq_zero_of_le_zero enough
      subst number
      rw [DeterministicTapeCode.NatList.decode.eq_def]
      rfl
  | succ fuel ih =>
      cases number with
      | zero => rw [DeterministicTapeCode.NatList.decode.eq_def]; rfl
      | succ number =>
          have enoughTail := Nat.le_trans (unpair_right_le number) (Nat.le_of_succ_le_succ enough)
          rw [rows, ih _ enoughTail, row_value, unpair_value]
          rw [DeterministicTapeCode.NatList.decode.eq_def _ (number + 1)]
          simp only [Nat.succ_ne_zero, ↓reduceDIte, Nat.add_sub_cancel]

theorem rows_operations_le (fuel number limit : Nat) (bounded : number ≤ limit) :
    (rows fuel number).operations ≤ (fuel + 1) * (116 * limit + 72) := by
  have constant : 2 ≤ 116 * limit + 72 := Nat.le_trans (by decide : 2 ≤ 72) (Nat.le_add_left _ _)
  induction fuel generalizing number with
  | zero => simpa only [rows, Nat.zero_add, Nat.one_mul] using constant
  | succ fuel ih =>
      cases number with
      | zero => exact Nat.le_trans constant (Nat.le_mul_of_pos_left _ (Nat.zero_lt_succ _))
      | succ number =>
          have smaller := Nat.le_trans (Nat.le_succ number) bounded
          have first := Nat.le_trans (row_operations_le (unpair number).value.1)
            (Nat.add_le_add_right (Nat.mul_le_mul_left 106 (Nat.le_trans (unpair_left_le number) smaller)) 51)
          have coordinates : (unpair number).operations ≤ 10 * limit + 3 := by
            rw [unpair_operations]
            exact Nat.add_le_add_right (Nat.mul_le_mul_left 10 smaller) 3
          have step := Nat.add_le_add_right (Nat.add_le_add coordinates first) 10
          have stepBound : (unpair number).operations + (row (unpair number).value.1).operations + 10 ≤ 116 * limit + 72 := by
            apply Nat.le_trans step
            have extended := Nat.add_le_add_left (by decide : 3 + 51 + 10 ≤ 72) (116 * limit)
            simpa only [show 116 = 10 + 106 by rfl, Nat.add_mul,
              Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using extended
          have rest := ih (unpair number).value.2 (Nat.le_trans (unpair_right_le number) smaller)
          have total := Nat.add_le_add stepBound rest
          change (unpair number).operations + (row (unpair number).value.1).operations +
            (rows fuel (unpair number).value.2).operations + 10 ≤
              Nat.succ (fuel + 1) * (116 * limit + 72)
          rw [Nat.succ_mul]
          simpa only [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using total

def bitValue : Nat → Bool
  | 0 => false
  | 1 => true
  | _ => false

theorem bitValue_eq (number : Nat) : bitValue number = decide (number = 1) := by
  cases number with
  | zero => rfl
  | succ number => cases number <;> rfl

def bits : Nat → Nat → Result (List Bool)
  | 0, _ => ⟨[], 2⟩
  | .succ _, 0 => ⟨[], 2⟩
  | .succ fuel, .succ number =>
      let decoded := ParserNatDivisionPrimitive.divMod 2 number
      let rest := bits fuel decoded.value.1
      ⟨bitValue decoded.value.2 :: rest.value, decoded.operations + rest.operations + 12⟩

theorem bits_value (fuel number : Nat) (enough : number ≤ fuel) :
    (bits fuel number).value = DeterministicTapeCode.bitListDecode number := by
  induction fuel generalizing number with
  | zero =>
      have zero := Nat.eq_zero_of_le_zero enough
      subst number
      rw [DeterministicTapeCode.bitListDecode.eq_def]
      rfl
  | succ fuel ih =>
      cases number with
      | zero => rw [DeterministicTapeCode.bitListDecode.eq_def]; rfl
      | succ number =>
          have enoughTail := Nat.le_trans (ParserNatDivisionPrimitive.quotient_le 2 number)
            (Nat.le_of_succ_le_succ enough)
          rw [bits, ih _ enoughTail, ParserNatDivisionPrimitive.divMod_value,
            bitValue_eq, DeterministicTapeCode.bitListDecode.eq_def (number + 1)]
          by_cases odd : number % 2 = 1
          · simp only [odd, decide_true, ↓reduceIte]
          · simp only [odd, decide_false, ↓reduceIte]

theorem bits_operations_le (fuel number limit : Nat) (bounded : number ≤ limit) :
    (bits fuel number).operations ≤ (fuel + 1) * (22 * limit + 16) := by
  have constant : 2 ≤ 22 * limit + 16 := Nat.le_trans (by decide : 2 ≤ 16) (Nat.le_add_left _ _)
  induction fuel generalizing number with
  | zero => simpa only [bits, Nat.zero_add, Nat.one_mul] using constant
  | succ fuel ih =>
      cases number with
      | zero => exact Nat.le_trans constant (Nat.le_mul_of_pos_left _ (Nat.zero_lt_succ _))
      | succ number =>
          have smaller := Nat.le_trans (Nat.le_succ number) bounded
          have division := Nat.le_trans (ParserNatDivisionPrimitive.divMod_operations_le 2 number)
            (Nat.add_le_add_right (Nat.mul_le_mul_left 22 smaller) 3)
          have stepBound : (ParserNatDivisionPrimitive.divMod 2 number).operations + 12 ≤ 22 * limit + 16 :=
            Nat.le_trans (Nat.add_le_add_right division 12) (Nat.add_le_add_left (by decide : 3 + 12 ≤ 16) _)
          have rest := ih (ParserNatDivisionPrimitive.divMod 2 number).value.1
            (Nat.le_trans (ParserNatDivisionPrimitive.quotient_le 2 number) smaller)
          have total := Nat.add_le_add stepBound rest
          change (ParserNatDivisionPrimitive.divMod 2 number).operations +
            (bits fuel (ParserNatDivisionPrimitive.divMod 2 number).value.1).operations + 12 ≤
              Nat.succ (fuel + 1) * (22 * limit + 16)
          rw [Nat.succ_mul]
          simpa only [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using total

def decode (number : Nat) : Result DeterministicTape.Instance :=
  let outer := unpair number
  let inner := unpair outer.value.2
  let table := rows outer.value.1 outer.value.1
  let word := bits inner.value.2 inner.value.2
  ⟨{ machine := ⟨table.value⟩, initialState := inner.value.1, input := word.value },
    outer.operations + inner.operations + table.operations + word.operations + 8⟩

theorem decode_value (number : Nat) : (decode number).value = DeterministicTapeCode.instanceDecodeCode number := by
  simp only [decode, rows_value _ _ (Nat.le_refl _), bits_value _ _ (Nat.le_refl _),
    unpair_value, DeterministicTapeCode.instanceDecodeCode, DeterministicTapeCode.machineDecode]

def decodeBudget (number : Nat) : Nat :=
  (10 * number + 3) + (10 * number + 3) +
    (number + 1) * (116 * number + 72) + (number + 1) * (22 * number + 16) + 8

theorem decode_operations_le (number : Nat) : (decode number).operations ≤ decodeBudget number := by
  have outerRight := unpair_right_le number
  have innerRight := Nat.le_trans (unpair_right_le (unpair number).value.2) outerRight
  have innerBound : (unpair (unpair number).value.2).operations ≤ 10 * number + 3 := by
    rw [unpair_operations]
    exact Nat.add_le_add_right (Nat.mul_le_mul_left 10 outerRight) 3
  have tableBound := Nat.le_trans (rows_operations_le (unpair number).value.1 (unpair number).value.1
    number (unpair_left_le number))
    (Nat.mul_le_mul_right (116 * number + 72) (Nat.succ_le_succ (unpair_left_le number)))
  have wordBound := Nat.le_trans (bits_operations_le (unpair (unpair number).value.2).value.2
    (unpair (unpair number).value.2).value.2 number innerRight)
    (Nat.mul_le_mul_right (22 * number + 16) (Nat.succ_le_succ innerRight))
  have result := Nat.add_le_add_right (Nat.add_le_add
    (Nat.add_le_add (Nat.add_le_add_left innerBound (unpair number).operations) tableBound) wordBound) 8
  simpa only [decode, decodeBudget, unpair_operations] using result

theorem decodeBudget_polynomial (number : Nat) :
    decodeBudget number = 138 * (number * number) + 246 * number + 102 := by
  simp only [decodeBudget, show 138 = 116 + 22 by rfl,
    show 246 = 10 + 10 + 72 + 116 + 16 + 22 by rfl,
    show 102 = 3 + 3 + 72 + 16 + 8 by rfl,
    Nat.mul_add, Nat.add_mul, Nat.one_mul, Nat.mul_one]
  simp only [Nat.mul_assoc, Nat.mul_comm, Nat.mul_left_comm, Nat.add_assoc, Nat.add_comm, Nat.add_left_comm]

theorem decode_operations_polynomial (number : Nat) :
    (decode number).operations ≤ 138 * (number * number) + 246 * number + 102 := by
  rw [← decodeBudget_polynomial]
  exact decode_operations_le number

theorem rule_covers_fixedOperations (number : Nat) :
    (ParserNatDivisionPrimitive.divMod 2 number).operations +
      (ParserNatDivisionPrimitive.divMod 3 (ParserNatDivisionPrimitive.divMod 2 number).value.1).operations +
      ruleTrace.length ≤ (rule number).operations :=
  Nat.add_le_add_left frontEnd_trace_allowances.1 _

theorem rows_covers_fixedOperations (fuel number : Nat) :
    (unpair number).operations + (row (unpair number).value.1).operations +
      (rows fuel (unpair number).value.2).operations + rowsTrace.length ≤
        (rows (.succ fuel) (.succ number)).operations :=
  Nat.add_le_add_left frontEnd_trace_allowances.2.1 _

theorem bits_covers_fixedOperations (fuel number : Nat) :
    (ParserNatDivisionPrimitive.divMod 2 number).operations +
      (bits fuel (ParserNatDivisionPrimitive.divMod 2 number).value.1).operations + bitsTrace.length ≤
        (bits (.succ fuel) (.succ number)).operations :=
  Nat.add_le_add_left frontEnd_trace_allowances.2.2 _

inductive UnpairExecution : Nat → (Nat × Nat) → Nat → Prop where
  | zero : UnpairExecution 0 (0, 0) 3
  | diagonal {number right operations : Nat} (previous : UnpairExecution number (0, right) operations) :
      UnpairExecution (.succ number) (.succ right, 0) (operations + 7 + 3)
  | advance {number left right operations : Nat} (previous : UnpairExecution number (.succ left, right) operations) :
      UnpairExecution (.succ number) (left, .succ right) (operations + 7 + 3)

theorem unpair_execution (number : Nat) : UnpairExecution number (unpair number).value (unpair number).operations := by
  induction number with
  | zero => exact .zero
  | succ number ih =>
      cases coordinates : (unpair number).value with
      | mk left right =>
          rw [coordinates] at ih
          cases left with
          | zero => simpa only [unpair, coordinates, nextPair] using UnpairExecution.diagonal ih
          | succ left => simpa only [unpair, coordinates, nextPair] using UnpairExecution.advance ih

inductive DivisionExecution (radix : Nat) : Nat → (Nat × Nat) → Nat → Prop where
  | zero : DivisionExecution radix 0 (0, 0) 3
  | wrap {number quotient remainder operations : Nat}
      (previous : DivisionExecution radix number (quotient, remainder) operations)
      (same : (ParserTerminalPrimitive.equalIndex (.succ remainder) radix).value = true) :
      DivisionExecution radix (.succ number) (.succ quotient, 0)
        (operations + (ParserTerminalPrimitive.equalIndex (.succ remainder) radix).operations + 12)
  | retain {number quotient remainder operations : Nat}
      (previous : DivisionExecution radix number (quotient, remainder) operations)
      (different : (ParserTerminalPrimitive.equalIndex (.succ remainder) radix).value = false) :
      DivisionExecution radix (.succ number) (quotient, .succ remainder)
        (operations + (ParserTerminalPrimitive.equalIndex (.succ remainder) radix).operations + 11)

theorem division_execution (radix number : Nat) :
    DivisionExecution radix number (ParserNatDivisionPrimitive.divMod radix number).value
      (ParserNatDivisionPrimitive.divMod radix number).operations := by
  induction number with
  | zero => exact .zero
  | succ number ih =>
      rw [ParserNatDivisionPrimitive.divMod]
      split
      next same => exact .wrap ih same
      next different =>
        have no : (ParserTerminalPrimitive.equalIndex
            (.succ (ParserNatDivisionPrimitive.divMod radix number).value.2) radix).value = false :=
          by
            cases selected : (ParserTerminalPrimitive.equalIndex
              (.succ (ParserNatDivisionPrimitive.divMod radix number).value.2) radix).value
            · rfl
            · exact False.elim (different selected)
        exact .retain ih no

inductive RuleExecution (number : Nat) : DeterministicTape.Rule → Nat → Prop where
  | construct {quotient binaryRemainder target ternaryRemainder binaryOperations ternaryOperations : Nat}
      (binary : DivisionExecution 2 number (quotient, binaryRemainder) binaryOperations)
      (ternary : DivisionExecution 3 quotient (target, ternaryRemainder) ternaryOperations) :
      RuleExecution number
        { write := ruleWrite binaryRemainder,
          move := ruleMove ternaryRemainder,
          nextState := target } (binaryOperations + ternaryOperations + 12)

theorem rule_execution (number : Nat) : RuleExecution number (rule number).value (rule number).operations :=
  .construct (division_execution 2 number) (division_execution 3 _)

inductive OptionExecution : Nat → Option DeterministicTape.Rule → Nat → Prop where
  | zero : OptionExecution 0 none 2
  | some {number operations : Nat} {current : DeterministicTape.Rule}
      (selected : RuleExecution number current operations) :
      OptionExecution (.succ number) (some current) (operations + 4)

theorem optionRule_execution (number : Nat) :
    OptionExecution number (optionRule number).value (optionRule number).operations := by
  cases number with
  | zero => exact .zero
  | succ number => exact .some (rule_execution number)

inductive RowExecution (number : Nat) : DeterministicTape.StateRow → Nat → Prop where
  | construct {left right pairOperations leftOperations rightOperations : Nat}
      {leftRule rightRule : Option DeterministicTape.Rule}
      (coordinates : UnpairExecution number (left, right) pairOperations)
      (leftRun : OptionExecution left leftRule leftOperations)
      (rightRun : OptionExecution right rightRule rightOperations) :
      RowExecution number ⟨leftRule, rightRule⟩ (pairOperations + leftOperations + rightOperations + 4)

theorem row_execution (number : Nat) : RowExecution number (row number).value (row number).operations :=
  .construct (unpair_execution number) (optionRule_execution _) (optionRule_execution _)

inductive RowsExecution : Nat → Nat → List DeterministicTape.StateRow → Nat → Prop where
  | exhausted (number : Nat) : RowsExecution 0 number [] 2
  | nil (fuel : Nat) : RowsExecution (.succ fuel) 0 [] 2
  | cons {fuel number first rest pairOperations rowOperations restOperations : Nat}
      {current : DeterministicTape.StateRow} {remaining : List DeterministicTape.StateRow}
      (coordinates : UnpairExecution number (first, rest) pairOperations)
      (headRun : RowExecution first current rowOperations)
      (tailRun : RowsExecution fuel rest remaining restOperations) :
      RowsExecution (.succ fuel) (.succ number) (current :: remaining)
        (pairOperations + rowOperations + restOperations + 10)

theorem rows_execution (fuel number : Nat) : RowsExecution fuel number (rows fuel number).value (rows fuel number).operations := by
  induction fuel generalizing number with
  | zero => exact .exhausted number
  | succ fuel ih =>
      cases number with
      | zero => exact .nil fuel
      | succ number => exact .cons (unpair_execution number) (row_execution _) (ih _)

inductive BitsExecution : Nat → Nat → List Bool → Nat → Prop where
  | exhausted (number : Nat) : BitsExecution 0 number [] 2
  | nil (fuel : Nat) : BitsExecution (.succ fuel) 0 [] 2
  | cons {fuel number quotient remainder divisionOperations restOperations : Nat} {rest : List Bool}
      (division : DivisionExecution 2 number (quotient, remainder) divisionOperations)
      (following : BitsExecution fuel quotient rest restOperations) :
      BitsExecution (.succ fuel) (.succ number) (bitValue remainder :: rest)
        (divisionOperations + restOperations + 12)

theorem bits_execution (fuel number : Nat) : BitsExecution fuel number (bits fuel number).value (bits fuel number).operations := by
  induction fuel generalizing number with
  | zero => exact .exhausted number
  | succ fuel ih =>
      cases number with
      | zero => exact .nil fuel
      | succ number => exact .cons (division_execution 2 number) (ih _)

inductive DecodeExecution (number : Nat) : DeterministicTape.Instance → Nat → Prop where
  | construct {tableCode innerCode initial inputCode outerOperations innerOperations tableOperations inputOperations : Nat}
      {table : List DeterministicTape.StateRow} {input : List Bool}
      (outer : UnpairExecution number (tableCode, innerCode) outerOperations)
      (inner : UnpairExecution innerCode (initial, inputCode) innerOperations)
      (tableRun : RowsExecution tableCode tableCode table tableOperations)
      (inputRun : BitsExecution inputCode inputCode input inputOperations) :
      DecodeExecution number { machine := ⟨table⟩, initialState := initial, input := input }
        (outerOperations + innerOperations + tableOperations + inputOperations + 8)

theorem decode_execution (number : Nat) : DecodeExecution number (decode number).value (decode number).operations :=
  .construct (unpair_execution number) (unpair_execution _) (rows_execution _ _) (bits_execution _ _)

end PureSFormal.Computation.DeterministicTapeDecodeConstructionMachine


