import PureSFormal.Computation.DeterministicTapePureSComputability

#print axioms PureSFormal.Computation.DeterministicTapePureSComputability.Program.eval_termApplication
#print axioms PureSFormal.Computation.DeterministicTapePureSComputability.Program.eval_wordStateStep
#print axioms PureSFormal.Computation.DeterministicTapePureSComputability.Program.eval_wordStateLoop
#print axioms PureSFormal.Computation.DeterministicTapePureSComputability.WordCorrectness.runWordState_bitListCode
#print axioms PureSFormal.Computation.DeterministicTapePureSComputability.WordCorrectness.eval_wordCodeProgram
#print axioms PureSFormal.Computation.DeterministicTapePureSComputability.Generator.generatorProgram_correct
#print axioms PureSFormal.Computation.DeterministicTapePureSComputability.Generator.generatorProgram_correct_total
#print axioms PureSFormal.Computation.DeterministicTapePureSComputability.Generator.generatorCode_primitiveRecursive
#print axioms PureSFormal.Computation.DeterministicTapePureSComputability.Generator.generatorCode_computable
#print axioms PureSFormal.Computation.DeterministicTapePureSComputability.FixedEndpoint.generatorProgram_correct
#print axioms PureSFormal.Computation.DeterministicTapePureSComputability.FixedEndpoint.generatorCode_primitiveRecursive
#print axioms PureSFormal.Computation.DeterministicTapePureSComputability.FixedEndpoint.generatorCode_computable
#print axioms PureSFormal.Computation.DeterministicTapePureSComputability.FixedEndpoint.encodeTermCode_primitiveRecursive_of_encodeBitsCode
#print axioms PureSFormal.Computation.DeterministicTapePureSComputability.FixedEndpoint.encodeTermCode_computable_of_encodeBitsCode_primitiveRecursive
