import PureSFormal.Computation.DeterministicTapeInfiniteTape
open PureSFormal.Computation.DeterministicTapeInfiniteTape
#print axioms tapeAt
#print axioms tapeAt_negative
#print axioms tapeAt_after
#print axioms tapeAt_blank_cons
#print axioms tapeAt_blank_append
#print axioms scanned_exists
#print axioms replace_exists
#print axioms tapeAt_replace
#print axioms window
#print axioms displacement
#print axioms movedOrigin
#print axioms move_valid
#print axioms move_head
#print axioms move_tape
#print axioms Infinite.Config
#print axioms Infinite.lookup
#print axioms Infinite.write
#print axioms Infinite.apply
#print axioms Infinite.step?
#print axioms Infinite.runFor?
#print axioms Infinite.initial
#print axioms Infinite.Halts
#print axioms Represents
#print axioms embed
#print axioms embed_represents
#print axioms lookup_agrees
#print axioms initial_represents
#print axioms Represents.scanned
#print axioms Represents.blank_outside
#print axioms applyRule_represents
#print axioms step_forward
#print axioms step_backward
#print axioms undefined_step_iff
#print axioms run_forward
#print axioms run_backward
#print axioms halts_iff
#print axioms step_preserves_valid
#print axioms run_preserves_valid
#print axioms returns_iff
