import PureSFormal.Computation.DeterministicTapeInitialComputability

#print axioms PureSFormal.Computation.DeterministicTapeInitialComputability.decodeState?_stateCode
#print axioms PureSFormal.Computation.DeterministicTapeInitialComputability.stackCode_eq_bitListCode_succ
#print axioms PureSFormal.Computation.DeterministicTapeInitialComputability.initialRight_eq
#print axioms PureSFormal.Computation.DeterministicTapeInitialComputability.Program.eval_inputLength
#print axioms PureSFormal.Computation.DeterministicTapeInitialComputability.Program.eval_control
#print axioms PureSFormal.Computation.DeterministicTapeInitialComputability.Program.eval_left
#print axioms PureSFormal.Computation.DeterministicTapeInitialComputability.Program.eval_right
#print axioms PureSFormal.Computation.DeterministicTapeInitialComputability.Program.eval_initialState
#print axioms PureSFormal.Computation.DeterministicTapeInitialComputability.Program.initialState_decodes
#print axioms PureSFormal.Computation.DeterministicTapeInitialComputability.initialState_primitiveRecursive
