import PureSFormal.Computation.DeterministicTapeOutputQuartic

#print axioms PureSFormal.Computation.DeterministicTapeOutputQuartic.Polynomial.majorant
#print axioms PureSFormal.Computation.DeterministicTapeOutputQuartic.seedCost_value
#print axioms PureSFormal.Computation.DeterministicTapeOutputQuartic.seedCost_degree
#print axioms PureSFormal.Computation.DeterministicTapeOutputQuartic.seedCost_coefficient
#print axioms PureSFormal.Computation.DeterministicTapeOutputQuartic.seedCost_operations_le
#print axioms PureSFormal.Computation.DeterministicTapeOutputQuartic.sum_quartic
#print axioms PureSFormal.Computation.DeterministicTapeOutputQuartic.scannedBudget_le
#print axioms PureSFormal.Computation.DeterministicTapeOutputQuartic.rowSuffix_le_terminal
#print axioms PureSFormal.Computation.DeterministicTapeOutputQuartic.terminalSuffix_le_scanned
#print axioms PureSFormal.Computation.DeterministicTapeOutputQuartic.rowBudget_le_terminal
#print axioms PureSFormal.Computation.DeterministicTapeOutputQuartic.terminalBudget_le_scanned
#print axioms PureSFormal.Computation.DeterministicTapeOutputQuartic.row_operations_le
#print axioms PureSFormal.Computation.DeterministicTapeOutputQuartic.terminal_operations_le
#print axioms PureSFormal.Computation.DeterministicTapeOutputQuartic.scanned_operations_le
#print axioms PureSFormal.Computation.DeterministicTapeOutputQuartic.complete_output_resource_certificate
