import PureSFormal.Computation.EncodedSigmaOneNatEvent

/-! Exact logical-basis audit for the fixed natural-coded source interface. -/

#print axioms PureSFormal.Computation.EncodedSigmaOneNatEvent.invalidCode_not_mem
#print axioms PureSFormal.Computation.EncodedSigmaOneNatEvent.decodeCode?_encodeJobCode
#print axioms PureSFormal.Computation.EncodedSigmaOneNatEvent.decodeCode?_encodeFormulaCode
#print axioms PureSFormal.Computation.EncodedSigmaOneNatEvent.termCode_reducesVia
#print axioms PureSFormal.Computation.EncodedSigmaOneNatEvent.codedLanguage_semidecidable
#print axioms PureSFormal.Computation.EncodedSigmaOneNatEvent.fixedTermCode_reducesVia
#print axioms PureSFormal.Computation.EncodedSigmaOneNatEvent.universalAccepts_iff_fixedPureSMarkedSnapshotNatLanguage
#print axioms PureSFormal.Computation.EncodedSigmaOneNatEvent.encodeJobCode_reducesVia
#print axioms PureSFormal.Computation.EncodedSigmaOneNatEvent.counterProgram_accepts_iff_fixedPureSMarkedSnapshotNatLanguage
#print axioms PureSFormal.Computation.EncodedSigmaOneNatEvent.encodedBoundedWitnessFormula_iff_fixedPureSMarkedSnapshotNatLanguage
#print axioms PureSFormal.Computation.EncodedSigmaOneNatEvent.encodeFormulaCode_reducesVia
#print axioms PureSFormal.Computation.EncodedSigmaOneNatEvent.fixedPureSMarkedSnapshotNatLanguage_counterMachineHardViaNamedEncoder
#print axioms PureSFormal.Computation.EncodedSigmaOneNatEvent.fixedPureSMarkedSnapshotNatLanguage_encodedBoundedWitnessHardViaNamedEncoder
#print axioms PureSFormal.Computation.EncodedSigmaOneNatEvent.fixedPureSMarkedSnapshotNatLanguage_semidecidable
#print axioms PureSFormal.Computation.EncodedSigmaOneNatEvent.fixedPureSMarkedSnapshotNatLanguage_encodedBoundedWitnessComplete
#print axioms PureSFormal.Computation.EncodedSigmaOneNatEvent.fixedPureSMarkedSnapshotNatLanguage_counterMachineComplete
