import PureSFormal.Computation.RogozhinContextDataPrimitive

#print axioms PureSFormal.Computation.RogozhinContextDataPrimitive.widths_value
#print axioms PureSFormal.Computation.RogozhinContextDataPrimitive.widths_operations_le
#print axioms PureSFormal.Computation.RogozhinContextDataPrimitive.widths_length_le
#print axioms PureSFormal.Computation.RogozhinContextDataPrimitive.labels_value
#print axioms PureSFormal.Computation.RogozhinContextDataPrimitive.labels_length
#print axioms PureSFormal.Computation.RogozhinContextDataPrimitive.labels_operations_le
#print axioms PureSFormal.Computation.RogozhinContextDataPrimitive.dataTail_value
#print axioms PureSFormal.Computation.RogozhinContextDataPrimitive.dataTail_operations_le
#print axioms PureSFormal.Computation.RogozhinContextDataPrimitive.dataTail_length_le
#print axioms PureSFormal.Computation.RogozhinContextDataPrimitive.dataCode_value
#print axioms PureSFormal.Computation.RogozhinContextDataPrimitive.dataCode_operations_le
#print axioms PureSFormal.Computation.RogozhinContextDataPrimitive.dataCode_length_le
#print axioms PureSFormal.Computation.RogozhinContextDataPrimitive.symbolEqual_value
#print axioms PureSFormal.Computation.RogozhinContextDataPrimitive.symbolEqual_operations
#print axioms PureSFormal.Computation.RogozhinContextDataPrimitive.equalCells_value
#print axioms PureSFormal.Computation.RogozhinContextDataPrimitive.equalCells_operations_le
#print axioms PureSFormal.Computation.RogozhinContextDataPrimitive.decodeNonempty_value
#print axioms PureSFormal.Computation.RogozhinContextDataPrimitive.decode_value
#print axioms PureSFormal.Computation.RogozhinContextDataPrimitive.dataBudget_sum_eq
#print axioms PureSFormal.Computation.RogozhinContextDataPrimitive.decodeNonempty_operations_le
#print axioms PureSFormal.Computation.RogozhinContextDataPrimitive.decode_operations_le
#print axioms PureSFormal.Computation.RogozhinContextDataPrimitive.decode_length_le
