import PureSFormal.Computation.RogozhinFirstSweepExclusion

#print axioms PureSFormal.Computation.RogozhinFirstSweepExclusion.LocalBoundary
#print axioms PureSFormal.Computation.RogozhinFirstSweepExclusion.dataTail_no_three
#print axioms PureSFormal.Computation.RogozhinFirstSweepExclusion.program_reverse_head
#print axioms PureSFormal.Computation.RogozhinFirstSweepExclusion.decoded_nonempty_local
#print axioms PureSFormal.Computation.RogozhinFirstSweepExclusion.not_local_of_state
#print axioms PureSFormal.Computation.RogozhinFirstSweepExclusion.not_local_of_current
#print axioms PureSFormal.Computation.RogozhinFirstSweepExclusion.not_local_of_three
#print axioms PureSFormal.Computation.RogozhinFirstSweepExclusion.marked_left_not_local
#print axioms PureSFormal.Computation.RogozhinFirstSweepExclusion.leftPosition_not_local
#print axioms PureSFormal.Computation.RogozhinFirstSweepExclusion.rightPosition_not_local
#print axioms PureSFormal.Computation.RogozhinFirstSweepExclusion.Through
#print axioms PureSFormal.Computation.RogozhinFirstSweepExclusion.through_append
#print axioms PureSFormal.Computation.RogozhinFirstSweepExclusion.through_one
#print axioms PureSFormal.Computation.RogozhinFirstSweepExclusion.leftPosition_through
#print axioms PureSFormal.Computation.RogozhinFirstSweepExclusion.rightPosition_through
#print axioms PureSFormal.Computation.RogozhinFirstSweepExclusion.excursion_positive_not_local
#print axioms PureSFormal.Computation.RogozhinFirstSweepExclusion.firstBoundary_step_positive_not_local
#print axioms PureSFormal.Computation.RogozhinFirstSweepExclusion.firstSweep_positive_not_local
#print axioms PureSFormal.Computation.RogozhinFirstSweepExclusion.compiled_firstSweep_positive_not_local
#print axioms PureSFormal.Computation.RogozhinFirstSweepExclusion.compiled_firstSweep_rejects_nonempty
