import PureSFormal.Computation.RogozhinBoundaryOperationalReflection

#print axioms PureSFormal.Computation.RogozhinBoundaryOperationalReflection.not_local_of_notDataHead
#print axioms PureSFormal.Computation.RogozhinBoundaryOperationalReflection.splice_exclusion
#print axioms PureSFormal.Computation.RogozhinBoundaryOperationalReflection.firstSweep_endpoint
#print axioms PureSFormal.Computation.RogozhinBoundaryOperationalReflection.nonhalting_macro_interior_not_local
#print axioms PureSFormal.Computation.RogozhinBoundaryOperationalReflection.halting_macro_positive_not_local
#print axioms PureSFormal.Computation.RogozhinBoundaryOperationalReflection.tag_iterate_step
#print axioms PureSFormal.Computation.RogozhinBoundaryOperationalReflection.decodeBoundary?_actual_nonempty_reflects
