import PureSFormal.Computation.RogozhinT2Simulation

-- Structural, unbounded sweep certificates for the fixed Rogozhin machine.
#print axioms PureSFormal.Computation.RogozhinT2Simulation.iterate_firstSweepFuel
#print axioms PureSFormal.Computation.RogozhinT2Simulation.iterate_compile_firstSweep
#print axioms PureSFormal.Computation.RogozhinT2Simulation.iterate_secondSweep_toProgram
#print axioms PureSFormal.Computation.RogozhinT2Simulation.dBeforeCode_markRightLetters
#print axioms PureSFormal.Computation.RogozhinT2Simulation.iterate_markExcursion
#print axioms PureSFormal.Computation.RogozhinT2Simulation.iterate_selectorAndProduction
#print axioms PureSFormal.Computation.RogozhinT2Simulation.iterate_thirdSweep_core
#print axioms PureSFormal.Computation.RogozhinT2Simulation.iterate_thirdSweep
#print axioms PureSFormal.Computation.RogozhinT2Simulation.iterate_thirdSweep_coreWithCarry
#print axioms PureSFormal.Computation.RogozhinT2Simulation.iterate_compileWithPadding_nonhaltingMacro
#print axioms PureSFormal.Computation.RogozhinT2Simulation.safeThrough_of_endpoint_not_halted
#print axioms PureSFormal.Computation.RogozhinT2Simulation.safeThrough_compileWithPadding_firstSweep
#print axioms PureSFormal.Computation.RogozhinT2Simulation.safeThrough_secondSweep_toProgram_withCarry
#print axioms PureSFormal.Computation.RogozhinT2Simulation.safeThrough_selectorAndProduction_withCarry
#print axioms PureSFormal.Computation.RogozhinT2Simulation.safeThrough_thirdSweep_withCarry
#print axioms PureSFormal.Computation.RogozhinT2Simulation.safeThrough_compileWithPadding_nonhaltingMacro
