import PureSFormal.Computation.RogozhinContextProgramPrimitive

#print axioms PureSFormal.Computation.RogozhinContextProgramPrimitive.exponentSize_eq
#print axioms PureSFormal.Computation.RogozhinContextProgramPrimitive.exponentTail_length_le
#print axioms PureSFormal.Computation.RogozhinContextProgramPrimitive.exponentCode_length_le
#print axioms PureSFormal.Computation.RogozhinContextProgramPrimitive.exponentCode_operations_le_size
#print axioms PureSFormal.Computation.RogozhinContextProgramPrimitive.frameOnto_value
#print axioms PureSFormal.Computation.RogozhinContextProgramPrimitive.frameOnto_operations_le
#print axioms PureSFormal.Computation.RogozhinContextProgramPrimitive.frameOnto_length_le
#print axioms PureSFormal.Computation.RogozhinContextProgramPrimitive.frames_value
#print axioms PureSFormal.Computation.RogozhinContextProgramPrimitive.frames_operations_le
#print axioms PureSFormal.Computation.RogozhinContextProgramPrimitive.frames_length_le
#print axioms PureSFormal.Computation.RogozhinContextProgramPrimitive.program_value
#print axioms PureSFormal.Computation.RogozhinContextProgramPrimitive.program_operations_le
#print axioms PureSFormal.Computation.RogozhinContextProgramPrimitive.program_length_le
#print axioms PureSFormal.Computation.RogozhinContextProgramPrimitive.reversedProgram_value
#print axioms PureSFormal.Computation.RogozhinContextProgramPrimitive.reversedProgram_operations_le
#print axioms PureSFormal.Computation.RogozhinContextProgramPrimitive.reversedProgram_length_le
#print axioms PureSFormal.Computation.RogozhinContextProgramPrimitive.stripAudit_value
#print axioms PureSFormal.Computation.RogozhinContextProgramPrimitive.stripAudit_operations_le
#print axioms PureSFormal.Computation.RogozhinContextProgramPrimitive.programMatches_value
#print axioms PureSFormal.Computation.RogozhinContextProgramPrimitive.programMatches_operations_le
