import PureSFormal.Computation.RogozhinContextBoundaryPrimitive

#print axioms PureSFormal.Computation.RogozhinContextBoundaryPrimitive.dataAt_value
#print axioms PureSFormal.Computation.RogozhinContextBoundaryPrimitive.dataAt_operations_le
#print axioms PureSFormal.Computation.RogozhinContextBoundaryPrimitive.dataAt_length_le
#print axioms PureSFormal.Computation.RogozhinContextBoundaryPrimitive.afterProgram_operations_le
#print axioms PureSFormal.Computation.RogozhinContextBoundaryPrimitive.boundary_value
#print axioms PureSFormal.Computation.RogozhinContextBoundaryPrimitive.boundary_operations_le
#print axioms PureSFormal.Computation.RogozhinContextBoundaryPrimitive.boundary_length_le
#print axioms PureSFormal.Computation.RogozhinContextBoundaryPrimitive.dataBudget_mono
#print axioms PureSFormal.Computation.RogozhinContextBoundaryPrimitive.boundaryBudget_mono
#print axioms PureSFormal.Computation.RogozhinContextBoundaryPrimitive.passTag_value
#print axioms PureSFormal.Computation.RogozhinContextBoundaryPrimitive.passTag_operations_le
#print axioms PureSFormal.Computation.RogozhinContextBoundaryPrimitive.passTag_length_le
