import PureSFormal.Computation.RogozhinInputConstructionMachine

#print axioms PureSFormal.Computation.RogozhinInputConstructionMachine.length_value
#print axioms PureSFormal.Computation.RogozhinInputConstructionMachine.length_operations
#print axioms PureSFormal.Computation.RogozhinInputConstructionMachine.lookup_value
#print axioms PureSFormal.Computation.RogozhinInputConstructionMachine.lookup_operations_le
#print axioms PureSFormal.Computation.RogozhinInputConstructionMachine.reverseOnto_value
#print axioms PureSFormal.Computation.RogozhinInputConstructionMachine.reverseOnto_operations
#print axioms PureSFormal.Computation.RogozhinInputConstructionMachine.weight_value
#print axioms PureSFormal.Computation.RogozhinInputConstructionMachine.weight_operations_le
#print axioms PureSFormal.Computation.RogozhinInputConstructionMachine.weightAndOnes_operations_le
#print axioms PureSFormal.Computation.RogozhinInputConstructionMachine.dataTail_value
#print axioms PureSFormal.Computation.RogozhinInputConstructionMachine.dataTail_length_cons
#print axioms PureSFormal.Computation.RogozhinInputConstructionMachine.dataTail_operations_le
#print axioms PureSFormal.Computation.RogozhinInputConstructionMachine.dataCode_value
#print axioms PureSFormal.Computation.RogozhinInputConstructionMachine.dataCode_operations_le
#print axioms PureSFormal.Computation.RogozhinInputConstructionMachine.length_execution
#print axioms PureSFormal.Computation.RogozhinInputConstructionMachine.lookup_execution
#print axioms PureSFormal.Computation.RogozhinInputConstructionMachine.reverseOnto_execution
#print axioms PureSFormal.Computation.RogozhinInputConstructionMachine.weight_execution
#print axioms PureSFormal.Computation.RogozhinInputConstructionMachine.dataTail_execution
#print axioms PureSFormal.Computation.RogozhinInputConstructionMachine.dataCode_execution

