import PureSFormal.Computation.RogozhinT2Correctness

#print axioms PureSFormal.Computation.RogozhinT2Simulation.tagIterate_succ_from
#print axioms PureSFormal.Computation.RogozhinT2Simulation.eventuallyHalts_of_iterate_eq
#print axioms PureSFormal.Computation.RogozhinT2Simulation.eventuallyHalts_compileWithPadding_of_halted
#print axioms PureSFormal.Computation.RogozhinT2Simulation.eventuallyHalts_compileWithPadding_of_sourceWitness
#print axioms PureSFormal.Computation.RogozhinT2Simulation.sourceEventuallyHalts_implies_compiledEventuallyHalts
#print axioms PureSFormal.Computation.RogozhinT2Simulation.sourceEventuallyHalts_or_nonhaltingBefore
#print axioms PureSFormal.Computation.RogozhinT2Simulation.compiledEventuallyHalts_implies_sourceEventuallyHalts
#print axioms PureSFormal.Computation.RogozhinT2Simulation.eventuallyHalts_compile_iff
