import PureSFormal.Computation.ThreeCounterTagInputConstructionMachine

#print axioms PureSFormal.Computation.ThreeCounterTagInputConstructionMachine.block_value
#print axioms PureSFormal.Computation.ThreeCounterTagInputConstructionMachine.block_operations_le
#print axioms PureSFormal.Computation.ThreeCounterTagInputConstructionMachine.canonical_value
#print axioms PureSFormal.Computation.ThreeCounterTagInputConstructionMachine.canonical_operations_le
#print axioms PureSFormal.Computation.ThreeCounterTagInputConstructionMachine.typedState_value
#print axioms PureSFormal.Computation.ThreeCounterTagInputConstructionMachine.typedState_operations_le
#print axioms PureSFormal.Computation.ThreeCounterTagInputConstructionMachine.ordinaryWord_value
#print axioms PureSFormal.Computation.ThreeCounterTagInputConstructionMachine.ordinaryWord_length
#print axioms PureSFormal.Computation.ThreeCounterTagInputConstructionMachine.ordinaryWord_operations_le
#print axioms PureSFormal.Computation.ThreeCounterTagInputConstructionMachine.compile_value
#print axioms PureSFormal.Computation.ThreeCounterTagInputConstructionMachine.compile_operations_le
#print axioms PureSFormal.Computation.ThreeCounterTagInputConstructionMachine.cookBits_value
#print axioms PureSFormal.Computation.ThreeCounterTagInputConstructionMachine.cookBits_operations_le
#print axioms PureSFormal.Computation.ThreeCounterTagInputConstructionMachine.block_execution
#print axioms PureSFormal.Computation.ThreeCounterTagInputConstructionMachine.canonical_execution
#print axioms PureSFormal.Computation.ThreeCounterTagInputConstructionMachine.typedState_execution
#print axioms PureSFormal.Computation.ThreeCounterTagInputConstructionMachine.ordinaryWord_execution
#print axioms PureSFormal.Computation.ThreeCounterTagInputConstructionMachine.compile_execution
#print axioms PureSFormal.Computation.ThreeCounterTagInputConstructionMachine.cookBits_execution
#print axioms PureSFormal.Computation.ThreeCounterTagInputConstructionMachine.cookBits_source_value
