import PureSFormal.Computation.ThreeCounterSymbolReadbackPrimitive

#print axioms PureSFormal.Computation.ThreeCounterSymbolReadbackPrimitive.sameFamily
#print axioms PureSFormal.Computation.ThreeCounterSymbolReadbackPrimitive.same
#print axioms PureSFormal.Computation.ThreeCounterSymbolReadbackPrimitive.same_value
#print axioms PureSFormal.Computation.ThreeCounterSymbolReadbackPrimitive.same_operations_le
#print axioms PureSFormal.Computation.ThreeCounterSymbolReadbackPrimitive.mass
#print axioms PureSFormal.Computation.ThreeCounterSymbolReadbackPrimitive.count
#print axioms PureSFormal.Computation.ThreeCounterSymbolReadbackPrimitive.count_value
#print axioms PureSFormal.Computation.ThreeCounterSymbolReadbackPrimitive.count_le_length
#print axioms PureSFormal.Computation.ThreeCounterSymbolReadbackPrimitive.count_operations_le
#print axioms PureSFormal.Computation.ThreeCounterSymbolReadbackPrimitive.equalWords
#print axioms PureSFormal.Computation.ThreeCounterSymbolReadbackPrimitive.equalWords_value
#print axioms PureSFormal.Computation.ThreeCounterSymbolReadbackPrimitive.equalWords_operations_le
#print axioms PureSFormal.Computation.ThreeCounterSymbolReadbackPrimitive.CountExecution
#print axioms PureSFormal.Computation.ThreeCounterSymbolReadbackPrimitive.count_execution
#print axioms PureSFormal.Computation.ThreeCounterSymbolReadbackPrimitive.EqualityExecution
#print axioms PureSFormal.Computation.ThreeCounterSymbolReadbackPrimitive.equalWords_execution
