import PureSFormal.Computation.ThreeCounterRadixReadbackPrimitive

#print axioms PureSFormal.Computation.ThreeCounterRadixReadbackPrimitive.exponent
#print axioms PureSFormal.Computation.ThreeCounterRadixReadbackPrimitive.exponent_value
#print axioms PureSFormal.Computation.ThreeCounterRadixReadbackPrimitive.exponent_operations_le
#print axioms PureSFormal.Computation.ThreeCounterRadixReadbackPrimitive.exponent_power_le_positive
#print axioms PureSFormal.Computation.ThreeCounterRadixReadbackPrimitive.exponent_power_le
#print axioms PureSFormal.Computation.ThreeCounterRadixReadbackPrimitive.radixExponent_power_le
#print axioms PureSFormal.Computation.ThreeCounterRadixReadbackPrimitive.radixExponent_le
#print axioms PureSFormal.Computation.ThreeCounterRadixReadbackPrimitive.read
#print axioms PureSFormal.Computation.ThreeCounterRadixReadbackPrimitive.read_value
#print axioms PureSFormal.Computation.ThreeCounterRadixReadbackPrimitive.read_operations_le
#print axioms PureSFormal.Computation.ThreeCounterRadixReadbackPrimitive.ExponentExecution
#print axioms PureSFormal.Computation.ThreeCounterRadixReadbackPrimitive.exponent_execution
#print axioms PureSFormal.Computation.ThreeCounterRadixReadbackPrimitive.read_execution
