import PureSFormal.Computation.ThreeCounterTagConstructionSize

#print axioms PureSFormal.Computation.ThreeCounterTagConstructionSize.scale_le_two
#print axioms PureSFormal.Computation.ThreeCounterTagConstructionSize.lane_formula_le_eight
#print axioms PureSFormal.Computation.ThreeCounterTagConstructionSize.laneMultiplicity_le_eight
#print axioms PureSFormal.Computation.ThreeCounterTagConstructionSize.production_length_le_eight
#print axioms PureSFormal.Computation.ThreeCounterTagConstructionSize.ordinary_symbolCount
#print axioms PureSFormal.Computation.ThreeCounterTagConstructionSize.normalized_symbolCount
#print axioms PureSFormal.Computation.ThreeCounterTagConstructionSize.normalized_row_length
#print axioms PureSFormal.Computation.ThreeCounterTagConstructionSize.tableCells_le
#print axioms PureSFormal.Computation.ThreeCounterTagConstructionSize.normalized_tableCells
#print axioms PureSFormal.Computation.ThreeCounterTagConstructionSize.encodeState_length
#print axioms PureSFormal.Computation.ThreeCounterTagConstructionSize.normalized_initialWord_length
#print axioms PureSFormal.Computation.ThreeCounterTagConstructionSize.registerMass_le
#print axioms PureSFormal.Computation.ThreeCounterTagConstructionSize.initialMass_le
#print axioms PureSFormal.Computation.ThreeCounterTagConstructionSize.normalized_initialWord_le
#print axioms PureSFormal.Computation.ThreeCounterTagConstructionSize.source_symbolCount
#print axioms PureSFormal.Computation.ThreeCounterTagConstructionSize.source_tableCells
#print axioms PureSFormal.Computation.ThreeCounterTagConstructionSize.source_initialWord_le
