import PureSFormal.Computation.ThreeCounterTagBoundaryReflection

#print axioms PureSFormal.Computation.ThreeCounterTagBoundaryReflection.tagIterate_prefix_head_ne
#print axioms PureSFormal.Computation.ThreeCounterTagBoundaryReflection.head_not_mem_alternativeWord
#print axioms PureSFormal.Computation.ThreeCounterTagBoundaryReflection.firstSweep_prefix_ne_head
#print axioms PureSFormal.Computation.ThreeCounterTagBoundaryReflection.positiveLane_prefix_ne_head
#print axioms PureSFormal.Computation.ThreeCounterTagBoundaryReflection.zeroLane_prefix_ne_head
#print axioms PureSFormal.Computation.ThreeCounterTagBoundaryReflection.live_macro_prefix_ne_head
#print axioms PureSFormal.Computation.ThreeCounterTagBoundaryReflection.haltPair_head_ne
#print axioms PureSFormal.Computation.ThreeCounterTagBoundaryReflection.tagIterate_head_reflects_source
