import PureSFormal.Computation.ThreeCounterNumericBoundaryReflection

#print axioms PureSFormal.Computation.ThreeCounterNumericBoundaryReflection.numeric_halt_head_fixed
#print axioms PureSFormal.Computation.ThreeCounterNumericBoundaryReflection.numeric_iterate_succ_front
#print axioms PureSFormal.Computation.ThreeCounterNumericBoundaryReflection.numeric_iterate_represented
#print axioms PureSFormal.Computation.ThreeCounterNumericBoundaryReflection.decodeSymbol_sameLength
#print axioms PureSFormal.Computation.ThreeCounterNumericBoundaryReflection.decodeSymbols_sameLength
#print axioms PureSFormal.Computation.ThreeCounterNumericBoundaryReflection.decodeCounterWord?_actual_reflects
#print axioms PureSFormal.Computation.ThreeCounterNumericBoundaryReflection.encodeState_head_fields
#print axioms PureSFormal.Computation.ThreeCounterNumericBoundaryReflection.decodeCounterWord?_compiled_reflects
