import PureSFormal.Computation.ThreeCounterTagProgramConstructionMachine

#print axioms PureSFormal.Computation.ThreeCounterTagProgramConstructionMachine.prepare_value
#print axioms PureSFormal.Computation.ThreeCounterTagProgramConstructionMachine.prepare_operations
#print axioms PureSFormal.Computation.ThreeCounterTagProgramConstructionMachine.ordinaryProgram_value
#print axioms PureSFormal.Computation.ThreeCounterTagProgramConstructionMachine.ordinaryProgram_operations_le
#print axioms PureSFormal.Computation.ThreeCounterTagProgramConstructionMachine.ordinaryProgram_rows
#print axioms PureSFormal.Computation.ThreeCounterTagProgramConstructionMachine.ordinaryProgram_cells_le
#print axioms PureSFormal.Computation.ThreeCounterTagProgramConstructionMachine.normalizedProgram_value
#print axioms PureSFormal.Computation.ThreeCounterTagProgramConstructionMachine.normalizedProgram_compileT2
#print axioms PureSFormal.Computation.ThreeCounterTagProgramConstructionMachine.normalizedProgram_operations_le
#print axioms PureSFormal.Computation.ThreeCounterTagProgramConstructionMachine.normalizedProgram_rows
#print axioms PureSFormal.Computation.ThreeCounterTagProgramConstructionMachine.normalizedProgram_cells_le
#print axioms PureSFormal.Computation.ThreeCounterTagProgramConstructionMachine.prepare_execution
#print axioms PureSFormal.Computation.ThreeCounterTagProgramConstructionMachine.ordinaryProgram_execution
#print axioms PureSFormal.Computation.ThreeCounterTagProgramConstructionMachine.normalizedProgram_execution
